export interface CountryData {
  code: string;
  name: string;
  languageCode: string;
  currency: string;
  currencySymbol: string;
  headline: string;
  subheadline: string;
  metaDescription: string;
  testimonial: {
    name: string;
    company: string;
    city: string;
    quote: string;
  };
  localKeywords: string[];
  pricing: {
    creator: number;
    pro: number;
    agency: number;
  };
}

export const VALID_COUNTRY_CODES = new Set([
  'us', 'uk', 'ca', 'au', 'de', 'fr', 'es', 'it', 'nl', 'se',
  'br', 'mx', 'in', 'jp', 'kr', 'sg', 'ae', 'za', 'nz', 'ie',
]);

export const COUNTRY_DATA: Record<string, CountryData> = {
  us: {
    code: 'us',
    name: 'United States',
    languageCode: 'en-US',
    currency: 'USD',
    currencySymbol: '$',
    headline: 'AI Website Builder in the United States',
    subheadline: 'Join thousands of American businesses building stunning websites in 90 seconds — from New York startups to Silicon Valley scale-ups.',
    metaDescription: 'Build professional websites with AI in 90 seconds. Trusted by US businesses coast to coast. Free trial, no coding needed. Start building today.',
    testimonial: {
      name: 'Sarah Mitchell',
      company: 'Redwood Digital',
      city: 'Austin, TX',
      quote: 'We replaced our entire Webflow workflow. Our agency builds client sites 10x faster now — saved us $4,200/month in dev costs.',
    },
    localKeywords: ['AI website builder USA', 'website builder United States', 'American website creator', 'build website AI US', 'no-code website builder America'],
    pricing: { creator: 19, pro: 49, agency: 99 },
  },
  uk: {
    code: 'uk',
    name: 'United Kingdom',
    languageCode: 'en-GB',
    currency: 'GBP',
    currencySymbol: '£',
    headline: 'AI Website Builder in the United Kingdom',
    subheadline: 'From London fintech to Manchester e-commerce — UK businesses are building professional websites in under two minutes with AI.',
    metaDescription: 'AI-powered website builder for UK businesses. Build in 90 seconds, deploy instantly. GDPR compliant. Plans from £15/mo. Try free.',
    testimonial: {
      name: 'James Hartley',
      company: 'Brick Lane Studio',
      city: 'London',
      quote: 'Launched three client sites in a single afternoon. Our Shoreditch clients love the quality — they think we spent weeks on each.',
    },
    localKeywords: ['AI website builder UK', 'website builder United Kingdom', 'British website creator', 'build website AI UK', 'no-code website builder Britain'],
    pricing: { creator: 15, pro: 39, agency: 79 },
  },
  ca: {
    code: 'ca',
    name: 'Canada',
    languageCode: 'en-CA',
    currency: 'CAD',
    currencySymbol: 'C$',
    headline: 'AI Website Builder in Canada',
    subheadline: 'Canadian businesses from Vancouver to Toronto are shipping professional websites in 90 seconds — bilingual-ready, no developers needed.',
    metaDescription: 'Build websites with AI in 90 seconds. Trusted by Canadian businesses. Bilingual support, local hosting. Plans from C$26/mo. Try free.',
    testimonial: {
      name: 'Marie-Claire Dubois',
      company: 'Nordique Creative',
      city: 'Montreal, QC',
      quote: 'We needed bilingual sites fast for our hospitality clients. Zoobicon generates them in both English and French — cut our turnaround from weeks to hours.',
    },
    localKeywords: ['AI website builder Canada', 'website builder Canadian', 'build website AI Canada', 'no-code website builder Canada', 'Canadian web design AI'],
    pricing: { creator: 26, pro: 67, agency: 135 },
  },
  au: {
    code: 'au',
    name: 'Australia',
    languageCode: 'en-AU',
    currency: 'AUD',
    currencySymbol: 'A$',
    headline: 'AI Website Builder in Australia',
    subheadline: 'Aussie businesses from Sydney to Perth are building high-converting websites in 90 seconds flat — no agency fees, no waiting.',
    metaDescription: 'AI website builder for Australian businesses. Build in 90 seconds, deploy instantly. Plans from A$29/mo. No coding required. Try free.',
    testimonial: {
      name: 'Liam Chen',
      company: 'Harbour Point Digital',
      city: 'Sydney, NSW',
      quote: 'Our surf school needed a site fast before summer. Built it during a coffee break — bookings went up 3x in the first month.',
    },
    localKeywords: ['AI website builder Australia', 'website builder Australian', 'build website AI Australia', 'no-code website builder Australia', 'Aussie web design AI'],
    pricing: { creator: 29, pro: 75, agency: 149 },
  },
  de: {
    code: 'de',
    name: 'Germany',
    languageCode: 'de-DE',
    currency: 'EUR',
    currencySymbol: '€',
    headline: 'AI Website Builder in Germany',
    subheadline: 'Deutsche Unternehmen von Berlin bis München erstellen professionelle Websites in 90 Sekunden — DSGVO-konform, ohne Programmierkenntnisse.',
    metaDescription: 'KI-Website-Builder für deutsche Unternehmen. In 90 Sekunden erstellen, sofort veröffentlichen. DSGVO-konform. Ab 18€/Monat. Jetzt testen.',
    testimonial: {
      name: 'Markus Weber',
      company: 'Neukölln Labs',
      city: 'Berlin',
      quote: 'DSGVO-konform ab der ersten Sekunde. Wir haben 12 Kundenseiten in einer Woche erstellt — vorher brauchten wir dafür einen Monat.',
    },
    localKeywords: ['KI Website Builder Deutschland', 'Website erstellen KI', 'Webseite erstellen Deutschland', 'AI Website Builder Germany', 'Homepage Baukasten KI'],
    pricing: { creator: 18, pro: 45, agency: 90 },
  },
  fr: {
    code: 'fr',
    name: 'France',
    languageCode: 'fr-FR',
    currency: 'EUR',
    currencySymbol: '€',
    headline: 'AI Website Builder in France',
    subheadline: 'Les entreprises françaises de Paris à Lyon créent des sites web professionnels en 90 secondes — conforme RGPD, sans code.',
    metaDescription: 'Créez votre site web avec l\'IA en 90 secondes. Pour les entreprises françaises. Conforme RGPD. À partir de 18€/mois. Essai gratuit.',
    testimonial: {
      name: 'Sophie Laurent',
      company: 'Atelier Lumière',
      city: 'Paris',
      quote: 'Notre boutique en ligne a été créée en moins de 2 minutes. Le design est si élégant que nos clients pensent que nous avons engagé une agence parisienne.',
    },
    localKeywords: ['créateur de site web IA France', 'constructeur site web IA', 'AI website builder France', 'créer site web intelligence artificielle', 'site web professionnel IA'],
    pricing: { creator: 18, pro: 45, agency: 90 },
  },
  es: {
    code: 'es',
    name: 'Spain',
    languageCode: 'es-ES',
    currency: 'EUR',
    currencySymbol: '€',
    headline: 'AI Website Builder in Spain',
    subheadline: 'Empresas españolas de Madrid a Barcelona crean sitios web profesionales en 90 segundos — sin código, sin esperas, conforme al RGPD.',
    metaDescription: 'Crea tu sitio web con IA en 90 segundos. Para empresas españolas. Conforme RGPD. Desde 18€/mes. Sin programación. Prueba gratis.',
    testimonial: {
      name: 'Carlos Moreno',
      company: 'Sol Digital',
      city: 'Barcelona',
      quote: 'Creamos la web de nuestro restaurante durante la pausa del almuerzo. Las reservas online aumentaron un 150% en el primer mes.',
    },
    localKeywords: ['creador de sitios web IA España', 'constructor web IA', 'AI website builder Spain', 'crear página web inteligencia artificial', 'diseño web IA España'],
    pricing: { creator: 18, pro: 45, agency: 90 },
  },
  it: {
    code: 'it',
    name: 'Italy',
    languageCode: 'it-IT',
    currency: 'EUR',
    currencySymbol: '€',
    headline: 'AI Website Builder in Italy',
    subheadline: 'Aziende italiane da Milano a Roma creano siti web professionali in 90 secondi — senza codice, conforme GDPR, design made in Italy.',
    metaDescription: 'Crea il tuo sito web con l\'IA in 90 secondi. Per aziende italiane. Conforme GDPR. Da 18€/mese. Nessuna programmazione. Prova gratis.',
    testimonial: {
      name: 'Giulia Rossi',
      company: 'Bottega Digitale',
      city: 'Milan',
      quote: 'Il nostro e-commerce di moda è stato creato in 2 minuti. I clienti pensano che abbiamo speso migliaia di euro — in realtà è costato meno di un caffè al giorno.',
    },
    localKeywords: ['creatore siti web IA Italia', 'costruttore siti web IA', 'AI website builder Italy', 'creare sito web intelligenza artificiale', 'web design IA Italia'],
    pricing: { creator: 18, pro: 45, agency: 90 },
  },
  nl: {
    code: 'nl',
    name: 'Netherlands',
    languageCode: 'nl-NL',
    currency: 'EUR',
    currencySymbol: '€',
    headline: 'AI Website Builder in the Netherlands',
    subheadline: 'Nederlandse bedrijven van Amsterdam tot Rotterdam bouwen professionele websites in 90 seconden — AVG-conform, geen code nodig.',
    metaDescription: 'Bouw je website met AI in 90 seconden. Voor Nederlandse bedrijven. AVG-conform. Vanaf €18/maand. Geen programmeerkennis nodig. Gratis proberen.',
    testimonial: {
      name: 'Daan van der Berg',
      company: 'Gracht Studios',
      city: 'Amsterdam',
      quote: 'We bouwen nu 5 klantwebsites per dag in plaats van 5 per maand. Onze klanten in de Randstad zijn onder de indruk van de kwaliteit.',
    },
    localKeywords: ['AI website builder Nederland', 'website maken met AI', 'website bouwer AI Nederland', 'professionele website AI', 'webdesign AI Nederland'],
    pricing: { creator: 18, pro: 45, agency: 90 },
  },
  se: {
    code: 'se',
    name: 'Sweden',
    languageCode: 'sv-SE',
    currency: 'SEK',
    currencySymbol: 'kr',
    headline: 'AI Website Builder in Sweden',
    subheadline: 'Svenska företag från Stockholm till Göteborg bygger professionella webbplatser på 90 sekunder — ingen kod, ren skandinavisk design.',
    metaDescription: 'Bygg din webbplats med AI på 90 sekunder. För svenska företag. GDPR-kompatibel. Från 199 kr/mån. Ingen kod behövs. Testa gratis.',
    testimonial: {
      name: 'Erik Lindgren',
      company: 'Norrsken Digital',
      city: 'Stockholm',
      quote: 'Vi byggde hemsidan för vår startup under en fika-paus. Investerarna trodde vi hade anlitat en dyr designbyrå — det tog 90 sekunder.',
    },
    localKeywords: ['AI webbplatsbyggare Sverige', 'skapa hemsida med AI', 'AI website builder Sweden', 'webbdesign AI Sverige', 'hemsida AI byggare'],
    pricing: { creator: 199, pro: 499, agency: 999 },
  },
  br: {
    code: 'br',
    name: 'Brazil',
    languageCode: 'pt-BR',
    currency: 'BRL',
    currencySymbol: 'R$',
    headline: 'AI Website Builder in Brazil',
    subheadline: 'Empresas brasileiras de São Paulo ao Rio criam sites profissionais em 90 segundos — sem código, sem agência, sem espera.',
    metaDescription: 'Crie seu site com IA em 90 segundos. Para empresas brasileiras. Sem programação. A partir de R$95/mês. Teste grátis agora.',
    testimonial: {
      name: 'Rafael Oliveira',
      company: 'Praia Digital',
      city: 'São Paulo',
      quote: 'Criamos o site do nosso restaurante em 90 segundos. As reservas online triplicaram no primeiro mês — nossos clientes adoraram o design.',
    },
    localKeywords: ['criador de sites IA Brasil', 'construtor de sites IA', 'AI website builder Brazil', 'criar site inteligência artificial', 'web design IA Brasil'],
    pricing: { creator: 95, pro: 245, agency: 495 },
  },
  mx: {
    code: 'mx',
    name: 'Mexico',
    languageCode: 'es-MX',
    currency: 'MXN',
    currencySymbol: 'MX$',
    headline: 'AI Website Builder in Mexico',
    subheadline: 'Negocios mexicanos de CDMX a Guadalajara crean sitios web profesionales en 90 segundos — sin programadores, sin costos ocultos.',
    metaDescription: 'Crea tu sitio web con IA en 90 segundos. Para negocios mexicanos. Sin código. Desde MX$325/mes. Sin programación. Prueba gratis.',
    testimonial: {
      name: 'Ana García Hernández',
      company: 'Mercado Digital MX',
      city: 'Mexico City',
      quote: 'Creamos la tienda en línea de nuestra panadería en minutos. Las ventas en línea ya representan el 40% de nuestros ingresos mensuales.',
    },
    localKeywords: ['creador de sitios web IA México', 'constructor web IA México', 'AI website builder Mexico', 'crear página web IA México', 'diseño web IA México'],
    pricing: { creator: 325, pro: 845, agency: 1699 },
  },
  in: {
    code: 'in',
    name: 'India',
    languageCode: 'en-IN',
    currency: 'INR',
    currencySymbol: '₹',
    headline: 'AI Website Builder in India',
    subheadline: 'Indian businesses from Bangalore to Mumbai are building professional websites in 90 seconds — affordable, powerful, no coding needed.',
    metaDescription: 'AI website builder for Indian businesses. Build in 90 seconds. Plans from ₹1,599/mo. No coding needed. GST invoicing. Try free today.',
    testimonial: {
      name: 'Priya Sharma',
      company: 'Koramangala Tech',
      city: 'Bangalore',
      quote: 'We built websites for 15 local businesses in a single week. Each client thought we spent days on their site — it took 90 seconds each.',
    },
    localKeywords: ['AI website builder India', 'website builder Indian', 'build website AI India', 'no-code website builder India', 'web design AI India'],
    pricing: { creator: 1599, pro: 4099, agency: 8299 },
  },
  jp: {
    code: 'jp',
    name: 'Japan',
    languageCode: 'ja-JP',
    currency: 'JPY',
    currencySymbol: '¥',
    headline: 'AI Website Builder in Japan',
    subheadline: '東京から大阪まで、日本の企業が90秒でプロフェッショナルなWebサイトを構築 — コード不要、即時公開。',
    metaDescription: 'AIでWebサイトを90秒で構築。日本のビジネス向け。コード不要。月額¥2,850から。無料トライアル実施中。',
    testimonial: {
      name: 'Takeshi Yamamoto',
      company: 'Shibuya Digital',
      city: 'Tokyo',
      quote: '渋谷のカフェのWebサイトを90秒で作成しました。お客様からのオンライン予約が2倍に増え、売上が大幅に向上しました。',
    },
    localKeywords: ['AI ウェブサイトビルダー 日本', 'ホームページ作成 AI', 'AI website builder Japan', 'Webサイト作成 AI', 'ノーコード ウェブサイト 日本'],
    pricing: { creator: 2850, pro: 7350, agency: 14850 },
  },
  kr: {
    code: 'kr',
    name: 'South Korea',
    languageCode: 'ko-KR',
    currency: 'KRW',
    currencySymbol: '₩',
    headline: 'AI Website Builder in South Korea',
    subheadline: '서울에서 부산까지, 한국 기업들이 90초 만에 전문적인 웹사이트를 구축하고 있습니다 — 코딩 불필요, 즉시 배포.',
    metaDescription: 'AI로 90초 만에 웹사이트 구축. 한국 비즈니스용. 코딩 불필요. 월 ₩25,500부터. 무료 체험 가능.',
    testimonial: {
      name: 'Jisoo Park',
      company: 'Gangnam Digital',
      city: 'Seoul',
      quote: '강남 뷰티샵 웹사이트를 90초 만에 만들었습니다. 온라인 예약이 200% 증가했고, 고객들이 디자인을 극찬합니다.',
    },
    localKeywords: ['AI 웹사이트 빌더 한국', '홈페이지 제작 AI', 'AI website builder Korea', '웹사이트 만들기 AI', '노코드 웹사이트 한국'],
    pricing: { creator: 25500, pro: 65500, agency: 132500 },
  },
  sg: {
    code: 'sg',
    name: 'Singapore',
    languageCode: 'en-SG',
    currency: 'SGD',
    currencySymbol: 'S$',
    headline: 'AI Website Builder in Singapore',
    subheadline: 'Singapore businesses are building professional websites in 90 seconds — from Marina Bay startups to Orchard Road retail brands.',
    metaDescription: 'AI website builder for Singapore businesses. Build in 90 seconds. Plans from S$26/mo. No coding required. PDPA compliant. Try free.',
    testimonial: {
      name: 'Wei Lin Tan',
      company: 'Raffles Digital',
      city: 'Singapore',
      quote: 'We launched our hawker delivery platform in under 2 minutes. Orders doubled in the first week — our competitors still don\'t have a website.',
    },
    localKeywords: ['AI website builder Singapore', 'website builder Singapore', 'build website AI Singapore', 'no-code website builder Singapore', 'web design AI Singapore'],
    pricing: { creator: 26, pro: 66, agency: 133 },
  },
  ae: {
    code: 'ae',
    name: 'United Arab Emirates',
    languageCode: 'en-AE',
    currency: 'AED',
    currencySymbol: 'AED',
    headline: 'AI Website Builder in the UAE',
    subheadline: 'UAE businesses from Dubai to Abu Dhabi are building premium websites in 90 seconds — perfect for the region\'s fast-paced digital economy.',
    metaDescription: 'AI website builder for UAE businesses. Build in 90 seconds. Plans from AED 70/mo. No coding needed. Arabic-ready. Try free today.',
    testimonial: {
      name: 'Omar Al-Rashid',
      company: 'Palm Digital',
      city: 'Dubai',
      quote: 'We built our luxury real estate portfolio site during a meeting break. Clients in Dubai Marina were impressed — it looks like a premium agency built it.',
    },
    localKeywords: ['AI website builder UAE', 'website builder Dubai', 'build website AI UAE', 'no-code website builder UAE', 'web design AI Dubai Abu Dhabi'],
    pricing: { creator: 70, pro: 180, agency: 365 },
  },
  za: {
    code: 'za',
    name: 'South Africa',
    languageCode: 'en-ZA',
    currency: 'ZAR',
    currencySymbol: 'R',
    headline: 'AI Website Builder in South Africa',
    subheadline: 'South African businesses from Johannesburg to Cape Town are building professional websites in 90 seconds — affordable, fast, no coding.',
    metaDescription: 'AI website builder for South African businesses. Build in 90 seconds. Plans from R345/mo. No coding needed. Load-shedding proof. Try free.',
    testimonial: {
      name: 'Thandi Nkosi',
      company: 'Table Mountain Digital',
      city: 'Cape Town',
      quote: 'We built our township tour booking site in 90 seconds. International bookings increased 4x — tourists love being able to book directly online.',
    },
    localKeywords: ['AI website builder South Africa', 'website builder SA', 'build website AI South Africa', 'no-code website builder South Africa', 'web design AI Johannesburg Cape Town'],
    pricing: { creator: 345, pro: 895, agency: 1799 },
  },
  nz: {
    code: 'nz',
    name: 'New Zealand',
    languageCode: 'en-NZ',
    currency: 'NZD',
    currencySymbol: 'NZ$',
    headline: 'AI Website Builder in New Zealand',
    subheadline: 'Kiwi businesses from Auckland to Wellington are building professional websites in 90 seconds — no agencies, no delays, just results.',
    metaDescription: 'AI website builder for NZ businesses. Build in 90 seconds. Plans from NZ$32/mo. No coding needed. Fast, beautiful, affordable. Try free.',
    testimonial: {
      name: 'Jack Thompson',
      company: 'Queenstown Digital',
      city: 'Auckland',
      quote: 'Built our adventure tourism site between meetings. Bookings from international visitors jumped 85% in the first month — the site sells itself.',
    },
    localKeywords: ['AI website builder New Zealand', 'website builder NZ', 'build website AI New Zealand', 'no-code website builder NZ', 'web design AI Auckland Wellington'],
    pricing: { creator: 32, pro: 82, agency: 165 },
  },
  ie: {
    code: 'ie',
    name: 'Ireland',
    languageCode: 'en-IE',
    currency: 'EUR',
    currencySymbol: '€',
    headline: 'AI Website Builder in Ireland',
    subheadline: 'Irish businesses from Dublin to Cork are building professional websites in 90 seconds — GDPR compliant, no coding, instant deployment.',
    metaDescription: 'AI website builder for Irish businesses. Build in 90 seconds. GDPR compliant. Plans from €18/mo. No coding needed. Try free today.',
    testimonial: {
      name: 'Aoife Murphy',
      company: 'Temple Bar Digital',
      city: 'Dublin',
      quote: 'We built our pub\'s website and online booking system in 90 seconds flat. Weekend reservations are up 60% — and it was free to try.',
    },
    localKeywords: ['AI website builder Ireland', 'website builder Irish', 'build website AI Ireland', 'no-code website builder Ireland', 'web design AI Dublin Cork'],
    pricing: { creator: 18, pro: 45, agency: 90 },
  },
};

export function getCountryData(code: string): CountryData | null {
  if (!VALID_COUNTRY_CODES.has(code)) return null;
  return COUNTRY_DATA[code] || null;
}

export function getAllCountryCodes(): string[] {
  return Array.from(VALID_COUNTRY_CODES);
}
