/**
 * GitHub Sync for Generated Projects
 *
 * Every generated site can be synced to a GitHub repository.
 * Changes auto-commit so developers can take over at any point.
 *
 * Flow:
 *   1. User generates a site
 *   2. Clicks "Push to GitHub" (or auto-sync enabled)
 *   3. Creates repo if needed, commits all files
 *   4. Future edits auto-commit with descriptive messages
 *
 * This is what Lovable and Bolt both do. Table stakes in 2026.
 */

const GITHUB_API = "https://api.github.com";

interface GitHubSyncResult {
  repoUrl: string;
  commitSha: string;
  filesCommitted: number;
}

/**
 * Create a GitHub repository and push all project files.
 */
export async function pushToGitHub(params: {
  files: Record<string, string>;
  repoName: string;
  commitMessage: string;
  token: string; // User's GitHub token (from OAuth or manual entry)
  isPrivate?: boolean;
}): Promise<GitHubSyncResult> {
  const { files, repoName, commitMessage, token, isPrivate = true } = params;

  const headers = {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };

  // Get authenticated user
  const userRes = await fetch(`${GITHUB_API}/user`, { headers });
  if (!userRes.ok) throw new Error("Invalid GitHub token");
  const user = await userRes.json();
  const owner = user.login;

  // Create repo if it doesn't exist
  let repoExists = false;
  const checkRes = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}`, { headers });
  if (checkRes.ok) {
    repoExists = true;
  } else {
    const createRes = await fetch(`${GITHUB_API}/user/repos`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        name: repoName,
        private: isPrivate,
        auto_init: true,
        description: `Generated by Zoobicon AI Builder — zoobicon.com`,
      }),
    });
    if (!createRes.ok) {
      const err = await createRes.json();
      throw new Error(err.message || "Failed to create repository");
    }
    // Wait a moment for repo initialization
    await new Promise(r => setTimeout(r, 2000));
  }

  // Get the current tree SHA (needed for creating a new tree)
  const refRes = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}/git/refs/heads/main`, { headers });
  let baseTreeSha = "";
  let parentSha = "";

  if (refRes.ok) {
    const refData = await refRes.json();
    parentSha = refData.object.sha;

    const commitRes = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}/git/commits/${parentSha}`, { headers });
    if (commitRes.ok) {
      const commitData = await commitRes.json();
      baseTreeSha = commitData.tree.sha;
    }
  }

  // Create blobs for each file
  const treeItems: Array<{ path: string; mode: string; type: string; sha: string }> = [];

  for (const [filePath, content] of Object.entries(files)) {
    const blobRes = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}/git/blobs`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        content,
        encoding: "utf-8",
      }),
    });

    if (!blobRes.ok) continue;
    const blob = await blobRes.json();

    treeItems.push({
      path: filePath.startsWith("/") ? filePath.slice(1) : filePath,
      mode: "100644",
      type: "blob",
      sha: blob.sha,
    });
  }

  // Create tree
  const treeBody: Record<string, unknown> = { tree: treeItems };
  if (baseTreeSha) treeBody.base_tree = baseTreeSha;

  const treeRes = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}/git/trees`, {
    method: "POST",
    headers,
    body: JSON.stringify(treeBody),
  });

  if (!treeRes.ok) throw new Error("Failed to create file tree");
  const tree = await treeRes.json();

  // Create commit
  const commitBody: Record<string, unknown> = {
    message: commitMessage,
    tree: tree.sha,
  };
  if (parentSha) commitBody.parents = [parentSha];

  const newCommitRes = await fetch(`${GITHUB_API}/repos/${owner}/${repoName}/git/commits`, {
    method: "POST",
    headers,
    body: JSON.stringify(commitBody),
  });

  if (!newCommitRes.ok) throw new Error("Failed to create commit");
  const newCommit = await newCommitRes.json();

  // Update ref to point to new commit
  const updateRef = parentSha ? "PATCH" : "POST";
  const refPath = parentSha
    ? `${GITHUB_API}/repos/${owner}/${repoName}/git/refs/heads/main`
    : `${GITHUB_API}/repos/${owner}/${repoName}/git/refs`;

  const refBody = parentSha
    ? { sha: newCommit.sha }
    : { ref: "refs/heads/main", sha: newCommit.sha };

  await fetch(refPath, {
    method: updateRef,
    headers,
    body: JSON.stringify(refBody),
  });

  return {
    repoUrl: `https://github.com/${owner}/${repoName}`,
    commitSha: newCommit.sha,
    filesCommitted: treeItems.length,
  };
}

/**
 * Sync changes to an existing GitHub repository.
 * Used for incremental updates after edits.
 */
export async function syncChanges(params: {
  changedFiles: Record<string, string>;
  repoOwner: string;
  repoName: string;
  commitMessage: string;
  token: string;
}): Promise<GitHubSyncResult> {
  return pushToGitHub({
    files: params.changedFiles,
    repoName: params.repoName,
    commitMessage: params.commitMessage,
    token: params.token,
  });
}
