/**
 * GitHub Sync for Generated Projects
 *
 * Every generated site can be synced to a GitHub repository.
 * Changes auto-commit so developers can take over at any point.
 *
 * Flow:
 *   1. User generates a site
 *   2. Clicks "Push to GitHub" (or auto-sync enabled)
 *   3. Creates repo if needed, commits all files
 *   4. Future edits auto-commit with descriptive messages
 *
 * Uses the GitHub REST API with user's personal access token (from OAuth).
 * This is what Lovable and Bolt both do. Table stakes in 2026.
 */

const GITHUB_API = "https://api.github.com";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface GitHubSyncResult {
  repoUrl: string;
  commitSha: string;
  filesCommitted: number;
  isNewRepo: boolean;
}

export interface GitHubRepoStatus {
  exists: boolean;
  repoUrl: string;
  defaultBranch: string;
  lastCommitSha: string;
  lastCommitMessage: string;
  lastCommitDate: string;
  totalCommits: number;
  isPrivate: boolean;
}

export interface GitHubUser {
  login: string;
  avatarUrl: string;
  name: string;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function makeHeaders(token: string): Record<string, string> {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

async function ghFetch(
  path: string,
  token: string,
  options?: RequestInit
): Promise<Response> {
  const url = path.startsWith("http") ? path : `${GITHUB_API}${path}`;
  return fetch(url, {
    ...options,
    headers: {
      ...makeHeaders(token),
      ...(options?.headers || {}),
    },
  });
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Get the authenticated GitHub user.
 */
export async function getGitHubUser(token: string): Promise<GitHubUser> {
  const res = await ghFetch("/user", token);
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.message || "Invalid GitHub token");
  }
  const data = await res.json();
  return {
    login: data.login,
    avatarUrl: data.avatar_url,
    name: data.name || data.login,
  };
}

/**
 * Check if a repository exists and get its status.
 */
export async function getRepoStatus(params: {
  owner: string;
  repoName: string;
  token: string;
}): Promise<GitHubRepoStatus | null> {
  const { owner, repoName, token } = params;

  const repoRes = await ghFetch(`/repos/${owner}/${repoName}`, token);
  if (!repoRes.ok) return null;

  const repo = await repoRes.json();
  const defaultBranch = repo.default_branch || "main";

  // Get latest commit info
  let lastCommitSha = "";
  let lastCommitMessage = "";
  let lastCommitDate = "";
  let totalCommits = 0;

  const commitsRes = await ghFetch(
    `/repos/${owner}/${repoName}/commits?sha=${defaultBranch}&per_page=1`,
    token
  );
  if (commitsRes.ok) {
    const commits = await commitsRes.json();
    if (commits.length > 0) {
      lastCommitSha = commits[0].sha;
      lastCommitMessage = commits[0].commit.message;
      lastCommitDate = commits[0].commit.committer.date;
    }
    // GitHub returns total count in Link header (approximate)
    const linkHeader = commitsRes.headers.get("link");
    if (linkHeader) {
      const lastPageMatch = linkHeader.match(/page=(\d+)>; rel="last"/);
      totalCommits = lastPageMatch ? parseInt(lastPageMatch[1], 10) : 1;
    } else {
      totalCommits = commits.length;
    }
  }

  return {
    exists: true,
    repoUrl: repo.html_url,
    defaultBranch,
    lastCommitSha,
    lastCommitMessage,
    lastCommitDate,
    totalCommits,
    isPrivate: repo.private,
  };
}

/**
 * Create a GitHub repository and push all project files as an initial commit.
 */
export async function createRepoAndPush(params: {
  files: Record<string, string>;
  repoName: string;
  commitMessage?: string;
  token: string;
  isPrivate?: boolean;
  description?: string;
}): Promise<GitHubSyncResult> {
  const {
    files,
    repoName,
    commitMessage = "Initial commit — generated by Zoobicon",
    token,
    isPrivate = true,
    description = "Generated by Zoobicon AI Builder — zoobicon.com",
  } = params;

  // Get authenticated user
  const user = await getGitHubUser(token);
  const owner = user.login;

  // Check if repo already exists
  const existing = await getRepoStatus({ owner, repoName, token });
  if (existing) {
    // Repo exists — push as a new commit instead
    return pushToExistingRepo({
      files,
      owner,
      repoName,
      commitMessage,
      token,
      branch: existing.defaultBranch,
    });
  }

  // Create repository (auto_init: true gives us a default branch with README)
  const createRes = await ghFetch("/user/repos", token, {
    method: "POST",
    body: JSON.stringify({
      name: repoName,
      private: isPrivate,
      auto_init: true,
      description,
    }),
  });

  if (!createRes.ok) {
    const err = await createRes.json().catch(() => ({}));
    throw new Error(err.message || "Failed to create repository");
  }

  // Wait for GitHub to finish initializing the repo
  await waitForRepoReady(owner, repoName, token);

  // Push all files
  const result = await pushToExistingRepo({
    files,
    owner,
    repoName,
    commitMessage,
    token,
    branch: "main",
  });

  return { ...result, isNewRepo: true };
}

/**
 * Push files to an existing repository as a new commit.
 * This creates proper git tree objects — NOT the contents API (which is one-file-at-a-time).
 */
export async function pushToExistingRepo(params: {
  files: Record<string, string>;
  owner: string;
  repoName: string;
  commitMessage: string;
  token: string;
  branch?: string;
}): Promise<GitHubSyncResult> {
  const {
    files,
    owner,
    repoName,
    commitMessage,
    token,
    branch = "main",
  } = params;

  // 1. Get the current ref (latest commit on branch)
  const refRes = await ghFetch(
    `/repos/${owner}/${repoName}/git/refs/heads/${branch}`,
    token
  );

  if (!refRes.ok) {
    throw new Error(
      `Branch "${branch}" not found on ${owner}/${repoName}. ` +
        "Make sure the repository is initialized."
    );
  }

  const refData = await refRes.json();
  const parentSha = refData.object.sha;

  // 2. Get the tree SHA from the parent commit
  const commitRes = await ghFetch(
    `/repos/${owner}/${repoName}/git/commits/${parentSha}`,
    token
  );
  if (!commitRes.ok) throw new Error("Failed to read latest commit");
  const commitData = await commitRes.json();
  const baseTreeSha = commitData.tree.sha;

  // 3. Create blobs for each file (parallel for speed)
  const blobPromises = Object.entries(files).map(
    async ([filePath, content]) => {
      const blobRes = await ghFetch(
        `/repos/${owner}/${repoName}/git/blobs`,
        token,
        {
          method: "POST",
          body: JSON.stringify({
            content,
            encoding: "utf-8",
          }),
        }
      );

      if (!blobRes.ok) {
        console.error(`Failed to create blob for ${filePath}`);
        return null;
      }

      const blob = await blobRes.json();
      return {
        path: filePath.startsWith("/") ? filePath.slice(1) : filePath,
        mode: "100644" as const,
        type: "blob" as const,
        sha: blob.sha as string,
      };
    }
  );

  const treeItems = (await Promise.all(blobPromises)).filter(
    (item): item is NonNullable<typeof item> => item !== null
  );

  if (treeItems.length === 0) {
    throw new Error("No files could be uploaded");
  }

  // 4. Create new tree (based on existing tree so existing files are preserved)
  const treeRes = await ghFetch(
    `/repos/${owner}/${repoName}/git/trees`,
    token,
    {
      method: "POST",
      body: JSON.stringify({
        base_tree: baseTreeSha,
        tree: treeItems,
      }),
    }
  );

  if (!treeRes.ok) throw new Error("Failed to create file tree");
  const tree = await treeRes.json();

  // 5. Create commit
  const newCommitRes = await ghFetch(
    `/repos/${owner}/${repoName}/git/commits`,
    token,
    {
      method: "POST",
      body: JSON.stringify({
        message: commitMessage,
        tree: tree.sha,
        parents: [parentSha],
      }),
    }
  );

  if (!newCommitRes.ok) throw new Error("Failed to create commit");
  const newCommit = await newCommitRes.json();

  // 6. Update the branch ref to point to the new commit
  const updateRefRes = await ghFetch(
    `/repos/${owner}/${repoName}/git/refs/heads/${branch}`,
    token,
    {
      method: "PATCH",
      body: JSON.stringify({ sha: newCommit.sha }),
    }
  );

  if (!updateRefRes.ok) throw new Error("Failed to update branch");

  return {
    repoUrl: `https://github.com/${owner}/${repoName}`,
    commitSha: newCommit.sha,
    filesCommitted: treeItems.length,
    isNewRepo: false,
  };
}

/**
 * Convenience: push changed files to an existing synced repo.
 * Same as pushToExistingRepo but resolves owner from token.
 */
export async function syncChanges(params: {
  changedFiles: Record<string, string>;
  repoName: string;
  commitMessage: string;
  token: string;
  branch?: string;
}): Promise<GitHubSyncResult> {
  const user = await getGitHubUser(params.token);
  return pushToExistingRepo({
    files: params.changedFiles,
    owner: user.login,
    repoName: params.repoName,
    commitMessage: params.commitMessage,
    token: params.token,
    branch: params.branch,
  });
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Poll until the newly created repo is ready (has a default branch).
 * GitHub can take 1-3 seconds to initialize after creation.
 */
async function waitForRepoReady(
  owner: string,
  repoName: string,
  token: string,
  maxAttempts = 10
): Promise<void> {
  for (let i = 0; i < maxAttempts; i++) {
    const res = await ghFetch(
      `/repos/${owner}/${repoName}/git/refs/heads/main`,
      token
    );
    if (res.ok) return;
    await new Promise((r) => setTimeout(r, 1000));
  }
  throw new Error("Repository initialization timed out. Please try again.");
}
