export interface Template {
  id: string;
  name: string;
  category: string;
  description: string;
  prompt: string;
  thumbnail: string; // CSS gradient as placeholder
  tags: string[];
}

export const TEMPLATES: Template[] = [
  {
    id: "saas-landing",
    name: "SaaS Landing Page",
    category: "Business",
    description: "Modern SaaS product page with hero, features, pricing, and CTA sections.",
    prompt: "A modern SaaS landing page with a bold hero section featuring a gradient background, feature cards with icons, a pricing table with 3 tiers, testimonials section, and a strong call-to-action footer. Use a professional color scheme with blues and purples.",
    thumbnail: "from-blue-600 to-blue-600",
    tags: ["SaaS", "Startup", "Landing"],
  },
  {
    id: "portfolio-creative",
    name: "Creative Portfolio",
    category: "Portfolio",
    description: "Stunning portfolio with masonry gallery, about section, and contact form.",
    prompt: "A creative portfolio website with a full-screen hero with the photographer's name in massive typography, a masonry-style image gallery grid, an about section with a split layout, a services section, and a contact form. Dark theme with accent colors.",
    thumbnail: "from-rose-600 to-orange-500",
    tags: ["Portfolio", "Creative", "Gallery"],
  },
  {
    id: "ecommerce-store",
    name: "E-Commerce Store",
    category: "E-Commerce",
    description: "Product showcase with grid layout, cart UI, and promotional banners.",
    prompt: "An e-commerce storefront with a hero banner slider area, product grid with cards showing images, prices and add-to-cart buttons, category navigation, a featured products section, and a newsletter signup footer. Clean modern design with a white and green color scheme.",
    thumbnail: "from-emerald-600 to-teal-500",
    tags: ["Shop", "Products", "Store"],
  },
  {
    id: "restaurant-menu",
    name: "Restaurant & Menu",
    category: "Food & Drink",
    description: "Elegant restaurant site with menu, gallery, and reservation section.",
    prompt: "An elegant restaurant website with a hero section showing a background image placeholder, a menu section organized by categories (starters, mains, desserts) with prices, a photo gallery, about the chef section, opening hours, and a reservation form. Warm earth tones with gold accents.",
    thumbnail: "from-amber-700 to-red-800",
    tags: ["Restaurant", "Menu", "Food"],
  },
  {
    id: "agency-dark",
    name: "Digital Agency",
    category: "Business",
    description: "Bold agency site with case studies, team section, and services grid.",
    prompt: "A bold digital agency website with a dark background, oversized typography hero, a services grid with hover effects, case study cards, team member profiles, client logos, and a contact section. Use a dark theme with neon green accents.",
    thumbnail: "from-gray-900 to-green-900",
    tags: ["Agency", "Dark", "Corporate"],
  },
  {
    id: "blog-minimal",
    name: "Minimal Blog",
    category: "Blog",
    description: "Clean blog layout with featured post, article grid, and sidebar.",
    prompt: "A minimalist blog with a clean header and navigation, a featured post hero with large typography, an article grid with cards showing titles, excerpts, dates, and read time, a sidebar with categories and popular posts, and a simple footer. Use a warm off-white background with serif fonts.",
    thumbnail: "from-stone-400 to-stone-600",
    tags: ["Blog", "Minimal", "Content"],
  },
  {
    id: "fitness-gym",
    name: "Fitness & Gym",
    category: "Health",
    description: "High-energy gym site with class schedule, trainers, and membership plans.",
    prompt: "A high-energy fitness gym website with a powerful hero section with bold text, class schedule in a timetable format, trainer profile cards, membership pricing plans, a photo gallery, and a free trial sign-up form. Use dark backgrounds with red and orange accents. Bold, aggressive typography.",
    thumbnail: "from-red-700 to-orange-600",
    tags: ["Fitness", "Gym", "Health"],
  },
  {
    id: "tech-startup",
    name: "AI/Tech Startup",
    category: "Technology",
    description: "Futuristic tech page with animated elements, feature grid, and demo CTA.",
    prompt: "A futuristic AI tech startup landing page with a hero section featuring animated gradient backgrounds, floating UI elements, a feature comparison grid, integration logos, a live demo CTA section, and an enterprise contact form. Dark theme with electric blue and purple gradients. Ultra-modern design.",
    thumbnail: "from-indigo-600 to-cyan-500",
    tags: ["Tech", "AI", "Startup"],
  },
  {
    id: "event-conference",
    name: "Event & Conference",
    category: "Events",
    description: "Conference page with speaker lineup, schedule, and ticket registration.",
    prompt: "A tech conference landing page with a countdown timer hero, speaker lineup cards with photos and bios, a multi-track schedule/agenda, sponsor logos, venue information, and a ticket purchase section with different tiers. Modern and professional with a blue color scheme.",
    thumbnail: "from-blue-600 to-blue-600",
    tags: ["Event", "Conference", "Tickets"],
  },
  {
    id: "real-estate",
    name: "Luxury Real Estate",
    category: "Real Estate",
    description: "Premium real estate with hero carousel, property cards, agent profiles, and neighborhood showcase.",
    prompt: "A premium luxury real estate website. HERO: Full-viewport hero carousel (.hero-carousel) showing 3-5 stunning property photos (use picsum images: seed/luxury-house/1400/800, seed/modern-villa/1400/800, seed/penthouse-view/1400/800, seed/pool-villa/1400/800, seed/estate-garden/1400/800). White overlay headline text (.overlay-text) with elegant serif font. PROPERTIES: A featured listings section with .property-grid showing 6 property cards (.property-card) — each with large image (.property-card-img), status badge (.status-badge .status-for-sale), price (.property-card-price), and beds/baths/sqft using .feature-badge in .property-card-meta. AGENTS: Agent profile section with 3 agents, professional photos, contact info, bio. NEIGHBORHOODS: Full-width neighborhood showcase with large images and descriptions of 4 areas. TESTIMONIALS: Client success stories with specific sale amounts and timeframes. STATS: Properties sold (2,847), years in business (18), average sale price ($2.4M), client satisfaction (98%). CTA: Schedule a private viewing form. DESIGN: Navy (#1a365d) and gold (#c9a96e) palette, Playfair Display serif headings, full-bleed imagery throughout. This must look like a $50,000 agency site — cinematic, aspirational, visually stunning. NO sparse white pages.",
    thumbnail: "from-blue-900 to-yellow-700",
    tags: ["Real Estate", "Luxury", "Property", "Listings"],
  },
  {
    id: "music-artist",
    name: "Music Artist",
    category: "Entertainment",
    description: "Artist page with album showcase, tour dates, and merch store.",
    prompt: "A music artist/band website with a full-screen hero with artist name, a latest album showcase section, a tour dates list with venue and ticket links, a music player UI element, a merch store section, and social media links. Dark and moody with neon accent colors.",
    thumbnail: "from-blue-900 to-pink-600",
    tags: ["Music", "Artist", "Entertainment"],
  },
  {
    id: "nonprofit-charity",
    name: "Nonprofit & Charity",
    category: "Nonprofit",
    description: "Charity site with impact stats, donation section, and volunteer signup.",
    prompt: "A nonprofit charity website with an emotional hero section, impact statistics with large numbers, a programs/initiatives section, a donation form with suggested amounts, volunteer sign-up, latest news/blog section, and partner logos. Warm, hopeful colors with greens and earth tones.",
    thumbnail: "from-green-700 to-emerald-500",
    tags: ["Nonprofit", "Charity", "Donation"],
  },
  {
    id: "law-firm",
    name: "Law Firm",
    category: "Business",
    description: "Authoritative legal practice site with practice areas, attorney profiles, and case results.",
    prompt: "A prestigious law firm website with a sophisticated hero section featuring a cityscape background image (.hero-image) and white overlay text. Practice areas in an elegant grid. Attorney profiles with professional photos, credentials, and bar admissions. Case results with specific settlements/verdicts ($4.2M recovery, 98% success rate). Client testimonials from corporate clients. FAQ addressing common legal concerns. Contact form for free consultation. Dark navy (#0f172a) and warm gold (#b8860b) color scheme, serif headings (Merriweather), light background. Conservative but premium — conveys authority and trust.",
    thumbnail: "from-slate-800 to-amber-700",
    tags: ["Law", "Legal", "Attorney", "Professional"],
  },
  {
    id: "dental-clinic",
    name: "Dental & Medical Clinic",
    category: "Health",
    description: "Clean medical practice site with services, doctor profiles, and appointment booking.",
    prompt: "A modern dental/medical clinic website with a calming hero section featuring a clean interior photo (.hero-image), services grid with icons (cleanings, implants, cosmetic, emergency), doctor profiles with qualifications and specialties, patient testimonials with before/after stories, insurance accepted badges, office tour photo gallery (.image-gallery), and an appointment booking form. Soft teal (#0d9488) and white palette, clean sans-serif fonts (Inter), lots of whitespace. Conveys cleanliness, professionalism, and patient comfort.",
    thumbnail: "from-teal-500 to-cyan-400",
    tags: ["Medical", "Dental", "Health", "Clinic"],
  },
  {
    id: "wedding-planner",
    name: "Wedding & Events",
    category: "Events",
    description: "Elegant wedding planner site with gallery, packages, and inquiry form.",
    prompt: "An elegant wedding planner website with a romantic hero section featuring a full-bleed floral/venue photo (.hero-image) with delicate overlay text. Portfolio gallery (.image-gallery) of past weddings. Service packages (Intimate, Classic, Grand) with pricing. Vendor partners section. Client love stories (testimonials with wedding date and venue). Planning timeline/process steps. Inquiry form for consultations. Soft blush (#fce7f3), sage green (#86efac), and cream palette. Elegant serif headings (Cormorant Garamond). Romantic, aspirational, feminine sophistication.",
    thumbnail: "from-pink-300 to-rose-400",
    tags: ["Wedding", "Events", "Planner", "Elegant"],
  },
  {
    id: "saas-dashboard",
    name: "SaaS Analytics Platform",
    category: "Technology",
    description: "Data-driven SaaS page with dashboard preview, integrations, and enterprise features.",
    prompt: "A data analytics SaaS platform landing page with a hero featuring an animated gradient background (.hero-aurora) and a dashboard screenshot mockup. Key metrics bar (10M+ data points, 500+ integrations, 99.9% uptime). Feature grid showing analytics capabilities with chart icons. Integration logos (Slack, Salesforce, HubSpot, etc.). Pricing with Free/Pro/Enterprise tiers. Enterprise security features (SOC 2, GDPR, SSO). Customer success stories from Fortune 500 companies. Dark theme (#0a0a1a) with electric blue (#3b82f6) and violet (#8b5cf6) accents. Ultra-modern, technical, data-forward.",
    thumbnail: "from-violet-700 to-blue-600",
    tags: ["SaaS", "Analytics", "Dashboard", "Enterprise"],
  },
  {
    id: "construction-company",
    name: "Construction & Contractor",
    category: "Business",
    description: "Rugged construction company site with project gallery, services, and quote request.",
    prompt: "A professional construction company website with a powerful hero featuring a large construction site photo (.hero-image) and bold overlay text. Services grid (residential, commercial, renovation, design-build) with project photos. Completed projects gallery (.image-gallery) with before/after shots. Safety certifications and insurance badges. Team section with experienced crew. Stats (500+ projects, 25 years, 100% licensed & insured). Client testimonials from property developers. Free quote request form. Strong, masculine colors — charcoal (#1e293b), construction orange (#ea580c), concrete gray. Bold sans-serif headings (Oswald).",
    thumbnail: "from-gray-800 to-orange-600",
    tags: ["Construction", "Contractor", "Building", "Services"],
  },
  {
    id: "yoga-wellness",
    name: "Yoga & Wellness Studio",
    category: "Health",
    description: "Serene wellness studio site with class schedule, instructor profiles, and membership.",
    prompt: "A serene yoga and wellness studio website with a peaceful hero section featuring a meditation/yoga photo (.hero-image) with soft overlay text. Class schedule displayed in a clean weekly timetable. Instructor profiles with bios and specialties. Membership plans (Drop-in, Monthly, Annual) with pricing. Wellness blog highlights. Studio photo gallery (.image-gallery). Testimonials about transformation journeys. First class free CTA. Soft sage (#86efac), lavender (#c4b5fd), and warm cream palette. Elegant flowing fonts (Cormorant Garamond for headings, Lato for body). Calm, mindful, welcoming.",
    thumbnail: "from-green-300 to-purple-300",
    tags: ["Yoga", "Wellness", "Studio", "Health"],
  },
  {
    id: "automotive-dealer",
    name: "Auto Dealership",
    category: "Business",
    description: "Sleek car dealership site with vehicle inventory, financing, and trade-in form.",
    prompt: "A sleek automotive dealership website with a cinematic hero carousel (.hero-carousel) showing 3-4 luxury vehicles (use seed/luxury-car, seed/sports-car, seed/suv-vehicle, seed/sedan-car). Vehicle inventory grid with cards showing make/model, year, price, mileage. Featured vehicles section with large photos. Financing calculator section. Trade-in value form. Service department section. Dealer stats (2,500+ cars sold, 15 years, 4.8 star rating). Customer reviews. Contact with dealership hours and map placeholder. Dark metallic (#0f172a) with racing red (#dc2626) and chrome silver accents. Bold, premium, automotive feel.",
    thumbnail: "from-slate-900 to-red-700",
    tags: ["Auto", "Cars", "Dealership", "Vehicles"],
  },
  {
    id: "coffee-shop",
    name: "Coffee Shop & Cafe",
    category: "Food & Drink",
    description: "Cozy cafe site with menu, locations, loyalty program, and online ordering.",
    prompt: "A warm, inviting coffee shop website with a full-bleed hero photo (.hero-image) of a beautifully crafted latte with soft overlay text. Menu section organized by category (espresso drinks, pour-overs, pastries, breakfast) with prices. Locations section with addresses and hours for 3 shops. Our Story section about coffee sourcing and roasting process. Loyalty program signup. Instagram-style photo gallery (.image-gallery) of drinks and interior. Testimonials from regulars. Online order CTA. Warm mocha (#78350f), cream (#fef3c7), and espresso brown palette. Cozy serif headings (Playfair Display). Artisanal, warm, community-focused.",
    thumbnail: "from-amber-800 to-yellow-600",
    tags: ["Coffee", "Cafe", "Food", "Drinks"],
  },
];

export const TEMPLATE_CATEGORIES = [
  "All",
  "Business",
  "Portfolio",
  "E-Commerce",
  "Blog",
  "Technology",
  "Food & Drink",
  "Health",
  "Events",
  "Real Estate",
  "Entertainment",
  "Nonprofit",
  "Professional",
];
