export interface Template {
  id: string;
  name: string;
  category: string;
  description: string;
  prompt: string;
  thumbnail: string; // CSS gradient as placeholder
  tags: string[];
}

export const TEMPLATES: Template[] = [
  {
    id: "saas-landing",
    name: "SaaS Landing Page",
    category: "Business",
    description: "Modern SaaS product page with hero, features, pricing, and CTA sections.",
    prompt: "A modern SaaS landing page with a bold hero section featuring a gradient background, feature cards with icons, a pricing table with 3 tiers, testimonials section, and a strong call-to-action footer. Use a professional color scheme with blues and purples.",
    thumbnail: "from-blue-600 to-blue-600",
    tags: ["SaaS", "Startup", "Landing"],
  },
  {
    id: "portfolio-creative",
    name: "Creative Portfolio",
    category: "Portfolio",
    description: "Stunning portfolio with masonry gallery, about section, and contact form.",
    prompt: "A creative portfolio website with a full-screen hero with the photographer's name in massive typography, a masonry-style image gallery grid, an about section with a split layout, a services section, and a contact form. Dark theme with accent colors.",
    thumbnail: "from-rose-600 to-orange-500",
    tags: ["Portfolio", "Creative", "Gallery"],
  },
  {
    id: "ecommerce-store",
    name: "E-Commerce Store",
    category: "E-Commerce",
    description: "Product showcase with grid layout, cart UI, and promotional banners.",
    prompt: "An e-commerce storefront with a hero banner slider area, product grid with cards showing images, prices and add-to-cart buttons, category navigation, a featured products section, and a newsletter signup footer. Clean modern design with a white and green color scheme.",
    thumbnail: "from-emerald-600 to-teal-500",
    tags: ["Shop", "Products", "Store"],
  },
  {
    id: "restaurant-menu",
    name: "Restaurant & Menu",
    category: "Food & Drink",
    description: "Elegant restaurant site with menu, gallery, and reservation section.",
    prompt: "An elegant restaurant website with a hero section showing a background image placeholder, a menu section organized by categories (starters, mains, desserts) with prices, a photo gallery, about the chef section, opening hours, and a reservation form. Warm earth tones with gold accents.",
    thumbnail: "from-amber-700 to-red-800",
    tags: ["Restaurant", "Menu", "Food"],
  },
  {
    id: "agency-dark",
    name: "Digital Agency",
    category: "Business",
    description: "Bold agency site with case studies, team section, and services grid.",
    prompt: "A bold digital agency website with a dark background, oversized typography hero, a services grid with hover effects, case study cards, team member profiles, client logos, and a contact section. Use a dark theme with neon green accents.",
    thumbnail: "from-gray-900 to-green-900",
    tags: ["Agency", "Dark", "Corporate"],
  },
  {
    id: "blog-minimal",
    name: "Minimal Blog",
    category: "Blog",
    description: "Clean blog layout with featured post, article grid, and sidebar.",
    prompt: "A minimalist blog with a clean header and navigation, a featured post hero with large typography, an article grid with cards showing titles, excerpts, dates, and read time, a sidebar with categories and popular posts, and a simple footer. Use a warm off-white background with serif fonts.",
    thumbnail: "from-stone-400 to-stone-600",
    tags: ["Blog", "Minimal", "Content"],
  },
  {
    id: "fitness-gym",
    name: "Fitness & Gym",
    category: "Health",
    description: "High-energy gym site with class schedule, trainers, and membership plans.",
    prompt: "A high-energy fitness gym website with a powerful hero section with bold text, class schedule in a timetable format, trainer profile cards, membership pricing plans, a photo gallery, and a free trial sign-up form. Use dark backgrounds with red and orange accents. Bold, aggressive typography.",
    thumbnail: "from-red-700 to-orange-600",
    tags: ["Fitness", "Gym", "Health"],
  },
  {
    id: "tech-startup",
    name: "AI/Tech Startup",
    category: "Technology",
    description: "Futuristic tech page with animated elements, feature grid, and demo CTA.",
    prompt: "A futuristic AI tech startup landing page with a hero section featuring animated gradient backgrounds, floating UI elements, a feature comparison grid, integration logos, a live demo CTA section, and an enterprise contact form. Dark theme with electric blue and purple gradients. Ultra-modern design.",
    thumbnail: "from-indigo-600 to-cyan-500",
    tags: ["Tech", "AI", "Startup"],
  },
  {
    id: "event-conference",
    name: "Event & Conference",
    category: "Events",
    description: "Conference page with speaker lineup, schedule, and ticket registration.",
    prompt: "A tech conference landing page with a countdown timer hero, speaker lineup cards with photos and bios, a multi-track schedule/agenda, sponsor logos, venue information, and a ticket purchase section with different tiers. Modern and professional with a blue color scheme.",
    thumbnail: "from-blue-600 to-blue-600",
    tags: ["Event", "Conference", "Tickets"],
  },
  {
    id: "real-estate",
    name: "Luxury Real Estate",
    category: "Real Estate",
    description: "Premium real estate with hero carousel, property cards, agent profiles, and neighborhood showcase.",
    prompt: "A premium luxury real estate website. HERO: Full-viewport hero carousel (.hero-carousel) showing 3-5 stunning property photos (use picsum images: seed/luxury-house/1400/800, seed/modern-villa/1400/800, seed/penthouse-view/1400/800, seed/pool-villa/1400/800, seed/estate-garden/1400/800). White overlay headline text (.overlay-text) with elegant serif font. PROPERTIES: A featured listings section with .property-grid showing 6 property cards (.property-card) — each with large image (.property-card-img), status badge (.status-badge .status-for-sale), price (.property-card-price), and beds/baths/sqft using .feature-badge in .property-card-meta. AGENTS: Agent profile section with 3 agents, professional photos, contact info, bio. NEIGHBORHOODS: Full-width neighborhood showcase with large images and descriptions of 4 areas. TESTIMONIALS: Client success stories with specific sale amounts and timeframes. STATS: Properties sold (2,847), years in business (18), average sale price ($2.4M), client satisfaction (98%). CTA: Schedule a private viewing form. DESIGN: Navy (#1a365d) and gold (#c9a96e) palette, Playfair Display serif headings, full-bleed imagery throughout. This must look like a $50,000 agency site — cinematic, aspirational, visually stunning. NO sparse white pages.",
    thumbnail: "from-blue-900 to-yellow-700",
    tags: ["Real Estate", "Luxury", "Property", "Listings"],
  },
  {
    id: "music-artist",
    name: "Music Artist",
    category: "Entertainment",
    description: "Artist page with album showcase, tour dates, and merch store.",
    prompt: "A music artist/band website with a full-screen hero with artist name, a latest album showcase section, a tour dates list with venue and ticket links, a music player UI element, a merch store section, and social media links. Dark and moody with neon accent colors.",
    thumbnail: "from-blue-900 to-pink-600",
    tags: ["Music", "Artist", "Entertainment"],
  },
  {
    id: "nonprofit-charity",
    name: "Nonprofit & Charity",
    category: "Nonprofit",
    description: "Charity site with impact stats, donation section, and volunteer signup.",
    prompt: "A nonprofit charity website with an emotional hero section, impact statistics with large numbers, a programs/initiatives section, a donation form with suggested amounts, volunteer sign-up, latest news/blog section, and partner logos. Warm, hopeful colors with greens and earth tones.",
    thumbnail: "from-green-700 to-emerald-500",
    tags: ["Nonprofit", "Charity", "Donation"],
  },
  {
    id: "law-firm",
    name: "Law Firm",
    category: "Business",
    description: "Authoritative legal practice site with practice areas, attorney profiles, and case results.",
    prompt: "A prestigious law firm website with a sophisticated hero section featuring a cityscape background image (.hero-image) and white overlay text. Practice areas in an elegant grid. Attorney profiles with professional photos, credentials, and bar admissions. Case results with specific settlements/verdicts ($4.2M recovery, 98% success rate). Client testimonials from corporate clients. FAQ addressing common legal concerns. Contact form for free consultation. Dark navy (#0f172a) and warm gold (#b8860b) color scheme, serif headings (Merriweather), light background. Conservative but premium — conveys authority and trust.",
    thumbnail: "from-slate-800 to-amber-700",
    tags: ["Law", "Legal", "Attorney", "Professional"],
  },
  {
    id: "dental-clinic",
    name: "Dental & Medical Clinic",
    category: "Health",
    description: "Clean medical practice site with services, doctor profiles, and appointment booking.",
    prompt: "A modern dental/medical clinic website with a calming hero section featuring a clean interior photo (.hero-image), services grid with icons (cleanings, implants, cosmetic, emergency), doctor profiles with qualifications and specialties, patient testimonials with before/after stories, insurance accepted badges, office tour photo gallery (.image-gallery), and an appointment booking form. Soft teal (#0d9488) and white palette, clean sans-serif fonts (Inter), lots of whitespace. Conveys cleanliness, professionalism, and patient comfort.",
    thumbnail: "from-teal-500 to-cyan-400",
    tags: ["Medical", "Dental", "Health", "Clinic"],
  },
  {
    id: "wedding-planner",
    name: "Wedding & Events",
    category: "Events",
    description: "Elegant wedding planner site with gallery, packages, and inquiry form.",
    prompt: "An elegant wedding planner website with a romantic hero section featuring a full-bleed floral/venue photo (.hero-image) with delicate overlay text. Portfolio gallery (.image-gallery) of past weddings. Service packages (Intimate, Classic, Grand) with pricing. Vendor partners section. Client love stories (testimonials with wedding date and venue). Planning timeline/process steps. Inquiry form for consultations. Soft blush (#fce7f3), sage green (#86efac), and cream palette. Elegant serif headings (Cormorant Garamond). Romantic, aspirational, feminine sophistication.",
    thumbnail: "from-pink-300 to-rose-400",
    tags: ["Wedding", "Events", "Planner", "Elegant"],
  },
  {
    id: "saas-dashboard",
    name: "SaaS Analytics Platform",
    category: "Technology",
    description: "Data-driven SaaS page with dashboard preview, integrations, and enterprise features.",
    prompt: "A data analytics SaaS platform landing page with a hero featuring an animated gradient background (.hero-aurora) and a dashboard screenshot mockup. Key metrics bar (10M+ data points, 500+ integrations, 99.9% uptime). Feature grid showing analytics capabilities with chart icons. Integration logos (Slack, Salesforce, HubSpot, etc.). Pricing with Free/Pro/Enterprise tiers. Enterprise security features (SOC 2, GDPR, SSO). Customer success stories from Fortune 500 companies. Dark theme (#0a0a1a) with electric blue (#3b82f6) and violet (#8b5cf6) accents. Ultra-modern, technical, data-forward.",
    thumbnail: "from-violet-700 to-blue-600",
    tags: ["SaaS", "Analytics", "Dashboard", "Enterprise"],
  },
  {
    id: "construction-company",
    name: "Construction & Contractor",
    category: "Business",
    description: "Rugged construction company site with project gallery, services, and quote request.",
    prompt: "A professional construction company website with a powerful hero featuring a large construction site photo (.hero-image) and bold overlay text. Services grid (residential, commercial, renovation, design-build) with project photos. Completed projects gallery (.image-gallery) with before/after shots. Safety certifications and insurance badges. Team section with experienced crew. Stats (500+ projects, 25 years, 100% licensed & insured). Client testimonials from property developers. Free quote request form. Strong, masculine colors — charcoal (#1e293b), construction orange (#ea580c), concrete gray. Bold sans-serif headings (Oswald).",
    thumbnail: "from-gray-800 to-orange-600",
    tags: ["Construction", "Contractor", "Building", "Services"],
  },
  {
    id: "yoga-wellness",
    name: "Yoga & Wellness Studio",
    category: "Health",
    description: "Serene wellness studio site with class schedule, instructor profiles, and membership.",
    prompt: "A serene yoga and wellness studio website with a peaceful hero section featuring a meditation/yoga photo (.hero-image) with soft overlay text. Class schedule displayed in a clean weekly timetable. Instructor profiles with bios and specialties. Membership plans (Drop-in, Monthly, Annual) with pricing. Wellness blog highlights. Studio photo gallery (.image-gallery). Testimonials about transformation journeys. First class free CTA. Soft sage (#86efac), lavender (#c4b5fd), and warm cream palette. Elegant flowing fonts (Cormorant Garamond for headings, Lato for body). Calm, mindful, welcoming.",
    thumbnail: "from-green-300 to-purple-300",
    tags: ["Yoga", "Wellness", "Studio", "Health"],
  },
  {
    id: "automotive-dealer",
    name: "Auto Dealership",
    category: "Business",
    description: "Sleek car dealership site with vehicle inventory, financing, and trade-in form.",
    prompt: "A sleek automotive dealership website with a cinematic hero carousel (.hero-carousel) showing 3-4 luxury vehicles (use seed/luxury-car, seed/sports-car, seed/suv-vehicle, seed/sedan-car). Vehicle inventory grid with cards showing make/model, year, price, mileage. Featured vehicles section with large photos. Financing calculator section. Trade-in value form. Service department section. Dealer stats (2,500+ cars sold, 15 years, 4.8 star rating). Customer reviews. Contact with dealership hours and map placeholder. Dark metallic (#0f172a) with racing red (#dc2626) and chrome silver accents. Bold, premium, automotive feel.",
    thumbnail: "from-slate-900 to-red-700",
    tags: ["Auto", "Cars", "Dealership", "Vehicles"],
  },
  {
    id: "coffee-shop",
    name: "Coffee Shop & Cafe",
    category: "Food & Drink",
    description: "Cozy cafe site with menu, locations, loyalty program, and online ordering.",
    prompt: "A warm, inviting coffee shop website with a full-bleed hero photo (.hero-image) of a beautifully crafted latte with soft overlay text. Menu section organized by category (espresso drinks, pour-overs, pastries, breakfast) with prices. Locations section with addresses and hours for 3 shops. Our Story section about coffee sourcing and roasting process. Loyalty program signup. Instagram-style photo gallery (.image-gallery) of drinks and interior. Testimonials from regulars. Online order CTA. Warm mocha (#78350f), cream (#fef3c7), and espresso brown palette. Cozy serif headings (Playfair Display). Artisanal, warm, community-focused.",
    thumbnail: "from-amber-800 to-yellow-600",
    tags: ["Coffee", "Cafe", "Food", "Drinks"],
  },

  // ══════════════════════════════════════════════════
  //  EXPANDED TEMPLATES — 80+ additional templates
  //  3-5 per generator type for deep industry coverage
  // ══════════════════════════════════════════════════

  // ── SaaS & Tech (5 more) ──
  {
    id: "saas-crm",
    name: "CRM Dashboard",
    category: "Technology",
    description: "Customer relationship management dashboard with pipeline view and contact management.",
    prompt: "A CRM dashboard application. Left sidebar with nav (Dashboard, Contacts, Deals, Pipeline, Reports). Main area: KPI cards (total deals $2.4M, new leads 47, win rate 68%, avg deal size $12K). Sales pipeline Kanban: Lead → Qualified → Proposal → Negotiation → Won columns with deal cards showing company name, value, probability. Contact table with name, company, email, last activity, deal stage badge. Activity timeline showing calls, emails, meetings. Revenue chart (SVG line chart). Quick actions: Add Contact, Log Call, Create Deal. Clean white UI, blue accents (#3b82f6), Inter font.",
    thumbnail: "from-blue-500 to-indigo-600",
    tags: ["SaaS", "CRM", "Dashboard", "Sales"],
  },
  {
    id: "saas-project",
    name: "Project Management App",
    category: "Technology",
    description: "Kanban board with task management, timelines, and team workload.",
    prompt: "A project management tool. Left sidebar: workspace name, projects list, + Create Project. Top bar: project name 'Marketing Launch Q2', view tabs (Board, List, Timeline, Calendar). Kanban board with 4 columns: Backlog (3 cards), In Progress (4 cards), Review (2 cards), Done (5 cards). Each card: title, assignee avatar, priority dot (red/yellow/green), due date, subtask count '3/5', labels. Team workload section showing 4 members with task count bars. Filter bar with assignee, priority, label dropdowns. Clean minimal design like Linear/Notion. Dark sidebar #1e293b, white main area, purple accent #8b5cf6.",
    thumbnail: "from-purple-600 to-indigo-500",
    tags: ["SaaS", "Project Management", "Kanban", "Team"],
  },
  {
    id: "saas-email-tool",
    name: "Email Marketing Platform",
    category: "Technology",
    description: "Email campaign builder with templates, analytics, and subscriber management.",
    prompt: "An email marketing platform dashboard. Sidebar: Campaigns, Templates, Subscribers, Automation, Analytics. Dashboard view: 4 KPI cards (subscribers 12,456, open rate 34.2%, click rate 8.7%, revenue $4,280). Recent campaigns table: name, sent date, recipients, open rate, click rate, status badge (Sent/Scheduled/Draft). Campaign builder preview showing email template with drag blocks. Subscriber growth line chart. Top performing emails list. Quick actions: Create Campaign, Import Subscribers, A/B Test. Modern UI with teal accent #0d9488, clean typography, data-focused layout.",
    thumbnail: "from-teal-500 to-emerald-600",
    tags: ["SaaS", "Email", "Marketing", "Analytics"],
  },
  {
    id: "ai-tool-landing",
    name: "AI Tool Landing Page",
    category: "Technology",
    description: "Landing page for an AI-powered tool with demo, features, and API docs.",
    prompt: "An AI-powered tool landing page. Hero with .hero-aurora background, large headline 'AI That Understands Your Data', subheading about natural language analytics, live demo input box ('Ask anything about your data...'). Demo output showing a sample chart response. Social proof: 'Powering insights at' + 6 company logos. Features .grid-3: Natural Language Queries, Automated Reports, Predictive Analytics with animated icons. API section with code snippet (dark code block). Pricing: Free/Pro $49/Enterprise. Integration logos (Slack, Snowflake, BigQuery). SOC 2 and GDPR badges. Dark theme #0a0a1a with gradient purple-blue accents. Ultra-modern.",
    thumbnail: "from-violet-600 to-blue-500",
    tags: ["AI", "Tech", "SaaS", "Landing"],
  },
  {
    id: "devtools-landing",
    name: "Developer Tools Landing",
    category: "Technology",
    description: "Developer-focused landing page with code examples, CLI, and documentation.",
    prompt: "A developer tools landing page. Hero: terminal-style code block showing CLI usage, headline 'Ship Faster, Break Less'. Features in 2-column layout with code snippets on right. Getting Started section with 3 steps (Install, Configure, Deploy) each with terminal commands in dark code blocks. Integration badges (GitHub, GitLab, VS Code, JetBrains). Benchmark comparison table (Us vs Competitor A vs Competitor B). Open source stats: GitHub stars, contributors, weekly downloads. Community section with Discord and forum links. Dark theme with green terminal accent (#4ade80) on #0a0a0a background. Monospace headings (JetBrains Mono).",
    thumbnail: "from-gray-900 to-green-800",
    tags: ["Developer", "CLI", "DevTools", "Open Source"],
  },

  // ── E-Commerce (5 more) ──
  {
    id: "fashion-store",
    name: "Fashion Boutique",
    category: "E-Commerce",
    description: "High-end fashion store with lookbook, collections, and shopping cart.",
    prompt: "A luxury fashion boutique e-commerce site. Full-viewport hero carousel (.hero-carousel) with 3 seasonal lookbook photos (seed/fashion-model, seed/fashion-editorial, seed/designer-clothing). 'New Collection' badge overlay. Category navigation: Women, Men, Accessories, Sale. Product grid .grid-3: fashion items with large images (seed/fashion-item), brand name, product name, price with crossed-out original for sale items, 'New' and 'Sale' badges. Lookbook section: full-width editorial images. Size guide modal trigger. Free shipping banner. Newsletter with '10% off your first order'. Instagram feed. Minimal black and white palette with gold (#c9a96e) accents. Didot/Playfair headings.",
    thumbnail: "from-gray-900 to-amber-800",
    tags: ["Fashion", "E-Commerce", "Luxury", "Boutique"],
  },
  {
    id: "electronics-store",
    name: "Electronics Store",
    category: "E-Commerce",
    description: "Tech gadget store with product specs, comparison, and reviews.",
    prompt: "A modern electronics store. Hero banner: featured product (latest smartphone) with specs overlay and 'Pre-order Now' CTA. Category bar: Phones, Laptops, Audio, Wearables, Gaming, Smart Home. Featured products .grid-4 with tech-style cards: product image, name, brief spec ('M3 chip, 16GB RAM'), star rating, price, 'Add to Cart' button. Product comparison table (3 products side-by-side). Deal of the day countdown timer. Customer reviews section with star breakdown bar chart. Trust signals: free 2-day shipping, 30-day returns, 2-year warranty, secure checkout. Newsletter signup. Dark charcoal (#18181b) with electric blue (#2563eb) accent. Clean tech aesthetic.",
    thumbnail: "from-slate-900 to-blue-700",
    tags: ["Electronics", "E-Commerce", "Tech", "Gadgets"],
  },
  {
    id: "handmade-marketplace",
    name: "Handmade & Artisan Shop",
    category: "E-Commerce",
    description: "Artisan marketplace with maker stories, handcrafted products, and gift options.",
    prompt: "A handmade artisan marketplace. Hero with warm lifestyle photo (.hero-image seed/artisan-workshop), headline 'Handcrafted with Love' in flowing script font. Categories: Ceramics, Textiles, Jewelry, Home Decor, Art, Candles. Product grid .grid-3: product cards with natural photography, maker name + small avatar, price, 'Handmade' badge, add to cart. Maker Stories section: 3 artisan profiles with workshop photos and brief bios. Gift section with curated gift boxes at different price points. Sustainability section about eco-friendly materials. Customer reviews with photos. Warm earth tones: terracotta (#c2410c), cream (#fffbeb), sage (#6b7280). Soft serif headings.",
    thumbnail: "from-orange-600 to-amber-500",
    tags: ["Handmade", "Artisan", "E-Commerce", "Marketplace"],
  },
  {
    id: "grocery-delivery",
    name: "Grocery Delivery",
    category: "E-Commerce",
    description: "Online grocery store with categories, weekly deals, and delivery scheduling.",
    prompt: "An online grocery delivery service. Header: logo, delivery address input, cart with item count. Hero: 'Fresh groceries delivered in 30 minutes' with promotional banners. Category icons strip: Fruits & Veg, Dairy, Meat, Bakery, Beverages, Snacks, Household. Weekly deals carousel with discount badges. Product grid: item image, name, weight/size, price (with per-unit price), +/- quantity stepper, 'Add' button. Popular items section. Recipe inspiration cards linking to ingredient lists. Delivery time picker (Today/Tomorrow with time slots). Minimum order notice. Loyalty points display. Fresh green (#16a34a) and white palette with orange deal highlights. Clean, functional, fast-looking.",
    thumbnail: "from-green-600 to-emerald-500",
    tags: ["Grocery", "Delivery", "E-Commerce", "Food"],
  },
  {
    id: "subscription-box",
    name: "Subscription Box Service",
    category: "E-Commerce",
    description: "Monthly subscription box with unboxing gallery, plans, and gifting options.",
    prompt: "A subscription box service website. Hero: lifestyle unboxing photo (.hero-image seed/subscription-box), headline 'Curated Just for You', subtitle 'Monthly surprises delivered to your door'. How it works: 3 steps (Choose Your Plan → Get Matched → Unbox Joy). Subscription plans .grid-3: Monthly ($29), Quarterly ($79, save 10%), Annual ($279, save 20%), each with what's included. Past boxes gallery showing previous months' contents with themed names. Customer unboxing video/photo testimonials. Gift a subscription CTA with gift card mockup. FAQ about shipping, cancellation, customization. Playful, colorful design: coral (#f43f5e) accent, soft backgrounds, rounded elements. Fun, approachable, gifting-friendly.",
    thumbnail: "from-rose-500 to-pink-400",
    tags: ["Subscription", "E-Commerce", "Gift", "Monthly Box"],
  },

  // ── Portfolio & Creative (4 more) ──
  {
    id: "photographer-portfolio",
    name: "Photography Portfolio",
    category: "Portfolio",
    description: "Full-screen photo gallery with lightbox, categories, and booking.",
    prompt: "A professional photographer portfolio. Full-screen hero with stunning landscape photo (.hero-image seed/photography-landscape), photographer name in minimal white text, scroll indicator. Portfolio gallery: filterable by category (Wedding, Portrait, Landscape, Commercial, Street) with masonry-style .image-gallery. Each image opens in lightbox on click. About section: photographer portrait, brief bio, equipment list, awards. Services with pricing hints: Wedding ($3,500+), Portrait ($500+), Commercial (custom quote). Client testimonials with wedding/event photos. Instagram feed row. Contact/booking form. Minimal design: black background, white text, zero clutter — photos are the ONLY decoration. Monospace for name, system sans for body.",
    thumbnail: "from-gray-900 to-gray-700",
    tags: ["Photography", "Portfolio", "Gallery", "Creative"],
  },
  {
    id: "design-agency",
    name: "Design Agency Portfolio",
    category: "Portfolio",
    description: "Agency portfolio with case studies, services, and team showcase.",
    prompt: "A design agency portfolio. Hero with animated gradient (.hero-aurora), agency name in oversized bold type (clamp(3rem,8vw,8rem)), tagline 'We Design Digital Experiences'. Featured work: 3 full-width case study previews with large images, client name, project type badge, brief result ('Increased conversions by 230%'), 'View Case Study' link. Services grid: Brand Identity, UI/UX Design, Web Development, Motion Design. Process section: Discovery → Strategy → Design → Build → Launch. Client logos strip (muted). Team: 6 members with playful hover effects on photos. Awards bar: Awwwards, FWA, CSS Design Awards badges. Contact with 'Start a Project' form. Dark theme #0a0a0a with accent color that shifts per section.",
    thumbnail: "from-gray-900 to-purple-900",
    tags: ["Agency", "Design", "Portfolio", "Case Studies"],
  },
  {
    id: "freelancer-portfolio",
    name: "Freelancer Personal Site",
    category: "Portfolio",
    description: "Individual freelancer site with skills, testimonials, and availability.",
    prompt: "A freelancer personal website. Hero: large name 'Taylor Morrison' with title 'Full-Stack Developer & Designer', availability badge ('Available for projects'), primary CTA 'Let's Talk', secondary 'View Work'. Skills section with tech icons and proficiency bars (React 95%, Node.js 90%, Python 85%, Figma 80%). Projects: .grid-2 with 4 project cards, each with screenshot, title, tech stack tags, brief description, live site + GitHub links. Experience timeline: 3 positions with company, role, dates, key achievements. Testimonials: 3 client quotes with ratings. Blog preview: 2 recent articles. Contact form with cal.com embed placeholder. Minimal light design with one bold accent color. Professional but personal.",
    thumbnail: "from-sky-500 to-indigo-500",
    tags: ["Freelancer", "Portfolio", "Developer", "Personal"],
  },
  {
    id: "architect-portfolio",
    name: "Architecture Firm",
    category: "Portfolio",
    description: "Architecture firm showcase with project gallery, process, and team.",
    prompt: "An architecture firm portfolio. Full-width hero with stunning building photo (.hero-image seed/modern-architecture/1600/900), firm name in clean sans-serif. Project showcase: 6 projects with large images (seed/building-exterior, seed/interior-design, seed/urban-design), project name, location, year, typology (Residential/Commercial/Cultural). Project detail layout: full-width photo, floor plan placeholder, materials list, project story. Services: Architecture, Interior Design, Urban Planning, Sustainability Consulting. Process: Concept → Schematic → Development → Construction → Completion. Awards and publications. Team with professional headshots. Contact with project inquiry form. Ultra-clean, whitespace-heavy, architectural grid system. Black text, white bg, one accent (warm gray or gold).",
    thumbnail: "from-stone-600 to-stone-400",
    tags: ["Architecture", "Portfolio", "Design", "Buildings"],
  },

  // ── Health & Wellness (4 more) ──
  {
    id: "physical-therapy",
    name: "Physical Therapy Clinic",
    category: "Health",
    description: "PT clinic with services, conditions treated, and appointment booking.",
    prompt: "A physical therapy clinic website. Hero with clinic interior photo (.hero-image seed/therapy-clinic), headline 'Move Better, Live Better', appointment CTA. Services .grid-3: Sports Rehabilitation, Post-Surgery Recovery, Chronic Pain Management, Pediatric PT, Orthopedic PT, Geriatric Care. Conditions treated list: back pain, knee injuries, shoulder issues, etc. Meet our therapists: 4 PT profiles with credentials (DPT, OCS). Patient success stories with before/after mobility improvements. Insurance accepted logos. FAQ about sessions, what to expect, insurance coverage. Appointment booking form with service dropdown and preferred date. Calming blue-green palette (#0d9488 teal, white, soft gray). Professional medical feel with warmth.",
    thumbnail: "from-teal-600 to-cyan-500",
    tags: ["Physical Therapy", "Health", "Medical", "Clinic"],
  },
  {
    id: "mental-health",
    name: "Mental Health Practice",
    category: "Health",
    description: "Therapist practice with approach, services, and confidential intake form.",
    prompt: "A mental health therapy practice website. Calming hero with abstract watercolor background (soft gradient), headline 'A Safe Space to Heal and Grow', subtitle about confidential compassionate care. Services: Individual Therapy, Couples Counseling, Group Therapy, Anxiety & Depression, Trauma & PTSD, Life Transitions. Our Approach section: evidence-based methods (CBT, EMDR, mindfulness). Therapist profiles with warm photos, credentials, specialties, personal statement. What to Expect: first session walkthrough. Sliding scale pricing mention. Crisis resources banner. Confidential intake form (name, email, brief concern, insurance, preferred contact method). VERY calming palette: sage green (#a7c4a0), lavender (#c4b5fd), warm cream. Gentle, non-clinical, welcoming feel.",
    thumbnail: "from-green-300 to-violet-300",
    tags: ["Mental Health", "Therapy", "Counseling", "Wellness"],
  },
  {
    id: "nutrition-coach",
    name: "Nutrition & Wellness Coach",
    category: "Health",
    description: "Nutrition coaching site with programs, meal plans, and transformation stories.",
    prompt: "A nutrition coaching website. Hero with vibrant food photo (.hero-image seed/healthy-food), headline 'Fuel Your Best Life', CTA 'Start Your Transformation'. Programs .grid-3: Weight Loss (12 weeks), Performance Nutrition (athletes), Gut Health Reset. Each with duration, what's included, price. How it works: Consultation → Custom Plan → Weekly Check-ins → Results. Before/After transformations with photos, names, results ('Lost 30 lbs in 12 weeks'). Sample meal plan preview (day of meals with macros). Blog preview: 3 nutrition articles. Free resources: downloadable grocery list CTA. Testimonials with specific results. Booking form for free discovery call. Fresh, energetic: green (#16a34a), orange (#f97316), white. Clean, health-forward, inspiring.",
    thumbnail: "from-green-500 to-orange-400",
    tags: ["Nutrition", "Coach", "Health", "Wellness"],
  },
  {
    id: "veterinary-clinic",
    name: "Veterinary Clinic",
    category: "Health",
    description: "Vet clinic with services, staff, pet portal, and emergency info.",
    prompt: "A veterinary clinic website. Warm hero with happy dog/cat photo (.hero-image seed/happy-pet), headline 'Compassionate Care for Your Best Friend', emergency number prominently displayed. Services: Wellness Exams, Vaccinations, Surgery, Dental Care, Emergency 24/7, Grooming. Meet our vets: 3 veterinarian profiles with photos, specialties, and fun facts. New patient section: what to bring, registration form download, first visit info. Pet care tips blog preview. Client testimonials with pet photos and names. Hours & location with emergency after-hours info. Appointment request form (pet name, species, reason for visit). Warm friendly palette: warm blue (#3b82f6), warm gray, white. Photos of happy pets throughout. Trustworthy, compassionate, family-friendly.",
    thumbnail: "from-blue-500 to-teal-400",
    tags: ["Veterinary", "Pets", "Health", "Clinic"],
  },

  // ── Food & Hospitality (4 more) ──
  {
    id: "bakery-shop",
    name: "Artisan Bakery",
    category: "Food & Drink",
    description: "Bakery with product showcase, custom orders, and story.",
    prompt: "An artisan bakery website. Hero with fresh bread photo (.hero-image seed/artisan-bread/1400/800), headline in handwritten-style font 'Baked Fresh Every Morning'. Product categories: Sourdough, Pastries, Cakes, Custom Orders. Product grid with gorgeous food photography (seed/croissant, seed/sourdough-loaf, seed/birthday-cake), name, brief description, price. Custom cake order section: occasion dropdown, flavor, size, design preferences, delivery date. Our Story: family bakery since 1985, master baker profile, sourcing philosophy. Instagram gallery (.image-gallery) of daily bakes. Hours & order ahead info. Warm, inviting: wheat gold (#d4a76a), dark brown (#3e2723), cream (#fffde7). Handwritten script for accents, clean serif for body.",
    thumbnail: "from-amber-600 to-yellow-500",
    tags: ["Bakery", "Food", "Artisan", "Custom Cakes"],
  },
  {
    id: "bar-cocktail-lounge",
    name: "Cocktail Bar & Lounge",
    category: "Food & Drink",
    description: "Upscale bar with signature cocktails, events, and reservations.",
    prompt: "An upscale cocktail bar website. Full-viewport hero with moody bar interior photo (.hero-image seed/cocktail-bar/1600/900), bar name in neon-glow effect text, overlay-text 'Craft Cocktails & Good Vibes'. Signature cocktails section: 6 drinks with artistic photos, names, ingredients, price. Menu: Cocktails (Classic, Signature, Seasonal), Wine, Beer & Cider, Small Plates. Events section: live jazz Fridays, DJ Saturdays, cocktail masterclasses. Happy Hour banner with times and specials. Gallery (.image-gallery) of interior, drinks, atmosphere. Private events/booking info. Hours & location. Dark, moody theme: near-black (#0c0c0c), amber (#d97706), warm red (#991b1b). Art deco-inspired accents. Intimate, sophisticated nightlife feel.",
    thumbnail: "from-gray-900 to-amber-900",
    tags: ["Bar", "Cocktails", "Nightlife", "Food & Drink"],
  },
  {
    id: "hotel-resort",
    name: "Luxury Hotel & Resort",
    category: "Food & Drink",
    description: "Resort website with rooms, amenities, gallery, and booking.",
    prompt: "A luxury hotel and resort website. Full-viewport hero carousel (.hero-carousel) with 4 stunning resort photos (seed/luxury-resort, seed/hotel-pool, seed/resort-beach, seed/hotel-suite). Overlay headline 'Your Escape Awaits'. Rooms section: 4 room types (Standard, Deluxe, Suite, Presidential) with photo, description, amenities icons, price per night, 'Book Now' CTA. Amenities: infinity pool, spa, fine dining, fitness center, private beach — each with icon and photo. Dining section: 2 restaurants with cuisine type and hours. Spa & Wellness: treatment menu with descriptions and pricing. Gallery (.image-gallery) with 8 resort photos. Guest reviews. Location with nearby attractions. Booking widget: check-in/check-out dates, guests, room type. Sophisticated navy (#1e3a5f) and gold (#c9a96e) palette. Full-bleed luxury imagery throughout.",
    thumbnail: "from-blue-900 to-amber-700",
    tags: ["Hotel", "Resort", "Luxury", "Hospitality"],
  },
  {
    id: "food-truck",
    name: "Food Truck / Street Food",
    category: "Food & Drink",
    description: "Food truck with menu, location schedule, and catering info.",
    prompt: "A fun food truck website. Hero with colorful food truck photo (.hero-image seed/food-truck/1400/800), bold playful headline 'Tacos That Move', today's location displayed prominently. Menu with large food photos: tacos, burritos, bowls, sides, drinks with playful descriptions and prices. Weekly schedule: Monday-Sunday with location names, times, and map link for each day. Catering section: 'Bring the truck to your event!' with pricing packages and past events gallery. Our Story: truck origin story with founder photo. Customer favorites with ratings. Social media feed. Newsletter for location updates. Bright, energetic: yellow (#fbbf24), red (#ef4444), white, with playful hand-drawn feel. Bold sans-serif headings. Fun, casual, street food energy.",
    thumbnail: "from-yellow-500 to-red-500",
    tags: ["Food Truck", "Street Food", "Catering", "Mobile"],
  },

  // ── Business & Professional (5 more) ──
  {
    id: "accounting-firm",
    name: "Accounting & Tax Firm",
    category: "Business",
    description: "Professional accounting firm with services, team, and client resources.",
    prompt: "A professional accounting firm website. Clean hero with cityscape photo (.hero-image seed/business-district), headline 'Financial Clarity for Growing Businesses'. Services .grid-3: Tax Planning & Preparation, Bookkeeping, Business Advisory, Payroll, Audit & Assurance, CFO Services. Industry expertise: Healthcare, Tech Startups, Real Estate, Nonprofits. Team: 4 CPAs with credentials and specialties. Client resources: tax deadline calendar, document checklist download, calculators. Testimonials from business owners citing specific results ('Saved $47K in taxes last year'). Free consultation CTA. Locations (2 offices). FAQ about pricing, what to bring, timeline. Conservative professional palette: dark navy (#1e293b), white, green accent (#059669 for financial growth). Trustworthy, methodical, premium.",
    thumbnail: "from-slate-800 to-green-700",
    tags: ["Accounting", "Tax", "Business", "Professional"],
  },
  {
    id: "consulting-firm",
    name: "Management Consulting",
    category: "Business",
    description: "Consulting firm with case studies, methodology, and team expertise.",
    prompt: "A management consulting firm website. Sophisticated hero with abstract geometric background (dark gradient), headline 'Strategy That Drives Results'. Practice areas: Digital Transformation, Operations Excellence, Growth Strategy, M&A Advisory, Organization Design. Methodology: 4-phase approach (Diagnose → Design → Deliver → Sustain) with connecting lines. Case studies: 3 featured with industry, challenge, approach, result metrics ('Revenue increased 34% in 18 months'). Leadership team: 4 partners with backgrounds (ex-McKinsey, ex-BCG). Thought leadership: 3 recent articles/whitepapers. Industries served: icons + names. Client logos (muted). Contact for engagement discussion. Dark sophisticated palette: #0f172a, white, gold (#b8860b) accents. Premium, authoritative, McKinsey-level presentation.",
    thumbnail: "from-slate-900 to-yellow-800",
    tags: ["Consulting", "Strategy", "Business", "Enterprise"],
  },
  {
    id: "insurance-agency",
    name: "Insurance Agency",
    category: "Business",
    description: "Insurance agency with product lines, quotes, and claims support.",
    prompt: "An insurance agency website. Hero with family/business protection theme (.hero-image seed/family-protection), headline 'Protection You Can Count On', 'Get a Free Quote' CTA. Insurance types .grid-3: Auto, Home, Life, Business, Health, Umbrella. Each with icon, brief description, 'Get Quote' button. Quote form wizard: insurance type → basic info → coverage preferences → contact details. Why Choose Us: local agency, 24/7 claims support, competitive rates, personalized service. Team: 3 agents with specialties and direct phone numbers. Claims section: how to file, emergency numbers, FAQ. Customer testimonials about claims experience. Partners: carrier logos (State Farm, Progressive, etc.). Blue (#2563eb) and white palette with green (#059669) CTAs. Trustworthy, protective, community-focused.",
    thumbnail: "from-blue-600 to-green-600",
    tags: ["Insurance", "Agency", "Business", "Protection"],
  },
  {
    id: "cleaning-service",
    name: "Cleaning Service",
    category: "Business",
    description: "Cleaning company with services, booking, and pricing calculator.",
    prompt: "A professional cleaning service website. Bright hero with sparkling clean home photo (.hero-image seed/clean-home), headline 'Spotless Homes, Happy Families', instant quote CTA. Services: Regular Cleaning, Deep Cleaning, Move-In/Out, Office Cleaning, Post-Construction, Window Cleaning. Pricing calculator: home size (sq ft slider), bedrooms, bathrooms, frequency (weekly/biweekly/monthly), add-ons (fridge, oven, laundry) → estimated price. Booking form: date picker, time preference, address, special instructions. Our team: insured, bonded, background-checked, 5-star trained. Before/after gallery (.image-gallery) showing transformations. Customer reviews with 5-star ratings. 100% satisfaction guarantee badge. Eco-friendly products section. Bright, clean: sky blue (#0ea5e9), white, spring green (#22c55e). Trustworthy, sparkling clean aesthetic.",
    thumbnail: "from-sky-500 to-green-400",
    tags: ["Cleaning", "Service", "Home", "Business"],
  },
  {
    id: "plumber-hvac",
    name: "Plumbing & HVAC",
    category: "Business",
    description: "Trade service with emergency line, service areas, and booking.",
    prompt: "A plumbing and HVAC service company website. Hero with technician at work photo (.hero-image seed/plumber-working), headline '24/7 Emergency Service', large phone number displayed, 'Book Online' CTA. Emergency banner: 'Burst pipe? AC broken? Call now: (555) 123-4567'. Services .grid-3: Plumbing Repair, Drain Cleaning, Water Heater, AC Installation, Heating Repair, Duct Cleaning. Service area map showing covered zip codes/cities. Pricing: transparent service call fee, common repair price ranges. Technician profiles: licensed, certified, experienced. Customer reviews with star ratings and specific job descriptions. Seasonal maintenance plans. Coupons: '$50 off first service' banner. Service request form: service type, urgency, address, description, preferred time. Blue (#2563eb) and orange (#ea580c) palette. Bold, reliable, action-oriented.",
    thumbnail: "from-blue-700 to-orange-500",
    tags: ["Plumbing", "HVAC", "Service", "Emergency"],
  },

  // ── Events & Entertainment (3 more) ──
  {
    id: "music-festival",
    name: "Music Festival",
    category: "Events",
    description: "Festival site with lineup, schedule, tickets, and camping info.",
    prompt: "A music festival website. Explosive hero with festival crowd photo (.hero-image seed/music-festival/1600/900), festival logo overlay, dates prominently displayed, countdown timer. Lineup: headliners (3 large names with photos), supporting acts organized by day (Friday/Saturday/Sunday). Stage schedule: multi-stage timetable (Main Stage, Tent Stage, DJ Stage) with time blocks. Tickets: General Admission $149, VIP $299, Platinum $499 with comparison. Camping & accommodation: tent/glamping/hotel options with photos and pricing. Getting there: map, shuttle info, parking. Festival map illustration placeholder. FAQ: what to bring, prohibited items, age policy. Past festival gallery (.image-gallery). Vibrant, psychedelic: neon pink (#ec4899), electric blue (#3b82f6), black bg. Festival energy — bold, loud, exciting.",
    thumbnail: "from-pink-600 to-blue-600",
    tags: ["Festival", "Music", "Events", "Tickets"],
  },
  {
    id: "workshop-course",
    name: "Workshop & Masterclass",
    category: "Events",
    description: "Workshop registration page with instructor, curriculum, and testimonials.",
    prompt: "A workshop/masterclass registration page. Hero: instructor photo with overlay, workshop title 'Master Product Design in 8 Weeks', start date, 'Enroll Now — 12 spots left' CTA with scarcity. What you'll learn: 8 module titles with brief descriptions in timeline format. Instructor bio: photo, credentials, notable work, social links. Who it's for: 3 persona descriptions. Format: live sessions, recordings, community access, 1-on-1 feedback. Student work showcase: .image-gallery of past student projects. Testimonials: 4 students with specific outcomes. Pricing: Early Bird $497 (crossed-out $697), 3-payment option, 30-day guarantee. Curriculum breakdown: expandable weeks/modules. FAQ about time commitment, prerequisites, tools needed. Professional, educational: dark blue (#1e3a5f), white, amber CTAs (#f59e0b). Authoritative yet inviting.",
    thumbnail: "from-blue-800 to-amber-600",
    tags: ["Workshop", "Course", "Education", "Events"],
  },
  {
    id: "comedy-show",
    name: "Comedy Club / Live Shows",
    category: "Entertainment",
    description: "Comedy venue with upcoming shows, comedians, and ticket booking.",
    prompt: "A comedy club website. Dark, theatrical hero with stage spotlight photo (.hero-image seed/comedy-stage), club name in neon style, 'Tonight's Show' spotlight featuring headliner. Upcoming shows: calendar list with comedian photo, name, date, time, ticket price, 'Get Tickets' button. This week's lineup: 3 featured comedians with headshots and bio excerpts. Venue info: seating chart placeholder, bar menu highlights, group package deals. Open mic night signup. Comedy class registration. Photo gallery (.image-gallery) of past shows and performers. Newsletter for show announcements. Location with parking info. Dark theatrical theme: near-black (#111111), red curtain accents (#dc2626), warm spotlight yellow (#fbbf24). Fun, exciting, nightlife energy with humor.",
    thumbnail: "from-red-800 to-yellow-600",
    tags: ["Comedy", "Entertainment", "Live Shows", "Tickets"],
  },

  // ── Education (3 more) ──
  {
    id: "language-school",
    name: "Language School",
    category: "Education",
    description: "Language school with courses, levels, placement test, and enrollment.",
    prompt: "A language school website. Colorful hero with diverse students photo (.hero-image seed/language-class), headline 'Speak the World' in multiple scripts. Languages offered: Spanish, French, German, Mandarin, Japanese, Portuguese — each with flag icon. Course levels: Beginner (A1-A2), Intermediate (B1-B2), Advanced (C1-C2) with CEFR reference. Class formats: Group (8 students), Semi-Private (2-3), Private 1-on-1. Schedule: weekday mornings, evenings, Saturday intensives. Free placement test CTA. Teachers: 4 native speaker instructors with qualifications. Student testimonials about fluency achievements. Cultural events calendar. Pricing table by format and duration. Enrollment form: language, level, preferred format, start date. Warm, worldly: teal (#0d9488), orange (#f97316), white. International, friendly, immersive.",
    thumbnail: "from-teal-500 to-orange-500",
    tags: ["Language", "School", "Education", "Courses"],
  },
  {
    id: "tutoring-service",
    name: "Tutoring Service",
    category: "Education",
    description: "Tutoring center with subjects, tutor profiles, and session booking.",
    prompt: "An academic tutoring service website. Hero with student studying photo (.hero-image seed/student-studying), headline 'Expert Tutors, Better Grades', 'Book a Free Trial' CTA. Subjects: Math, Science, English, SAT/ACT Prep, AP Courses, College Admissions. Results stats: average grade improvement (+1.5 GPA), SAT score increase (+200 points), student satisfaction (98%). How it works: Match → Plan → Learn → Succeed. Top tutors: 4 profiles with education (MIT, Stanford), subjects, experience, rating, hourly rate. Session formats: In-Person, Online, Hybrid. Pricing: transparent hourly rates by subject and level. Parent testimonials with specific results ('Sarah raised her SAT from 1200 to 1450'). Free trial lesson form: student name, grade, subject, goals. Encouraging blue (#3b82f6) and green (#10b981) palette. Academic, trustworthy, results-driven.",
    thumbnail: "from-blue-500 to-green-500",
    tags: ["Tutoring", "Education", "Academic", "SAT Prep"],
  },
  {
    id: "daycare-preschool",
    name: "Daycare & Preschool",
    category: "Education",
    description: "Childcare center with programs, safety info, and enrollment.",
    prompt: "A daycare and preschool website. Bright, cheerful hero with playing children photo (.hero-image seed/children-playing), headline 'Where Little Minds Grow' in friendly rounded font. Programs by age: Infants (6-18 mo), Toddlers (18-36 mo), Preschool (3-5), Before/After School (5-12). Daily schedule: arrival, circle time, learning centers, outdoor play, lunch, rest, creative arts, pickup. Our approach: play-based learning, STEM activities, social-emotional development. Safety & security: licensed, CPR-certified staff, secure entry, cameras, health protocols. Facility tour gallery (.image-gallery): classrooms, playground, art room, garden. Staff: head teachers with Early Childhood Education degrees. Parent testimonials. Enrollment: tour request form + waitlist signup. Tuition info. Bright, playful: primary blue, sunshine yellow (#fbbf24), grass green (#22c55e). Child-friendly without being childish to parents.",
    thumbnail: "from-blue-400 to-yellow-400",
    tags: ["Daycare", "Preschool", "Childcare", "Education"],
  },

  // ── Nonprofit & Community (3 more) ──
  {
    id: "animal-shelter",
    name: "Animal Shelter & Rescue",
    category: "Nonprofit",
    description: "Animal shelter with adoptable pets, volunteer signup, and donation.",
    prompt: "An animal rescue and shelter website. Emotional hero with rescued dog (.hero-image seed/shelter-dog), headline 'Every Animal Deserves a Home', 'Meet Our Animals' and 'Donate' CTAs. Adoptable pets grid .grid-3: pet photo, name, breed, age, personality traits badge, 'Meet Me' button. Featured pet spotlight with longer story. Adoption process: 4 steps (Browse → Apply → Meet → Adopt). Volunteer section: dog walking, cat socialization, foster homes, event help — with signup form. Donation section: suggested amounts ($25 feeds a pet for a week, $50 covers vet visit, $100 sponsors a pet), monthly/one-time toggle. Success stories: adopted pets in their new homes. Events calendar: adoption fairs, fundraisers. Sponsors/partners. Warm, compassionate: warm amber (#d97706), sage green (#6b8f71), cream. Heartwarming, hopeful, action-driving.",
    thumbnail: "from-amber-600 to-green-600",
    tags: ["Animal Shelter", "Nonprofit", "Adoption", "Pets"],
  },
  {
    id: "community-foundation",
    name: "Community Foundation",
    category: "Nonprofit",
    description: "Community foundation with grant programs, impact reports, and donor portal.",
    prompt: "A community foundation website. Stately hero with community event photo (.hero-image seed/community-gathering), headline 'Investing in Our Community's Future'. Grant programs: Education, Health, Arts & Culture, Environment, Economic Development — each with current funding amount and application status (Open/Closed). Impact dashboard: total grants awarded ($12.4M), nonprofits supported (340+), community projects (580), years serving (25). Grant application process: eligibility → apply → review → award timeline. Featured grantees: 3 spotlight stories with project photos and outcomes. Donor section: ways to give (direct gift, donor-advised fund, planned giving, corporate), tax benefits info. Events: annual gala, grant ceremonies, community forums. Board of directors: names and professional affiliations. Trustworthy, established: navy (#1e3a5f), white, warm gold (#b8860b). Authoritative, community-proud.",
    thumbnail: "from-blue-900 to-amber-600",
    tags: ["Foundation", "Nonprofit", "Grants", "Community"],
  },
  {
    id: "church-religious",
    name: "Church & Religious Org",
    category: "Nonprofit",
    description: "Church website with service times, events, ministries, and giving.",
    prompt: "A church website. Welcoming hero with church community photo (.hero-image seed/church-community), name 'Grace Community Church', headline 'You Belong Here', service times prominently displayed (Sunday 9 AM & 11 AM). Watch Live banner for online streaming. About: pastor's message, beliefs, church story. Ministries .grid-3: Children's, Youth, Young Adults, Women's, Men's, Missions. Upcoming events: weekly calendar with Bible study, prayer group, community dinners, volunteer days. Sermons: recent messages with video/audio links, series archive. Connect: small groups, new here info, prayer requests form. Online giving: one-time/recurring, fund designation. Location with campus photo and directions. Warm, welcoming: warm navy (#1e3a5f), cream (#fef7ed), burgundy accent (#7f1d1d). Inviting, warm, community-focused. NOT preachy — welcoming to visitors.",
    thumbnail: "from-blue-900 to-red-800",
    tags: ["Church", "Religious", "Community", "Nonprofit"],
  },

  // ── Travel & Lifestyle (3 more) ──
  {
    id: "travel-blog",
    name: "Travel Blog",
    category: "Blog",
    description: "Travel blog with destinations, photo journals, and travel guides.",
    prompt: "A travel blog website. Full-width hero with stunning travel photo (.hero-image seed/travel-destination/1600/900), blog name in handwritten overlay, 'Explore the World Through My Lens'. Featured destination: large article card with cinematic image, destination name, excerpt. Recent posts .grid-3: destination thumbnail (16:9), country flag badge, title, date, read time, excerpt. Destination guides sidebar: popular countries with post counts. Travel tips section: packing lists, budget guides, visa info. Photo journal: full-width image gallery from recent trip. Newsletter: 'Get travel inspiration weekly'. About the blogger: portrait, travel stats (42 countries, 6 continents), gear list. Warm wanderlust palette: sunset orange (#f97316), ocean blue (#0ea5e9), sand (#fefce8). Adventurous, cinematic, inspiring. Georgia serif for headings.",
    thumbnail: "from-orange-500 to-blue-500",
    tags: ["Travel", "Blog", "Photography", "Adventure"],
  },
  {
    id: "personal-brand",
    name: "Personal Brand / Influencer",
    category: "Blog",
    description: "Personal brand site with content, collaborations, and media kit.",
    prompt: "A personal brand / influencer website. Bold hero with professional portrait (.hero-image seed/influencer-portrait), name large and bold, tagline 'Digital Creator | Speaker | Author', social follower counts (IG 150K, YouTube 500K, TikTok 1M). Content sections: Latest YouTube videos (3 thumbnails with titles), Recent blog posts, Podcast episodes. Collaborations: 'As Seen In' logos (Forbes, TechCrunch, etc.). Brand partnerships: 4 featured collab case studies with brand logos and campaign photos. Speaking section: past events, topics, booking inquiry. Media kit download CTA with stats summary. Shop: merchandise or digital products. About: longer bio, achievements, mission statement. Contact for business inquiries form. Bold, modern: dark bg (#0a0a0a), neon accent matching personal brand, white text. Instagram-aesthetic quality.",
    thumbnail: "from-gray-900 to-pink-600",
    tags: ["Personal Brand", "Influencer", "Content Creator", "Blog"],
  },
  {
    id: "travel-agency",
    name: "Travel Agency",
    category: "Business",
    description: "Travel agency with packages, destinations, and booking.",
    prompt: "A travel agency website. Stunning hero carousel (.hero-carousel) with 4 exotic destination photos (seed/tropical-beach, seed/mountain-sunset, seed/european-city, seed/safari-landscape). Search widget: destination, travel dates, travelers, trip type (Beach/Adventure/Cultural/Cruise). Featured packages .grid-3: destination photo, package name ('Bali Paradise 7D/6N'), original price crossed out, sale price, includes (flights, hotel, tours), star rating, 'Book Now'. Popular destinations: cards with dest photo, country, starting from price. Trip types: Beach & Islands, Cultural & Heritage, Adventure & Safari, Cruise & Luxury. Why book with us: price match, 24/7 support, local experts, flexible cancellation. Customer travel stories with vacation photos. Newsletter for deal alerts. Vibrant: ocean blue (#0369a1), sunset orange (#ea580c), white. Aspirational, trustworthy, deal-focused.",
    thumbnail: "from-blue-700 to-orange-600",
    tags: ["Travel", "Agency", "Packages", "Destinations"],
  },

  // ── Miscellaneous Industry (5 more) ──
  {
    id: "pet-grooming",
    name: "Pet Grooming Salon",
    category: "Business",
    description: "Pet grooming with services, pricing, gallery, and online booking.",
    prompt: "A pet grooming salon website. Cute hero with groomed fluffy dog (.hero-image seed/groomed-dog), headline 'Pampered Pups & Pretty Kitties', 'Book Grooming' CTA. Services: Bath & Brush ($35+), Full Grooming ($55+), Puppy's First Groom ($40), Cat Grooming ($65), Nail Trim ($15), Teeth Cleaning ($20). Pricing by size: Small/Medium/Large/XL with prices for each service. Before/after gallery (.image-gallery) of groomed pets. Our groomers: 3 profiles with specialties and certifications. Pet of the month feature. Loyalty program: every 5th groom free. Booking form: pet name, breed, service, preferred date/time, special instructions. Reviews with pet photos. FAQ about preparation, duration, aggressive pet policy. Playful, clean: baby blue (#93c5fd), white, pink accents (#f9a8d4). Adorable but professional.",
    thumbnail: "from-blue-300 to-pink-300",
    tags: ["Pet Grooming", "Salon", "Pets", "Business"],
  },
  {
    id: "photography-studio",
    name: "Photography Studio",
    category: "Business",
    description: "Studio with session types, booking, mini sessions, and print shop.",
    prompt: "A photography studio booking website. Elegant hero with studio portrait (.hero-image seed/studio-portrait/1400/800), studio name, 'Book Your Session'. Session types .grid-3: Family Portraits ($299), Headshots ($199), Newborn ($399), Maternity ($349), Senior Portraits ($249), Event Coverage (custom quote). Each with sample image and what's included (session time, edited photos, online gallery). Mini session calendar: upcoming themed mini sessions (Holiday, Spring Garden, Back to School) with limited spots and booking. Portfolio: filterable gallery by session type. Client experience: what to expect from booking to gallery delivery. Print shop: canvas, albums, gift prints with pricing. Testimonials from families. Studio location with interior photos. Booking form: session type, preferred date, # of people, special requests. Soft, warm palette: blush (#fce7f3), warm gray, gold (#c9a96e). Elegant, premium, personal.",
    thumbnail: "from-pink-200 to-amber-300",
    tags: ["Photography", "Studio", "Portraits", "Booking"],
  },
  {
    id: "moving-company",
    name: "Moving Company",
    category: "Business",
    description: "Moving service with quote calculator, services, and availability.",
    prompt: "A moving company website. Action hero with moving truck (.hero-image seed/moving-truck), headline 'Stress-Free Moving, Guaranteed', instant quote CTA. Moving services: Local Moves, Long Distance, Commercial/Office, Packing Services, Storage Solutions, Piano/Specialty. Instant quote calculator: from zip, to zip, home size (studio/1BR/2BR/3BR/4BR+), move date → estimated cost range. How it works: Get Quote → Schedule → We Pack & Load → Deliver. Why choose us: licensed & insured, no hidden fees, on-time guarantee, damage protection. Service area map. Customer reviews with star ratings and move details. Moving tips blog: 3 articles (packing guide, moving checklist, change of address list). Seasonal promotions banner. Request form: details for exact quote. Bold, reliable: strong blue (#1d4ed8), orange (#ea580c), white. Professional, trustworthy, action-oriented.",
    thumbnail: "from-blue-700 to-orange-600",
    tags: ["Moving", "Service", "Relocation", "Business"],
  },
  {
    id: "car-wash",
    name: "Car Wash & Detailing",
    category: "Business",
    description: "Car wash with packages, mobile service, and membership plans.",
    prompt: "A car wash and detailing website. Hero with gleaming clean car (.hero-image seed/clean-car), headline 'The Ultimate Shine', 'Book Now' CTA. Wash packages: Express ($15), Premium ($25), Supreme ($40), Ultimate Detail ($150) — each listing included services with checkmarks. Comparison table showing all packages side by side. Mobile detailing section: 'We Come to You' with service area and booking. Monthly memberships: Unlimited Express ($29/mo), Unlimited Premium ($49/mo), VIP All-Access ($79/mo). Before/after gallery (.image-gallery) of detailed vehicles. Gift cards section. Customer reviews. Our process: 5 steps with icons. Eco-friendly products and water reclamation section. Location with hours and wait time indicator. Booking form: service, vehicle type, date. Clean, bright: electric blue (#2563eb), white, lime green (#84cc16) for eco messaging. Shiny, premium, fast.",
    thumbnail: "from-blue-600 to-lime-500",
    tags: ["Car Wash", "Detailing", "Auto", "Business"],
  },
  {
    id: "coworking-space",
    name: "Coworking Space",
    category: "Business",
    description: "Coworking with plans, amenities, virtual tour, and community events.",
    prompt: "A coworking space website. Inspiring hero with modern coworking interior (.hero-image seed/coworking-space/1400/800), headline 'Work Better, Together', 'Book a Tour' CTA. Membership plans: Hot Desk ($199/mo), Dedicated Desk ($349/mo), Private Office ($699/mo), Virtual Office ($49/mo) — each with included amenities. Amenities icons: high-speed WiFi, free coffee, meeting rooms, event space, phone booths, bike storage, shower, 24/7 access. Virtual tour gallery (.image-gallery) of spaces: open area, private offices, meeting rooms, kitchen, rooftop. Community: member companies logos, upcoming events (networking, workshops, happy hours), member directory access. Meeting room booking: capacity, hourly rate, AV equipment. Locations if multiple. Testimonials from members about community. Contact for tour booking. Modern, creative: warm white, wood tones (#92400e), teal (#0d9488). Productive, inspiring, community-driven.",
    thumbnail: "from-amber-700 to-teal-500",
    tags: ["Coworking", "Office", "Community", "Workspace"],
  },

  // ── Dashboard & Apps (3 more) ──
  {
    id: "finance-dashboard",
    name: "Personal Finance Dashboard",
    category: "Technology",
    description: "Personal finance app with budget tracking, spending analysis, and goals.",
    prompt: "A personal finance dashboard app. Top bar: app name, month selector, notifications, settings gear. Summary cards: Net Worth ($124,500, +2.3%), Monthly Income ($7,200), Monthly Expenses ($4,850), Savings Rate (32.6%). Budget breakdown: category cards (Housing 35%, Food 15%, Transport 10%, etc.) with progress bars showing spent vs budget. Spending chart: donut chart by category + line chart for monthly trend. Transaction list: date, merchant, category icon, amount (green for income, red for expense), running balance. Goals section: Emergency Fund (72% to $10K), Vacation ($800/$2,000), New Car ($5,400/$15,000) with progress bars. Accounts sidebar: Checking, Savings, Credit Card, Investment with balances. Clean fintech aesthetic: white bg, subtle gray cards, green (#10b981) for positive, red (#ef4444) for negative, blue (#3b82f6) primary. Mint/YNAB-inspired.",
    thumbnail: "from-emerald-600 to-blue-500",
    tags: ["Finance", "Dashboard", "Budget", "App"],
  },
  {
    id: "social-media-dashboard",
    name: "Social Media Dashboard",
    category: "Technology",
    description: "Social analytics with cross-platform metrics, content calendar, and performance.",
    prompt: "A social media analytics dashboard. Sidebar: Dashboard, Content, Calendar, Analytics, Accounts, Settings. Connected accounts row with icons: Instagram, Twitter/X, LinkedIn, TikTok, YouTube — each with follower count. Overview cards: Total Followers (245K, +3.2%), Engagement Rate (4.7%), Impressions (1.2M), Link Clicks (8,400). Platform comparison chart: bar chart showing followers/engagement per platform. Top performing posts: 5 posts with thumbnail, platform icon, engagement metrics, post date. Content calendar: monthly view with colored dots per platform showing scheduled posts. Best posting times heatmap: days × hours grid with engagement intensity. Audience demographics: age, gender, location charts. Quick actions: Schedule Post, Create Campaign, Generate Report. Modern dark theme: #0f172a sidebar, #f8fafc content, platform brand colors for icons. Data-rich, actionable.",
    thumbnail: "from-pink-600 to-violet-600",
    tags: ["Social Media", "Analytics", "Dashboard", "Marketing"],
  },
  {
    id: "fitness-tracker",
    name: "Fitness Tracker App",
    category: "Health",
    description: "Fitness tracking dashboard with workouts, nutrition, and progress.",
    prompt: "A fitness tracking web app. Mobile-first layout with bottom nav: Home, Workouts, Nutrition, Progress, Profile. Home dashboard: today's activity ring (steps 8,432/10,000, calories 1,847/2,200, active mins 45/60), workout streak (14 days), next scheduled workout. Workout section: today's plan (Chest & Triceps), exercise list with sets × reps, timer, rest counter. Workout library: .grid-2 with workout cards (Upper Body, Lower Body, HIIT, Yoga, Running). Nutrition tracker: meals logged with calorie/macro breakdown, water intake (6/8 glasses), macro pie chart. Progress: weight graph over 12 weeks (SVG line chart), body measurements, personal records table. Weekly summary: total workouts, calories burned, distance. Dark athletic theme: near-black (#111827), electric green (#22c55e) for activity, blue (#3b82f6) for hydration. Energetic, motivating, data-driven.",
    thumbnail: "from-green-600 to-blue-600",
    tags: ["Fitness", "Tracker", "Health", "App"],
  },
];

export const TEMPLATE_CATEGORIES = [
  "All",
  "Business",
  "Portfolio",
  "E-Commerce",
  "Blog",
  "Technology",
  "Food & Drink",
  "Health",
  "Events",
  "Real Estate",
  "Entertainment",
  "Nonprofit",
  "Professional",
  "Education",
];
