"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import {
  ArrowLeft,
  Sparkles,
  User,
  LogOut,
  LayoutDashboard,
} from "lucide-react";
import ShowcaseGallery from "@/components/ShowcaseGallery";

export default function ShowcasePage() {
  const [isLoggedIn, setIsLoggedIn] = useState(false);

  useEffect(() => {
    try {
      const u = localStorage.getItem("zoobicon_user");
      if (u) setIsLoggedIn(true);
    } catch { /* ignore */ }
  }, []);

  return (
    <div className="min-h-screen bg-[#050508] text-white">
      {/* Nav */}
      <nav className="fixed top-0 left-0 right-0 z-50 bg-[#050508]/80 backdrop-blur-xl border-b border-white/[0.06]">
        <div className="max-w-7xl mx-auto flex items-center justify-between px-6 h-16">
          <div className="flex items-center gap-4">
            <Link
              href="/"
              className="flex items-center gap-2 text-white/50 hover:text-white/80 transition-colors text-sm"
            >
              <ArrowLeft className="w-4 h-4" />
              Home
            </Link>
            <div className="w-px h-5 bg-white/10" />
            <Link href="/" className="font-bold text-lg tracking-tight">
              Zoobicon
            </Link>
          </div>

          <div className="flex items-center gap-3">
            {isLoggedIn ? (
              <>
                <Link
                  href="/dashboard"
                  className="flex items-center gap-1.5 text-sm text-white/50 hover:text-white/80 transition-colors"
                >
                  <LayoutDashboard className="w-4 h-4" />
                  Dashboard
                </Link>
                <button
                  onClick={() => {
                    localStorage.removeItem("zoobicon_user");
                    setIsLoggedIn(false);
                  }}
                  className="flex items-center gap-1.5 text-sm text-white/50 hover:text-white/80 transition-colors"
                >
                  <LogOut className="w-4 h-4" />
                  Sign out
                </button>
              </>
            ) : (
              <>
                <Link
                  href="/auth/login"
                  className="text-sm text-white/50 hover:text-white/80 transition-colors"
                >
                  Sign in
                </Link>
                <Link
                  href="/builder"
                  className="px-4 py-2 bg-purple-600 hover:bg-purple-500 text-white text-sm font-medium rounded-lg transition-colors"
                >
                  Start Building
                </Link>
              </>
            )}
          </div>
        </div>
      </nav>

      {/* Hero header */}
      <div className="pt-32 pb-8 px-6 text-center">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4" />
            Real AI-Generated Sites
          </div>
          <h1 className="text-5xl sm:text-6xl font-black tracking-tight mb-4">
            The <span className="bg-gradient-to-r from-purple-400 to-violet-400 bg-clip-text text-transparent">Showcase</span>
          </h1>
          <p className="text-lg text-gray-400 max-w-2xl mx-auto">
            Every site below was generated by Zoobicon&apos;s 7-agent AI pipeline from a single prompt.
            No templates. No manual coding. Just AI.
          </p>
        </motion.div>
      </div>

      {/* Gallery */}
      <ShowcaseGallery />

      {/* Footer */}
      <footer className="border-t border-white/[0.06] py-12 px-6 text-center">
        <p className="text-sm text-gray-500 mb-4">
          Want to see your site here? Build something amazing and deploy it.
        </p>
        <Link
          href="/builder"
          className="inline-flex items-center gap-2 px-6 py-3 bg-gradient-to-r from-purple-600 to-violet-600 hover:from-purple-500 hover:to-violet-500 text-white font-semibold rounded-xl transition-all shadow-lg shadow-purple-500/20"
        >
          Open the Builder
          <Sparkles className="w-4 h-4" />
        </Link>
        <div className="mt-8 flex items-center justify-center gap-6 text-xs text-gray-600">
          <Link href="/privacy" className="hover:text-gray-400 transition-colors">Privacy</Link>
          <Link href="/terms" className="hover:text-gray-400 transition-colors">Terms</Link>
          <Link href="/support" className="hover:text-gray-400 transition-colors">Support</Link>
        </div>
      </footer>
    </div>
  );
}
