// ---------------------------------------------------------------------------
// GET /api/domains/drops?tld=com&limit=20[&min_value=500]
//
// Surface domains expiring soon with high predicted value. No registrar ships
// this in real-time search — this is one of the wow features that justifies
// "most advanced domain search on the internet."
//
// ╔═══════════════════════════════════════════════════════════════════════╗
// ║ TODO — LIVE-FEED UPGRADE PATH                                         ║
// ║                                                                       ║
// ║ This route currently returns a STUBBED list generated by Claude, so   ║
// ║ the UI has something real to render while we integrate a paid feed.   ║
// ║ When we commit to a live feed, wire it in at fetchDropsLive() below   ║
// ║ and flip `source: "stub"` → `source: "live"`.                         ║
// ║                                                                       ║
// ║ Recommended providers (in priority order):                            ║
// ║                                                                       ║
// ║ 1. DROPCATCH.COM API (preferred) —                                    ║
// ║      • Env var: DROPCATCH_API_KEY                                     ║
// ║      • Cost: ~$99/mo Pro, $299/mo Enterprise (~2026 pricing)          ║
// ║      • Covers: .com/.net/.org daily drop lists + pending-delete tier  ║
// ║      • Endpoint: https://api.dropcatch.com/v1/expiring                ║
// ║      • Why first: best .com coverage, simple JSON API                 ║
// ║                                                                       ║
// ║ 2. SNAPNAMES API —                                                    ║
// ║      • Env var: SNAPNAMES_API_KEY                                     ║
// ║      • Cost: Revenue-share (free-to-use, cut on catches)              ║
// ║      • Covers: back-order drop list, ~35M+ domains watched            ║
// ║      • Endpoint: https://api.snapnames.com/v2/expiring                ║
// ║      • Why second: zero-fixed-cost hedge                              ║
// ║                                                                       ║
// ║ 3. NAMEJET API —                                                      ║
// ║      • Env var: NAMEJET_API_KEY                                       ║
// ║      • Cost: Auction-fee model                                        ║
// ║      • Covers: pre-release drops from NetSol/Web.com registrars       ║
// ║                                                                       ║
// ║ 4. EXPIREDDOMAINS.NET SCRAPE (last resort) —                          ║
// ║      • Free but ToS-grey; rate-limited; HTML scraping required        ║
// ║      • Only if all 3 above decline or their pricing moves             ║
// ║                                                                       ║
// ║ Estimated monthly cost for Tier 1 launch: $99–$299. Break-even on     ║
// ║ a SINGLE catch at $1k+, which is routine for 4-char .com.             ║
// ╚═══════════════════════════════════════════════════════════════════════╝
// ---------------------------------------------------------------------------

import { NextRequest, NextResponse } from "next/server";
import { callLLMWithFailover } from "@/lib/llm-provider";
import {
  LruCache,
  extractJsonArray,
  splitDomain,
  valueHeuristic,
} from "@/lib/domain-intel";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";
export const maxDuration = 45;

type DropStatus = "grace" | "redemption" | "pendingDelete" | "dropping";

interface DropItem {
  domain: string;
  expires_at: string;
  days_until_drop: number;
  status: DropStatus;
  predicted_value: { low: number; high: number; midpoint: number };
  brandability_score: number;
  reason_surfaced: string;
}

interface DropsResponse {
  tld: string;
  count: number;
  drops: DropItem[];
  source: "stub" | "live";
  notes: string | null;
}

const CACHE = new LruCache<DropsResponse>(200, 10 * 60 * 1000);

const ALLOWED_TLDS = new Set([
  "com",
  "net",
  "org",
  "io",
  "ai",
  "co",
  "app",
  "dev",
  "sh",
  "me",
  "xyz",
  "us",
]);

export async function GET(req: NextRequest) {
  try {
    const tldRaw = (req.nextUrl.searchParams.get("tld") || "com").toLowerCase().replace(/^\./, "");
    const limitRaw = req.nextUrl.searchParams.get("limit");
    const minValueRaw = req.nextUrl.searchParams.get("min_value");

    if (!ALLOWED_TLDS.has(tldRaw)) {
      return NextResponse.json(
        {
          error: `Unsupported TLD "${tldRaw}". Supported: ${Array.from(ALLOWED_TLDS).join(", ")}`,
        },
        { status: 400 },
      );
    }

    const limit = clampInt(limitRaw, 20, 1, 50);
    const minValue = minValueRaw ? clampInt(minValueRaw, 0, 0, 1_000_000) : 0;

    const cacheKey = `${tldRaw}|${limit}|${minValue}`;
    const cached = CACHE.get(cacheKey);
    if (cached) {
      return NextResponse.json({ ...cached, cached: true });
    }

    // ── Live feed hook — plugs in here once a paid provider is wired ──────
    const live = await fetchDropsLive(tldRaw);
    if (live) {
      const filtered = filterAndSort(live, limit, minValue);
      const payload: DropsResponse = {
        tld: tldRaw,
        count: filtered.length,
        drops: filtered,
        source: "live",
        notes: null,
      };
      CACHE.set(cacheKey, payload);
      return NextResponse.json(payload);
    }

    // ── Stub fallback (current default) ───────────────────────────────────
    const drops = await generateStubDrops(tldRaw, limit);
    const filtered = filterAndSort(drops, limit, minValue);

    const payload: DropsResponse = {
      tld: tldRaw,
      count: filtered.length,
      drops: filtered,
      source: "stub",
      notes:
        "Feed is stubbed pending paid drop-catching integration (DropCatch/SnapNames). Upgrade path documented in route comment.",
    };
    CACHE.set(cacheKey, payload);
    return NextResponse.json(payload);
  } catch (err) {
    const msg = err instanceof Error ? err.message : "Internal server error";
    console.error("[domains/drops] Unexpected error:", msg);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

// ---------------------------------------------------------------------------
// Live feed stub — returns null today. When we wire DropCatch/SnapNames,
// flip this to fetch + normalise to DropItem[]. Keeping the hook in place
// means the caller contract never changes.
// ---------------------------------------------------------------------------

async function fetchDropsLive(_tld: string): Promise<DropItem[] | null> {
  // Intentional: no live feed configured yet. See TODO block at top of file.
  if (!process.env.DROPCATCH_API_KEY && !process.env.SNAPNAMES_API_KEY) {
    return null;
  }
  // When a provider is wired:
  //   1. fetch(provider URL, { signal: AbortSignal.timeout(10000) })
  //   2. normalise each row → DropItem (reuse valuation via valueDomainForDrop)
  //   3. return DropItem[]
  // Until then, behave as if no feed exists.
  return null;
}

// ---------------------------------------------------------------------------
// Stub generation — asks Claude Haiku for N plausible-looking expiring names,
// then runs them through the shared valuation heuristic. Deterministic enough
// on a 10-min cache that we don't hammer Anthropic.
// ---------------------------------------------------------------------------

async function generateStubDrops(tld: string, count: number): Promise<DropItem[]> {
  const system =
    "You generate realistic-looking expiring domain lists. Output JSON arrays only, no prose, no markdown.";

  const user = `Generate exactly ${count} realistic expiring .${tld} domain names for a domain-aftermarket surface.

Each name should be:
  • 4-8 characters (SLD only, no TLD)
  • Letters only — no numbers, no hyphens
  • Brandable (pronounceable, memorable)
  • Mix styles: invented coinages, two-root compounds, rare Latin/Greek stems
  • Avoid obvious squatted names (skip: apex, nova, lumen, pulse, forge, atlas, phoenix, echo)

Distribute across drop windows:
  • Roughly 20% dropping in 1-2 days (status: "pendingDelete" or "dropping")
  • Roughly 40% in 8-14 days (status: "redemption")
  • Roughly 40% in 20-30 days (status: "grace")

Output JSON array only. Shape:
[
  { "sld": "vexion", "days": 2, "status": "dropping" },
  { "sld": "lumeris", "days": 12, "status": "redemption" },
  ...
]

Rules:
  • Return exactly ${count} entries.
  • "status" ∈ {"grace","redemption","pendingDelete","dropping"}
  • "days" is a positive integer.
  • No duplicates.
  • No TLD in the sld value.
  • No markdown fences, no commentary. JSON array only.`;

  let raw: Array<{ sld?: unknown; days?: unknown; status?: unknown }> | null = null;
  try {
    const { text } = await callLLMWithFailover({
      model: "claude-haiku-4-5-20251001",
      system,
      userMessage: user,
      maxTokens: 2000,
    });
    raw = extractJsonArray<{ sld?: unknown; days?: unknown; status?: unknown }>(text);
  } catch (err) {
    console.error(
      `[domains/drops] Stub LLM call failed for .${tld}:`,
      err instanceof Error ? err.message : err,
    );
  }

  if (!raw || raw.length === 0) {
    console.warn(
      `[domains/drops] No LLM stub list for .${tld} — returning a tiny deterministic seed so UI still renders.`,
    );
    return DETERMINISTIC_SEED.map((s) => buildDropItem(s.sld, tld, s.days, s.status));
  }

  const out: DropItem[] = [];
  const seen = new Set<string>();
  for (const row of raw) {
    if (!row || typeof row !== "object") continue;
    const sld =
      typeof row.sld === "string"
        ? row.sld.trim().toLowerCase().replace(/[^a-z]/g, "").slice(0, 20)
        : "";
    if (!sld || sld.length < 3) continue;
    if (seen.has(sld)) continue;

    const days = typeof row.days === "number" && Number.isFinite(row.days)
      ? Math.max(1, Math.min(Math.round(row.days), 60))
      : 14;
    const status = normaliseStatus(row.status, days);

    seen.add(sld);
    out.push(buildDropItem(sld, tld, days, status));
  }

  return out;
}

// Last-ditch seed so the endpoint never returns an empty drops array when
// Claude is down AND there's no live feed.
const DETERMINISTIC_SEED: Array<{ sld: string; days: number; status: DropStatus }> = [
  { sld: "veridax", days: 3, status: "dropping" },
  { sld: "octavus", days: 9, status: "redemption" },
  { sld: "sonare", days: 14, status: "redemption" },
  { sld: "calidus", days: 22, status: "grace" },
  { sld: "lumeris", days: 27, status: "grace" },
];

function buildDropItem(sld: string, tld: string, days: number, status: DropStatus): DropItem {
  const domain = `${sld}.${tld}`;
  const h = valueHeuristic(domain);
  const expiresAt = isoDaysFromNow(days);
  const brandability = scoreBrandability(sld, tld, h);
  const reason = buildReasonSurfaced(sld, tld, h, status, days);

  return {
    domain,
    expires_at: expiresAt,
    days_until_drop: days,
    status,
    predicted_value: { low: h.low, high: h.high, midpoint: h.midpoint },
    brandability_score: brandability,
    reason_surfaced: reason,
  };
}

function scoreBrandability(
  sld: string,
  tld: string,
  h: ReturnType<typeof valueHeuristic>,
): number {
  // Brandability 0-100 — anchored off the midpoint valuation but bounded so
  // obscure $200 names don't show as "1/100".
  let score = 40;
  if (sld.length <= 5) score += 20;
  else if (sld.length <= 7) score += 10;
  if (tld === "com") score += 15;
  else if (tld === "ai" || tld === "io") score += 10;
  if (/^[aeiou]/.test(sld) && /[aeiou]$/.test(sld)) score += 5;
  if (h.midpoint >= 1000) score += 10;
  else if (h.midpoint >= 500) score += 5;
  if (sld.includes("-") || /\d/.test(sld)) score -= 15;
  return Math.max(10, Math.min(99, score));
}

function buildReasonSurfaced(
  sld: string,
  tld: string,
  h: ReturnType<typeof valueHeuristic>,
  status: DropStatus,
  days: number,
): string {
  const chunks: string[] = [];
  if (sld.length <= 5) chunks.push(`${sld.length}-char`);
  if (tld === "com") chunks.push(".com");
  else chunks.push(`.${tld}`);
  if (h.midpoint >= 1000) chunks.push("high-value");
  if (status === "pendingDelete" || status === "dropping") {
    chunks.push(`drops in ${days}d`);
  }
  return chunks.join(", ") || `${tld} drop`;
}

// ---------------------------------------------------------------------------
// Utility
// ---------------------------------------------------------------------------

function filterAndSort(drops: DropItem[], limit: number, minValue: number): DropItem[] {
  return drops
    .filter((d) => d.predicted_value.midpoint >= minValue)
    .sort((a, b) => b.predicted_value.midpoint - a.predicted_value.midpoint)
    .slice(0, limit);
}

function clampInt(v: string | null, fallback: number, min: number, max: number): number {
  if (v === null) return fallback;
  const n = Number(v);
  if (!Number.isFinite(n)) return fallback;
  return Math.max(min, Math.min(Math.floor(n), max));
}

function isoDaysFromNow(days: number): string {
  const d = new Date(Date.now() + days * 24 * 60 * 60 * 1000);
  return d.toISOString().slice(0, 10);
}

function normaliseStatus(v: unknown, days: number): DropStatus {
  if (typeof v === "string") {
    const s = v.trim();
    if (s === "grace" || s === "redemption" || s === "pendingDelete" || s === "dropping") {
      return s;
    }
  }
  // Fallback inferred from timing: ICANN grace ~0-30d, redemption ~30-60d,
  // pendingDelete ~last 5d, dropping ~last 2d. Our stub uses a compressed
  // timeline so the mapping below is the practical one for UI sorting.
  if (days <= 2) return "dropping";
  if (days <= 5) return "pendingDelete";
  if (days <= 14) return "redemption";
  return "grace";
}

// Keep splitDomain import live for future live-feed normalisation paths.
void splitDomain;
