import { NextRequest, NextResponse } from "next/server";
import {
  createRepoAndPush,
  pushToExistingRepo,
  getRepoStatus,
  getGitHubUser,
} from "@/lib/github-sync";

/**
 * Read the GitHub token from the HttpOnly cookie set during OAuth.
 * This keeps the raw token out of client-side JavaScript.
 */
function getToken(req: NextRequest): string | null {
  return req.cookies.get("zoobicon_github_token")?.value || null;
}

// ---------------------------------------------------------------------------
// POST — Create a new repo (or push to existing) with all project files
// ---------------------------------------------------------------------------

export async function POST(req: NextRequest) {
  try {
    const token = getToken(req);
    if (!token) {
      return NextResponse.json(
        { error: "Not connected to GitHub. Please connect your GitHub account first." },
        { status: 401 }
      );
    }

    const body = await req.json();
    const {
      files,
      repoName,
      isPrivate = true,
      commitMessage,
      description,
    } = body;

    if (!files || typeof files !== "object" || Object.keys(files).length === 0) {
      return NextResponse.json(
        { error: "No files to push" },
        { status: 400 }
      );
    }

    if (!repoName || typeof repoName !== "string") {
      return NextResponse.json(
        { error: "Repository name is required" },
        { status: 400 }
      );
    }

    // Sanitize repo name for GitHub
    const sanitized = repoName
      .toLowerCase()
      .replace(/[^a-z0-9._-]+/g, "-")
      .replace(/^-|-$/g, "")
      .replace(/\.+/g, ".")
      .slice(0, 100);

    if (!sanitized) {
      return NextResponse.json(
        { error: "Invalid repository name" },
        { status: 400 }
      );
    }

    const result = await createRepoAndPush({
      files,
      repoName: sanitized,
      token,
      isPrivate,
      commitMessage:
        commitMessage || "Initial commit — generated by Zoobicon",
      description,
    });

    return NextResponse.json(result);
  } catch (err) {
    console.error("GitHub sync POST error:", err);
    const message =
      err instanceof Error ? err.message : "Failed to push to GitHub";
    const status = message.includes("Invalid GitHub token") ? 401 : 500;
    return NextResponse.json({ error: message }, { status });
  }
}

// ---------------------------------------------------------------------------
// PUT — Push updated files to an existing repo
// ---------------------------------------------------------------------------

export async function PUT(req: NextRequest) {
  try {
    const token = getToken(req);
    if (!token) {
      return NextResponse.json(
        { error: "Not connected to GitHub. Please connect your GitHub account first." },
        { status: 401 }
      );
    }

    const body = await req.json();
    const { files, owner, repoName, commitMessage, branch = "main" } = body;

    if (!files || typeof files !== "object" || Object.keys(files).length === 0) {
      return NextResponse.json(
        { error: "No files to push" },
        { status: 400 }
      );
    }

    if (!repoName || typeof repoName !== "string") {
      return NextResponse.json(
        { error: "Repository name is required" },
        { status: 400 }
      );
    }

    // Resolve owner from token if not provided
    let resolvedOwner = owner;
    if (!resolvedOwner) {
      const user = await getGitHubUser(token);
      resolvedOwner = user.login;
    }

    const result = await pushToExistingRepo({
      files,
      owner: resolvedOwner,
      repoName,
      commitMessage: commitMessage || "Update from Zoobicon builder",
      token,
      branch,
    });

    return NextResponse.json(result);
  } catch (err) {
    console.error("GitHub sync PUT error:", err);
    const message =
      err instanceof Error ? err.message : "Failed to sync to GitHub";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

// ---------------------------------------------------------------------------
// GET — Check sync status for a repo
// ---------------------------------------------------------------------------

export async function GET(req: NextRequest) {
  try {
    const token = getToken(req);
    if (!token) {
      return NextResponse.json({ connected: false }, { status: 200 });
    }

    const repoName = req.nextUrl.searchParams.get("repoName");
    const owner = req.nextUrl.searchParams.get("owner");

    // If no repoName specified, return the authenticated user info
    if (!repoName) {
      try {
        const user = await getGitHubUser(token);
        return NextResponse.json({ connected: true, user });
      } catch {
        return NextResponse.json({ connected: false });
      }
    }

    // Resolve owner
    let resolvedOwner = owner;
    if (!resolvedOwner) {
      const user = await getGitHubUser(token);
      resolvedOwner = user.login;
    }

    const status = await getRepoStatus({
      owner: resolvedOwner,
      repoName,
      token,
    });

    if (!status) {
      return NextResponse.json({
        exists: false,
        repoName,
        owner: resolvedOwner,
      });
    }

    return NextResponse.json(status);
  } catch (err) {
    console.error("GitHub sync GET error:", err);
    const message =
      err instanceof Error ? err.message : "Failed to check status";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
