/**
 * Gallery, Contact, Blog, E-commerce, Forms, and Misc components
 * for the Zoobicon Component Registry.
 */
import { registerComponent } from "./store";

// ── GALLERY ──

registerComponent({
  id: "gallery-grid",
  name: "Gallery Grid",
  category: "gallery",
  variant: "grid",
  description: "Clean 3x3 image grid with hover overlay",
  tags: ["gallery", "portfolio", "photos", "images", "showcase", "creative"],
  code: `export default function Gallery() {
  const images = [
    { src: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop", title: "Mountain Vista" },
    { src: "https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=400&fit=crop", title: "Starlit Peaks" },
    { src: "https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&h=400&fit=crop", title: "Forest Path" },
    { src: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=400&fit=crop", title: "Sunlit Canopy" },
    { src: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop", title: "Ocean Shore" },
    { src: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=400&fit=crop", title: "Golden Valley" },
  ];
  return (
    <section className="py-24 px-6 bg-white">
      <div className="max-w-7xl mx-auto">
        <h2 className="text-4xl font-bold text-gray-900 text-center mb-4">Our Work</h2>
        <p className="text-xl text-gray-600 text-center mb-16 max-w-2xl mx-auto">A selection of our finest projects and creative endeavors.</p>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {images.map((img, i) => (
            <div key={i} className="group relative overflow-hidden rounded-2xl aspect-[3/2] cursor-pointer">
              <img src={img.src} alt={img.title} className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" />
              <div className="absolute inset-0 bg-black/0 group-hover:bg-black/50 transition-all duration-300 flex items-center justify-center">
                <span className="text-white font-semibold text-lg opacity-0 group-hover:opacity-100 transition-opacity duration-300">{img.title}</span>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}`,
});

// ── CONTACT ──

registerComponent({
  id: "contact-split",
  name: "Contact Split",
  category: "contact",
  variant: "split",
  description: "Company info left, contact form right",
  tags: ["contact", "form", "email", "phone", "address", "reach", "support"],
  code: `export default function Contact() {
  return (
    <section id="contact" className="py-24 px-6 bg-gray-50">
      <div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-16">
        <div>
          <h2 className="text-4xl font-bold text-gray-900 mb-4">Get In Touch</h2>
          <p className="text-lg text-gray-600 mb-8">Have a project in mind? We'd love to hear from you. Send us a message and we'll respond within 24 hours.</p>
          <div className="space-y-6">
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-indigo-100 flex items-center justify-center flex-shrink-0">
                <svg className="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" /></svg>
              </div>
              <div><div className="font-semibold text-gray-900">Email</div><div className="text-gray-600">hello@company.com</div></div>
            </div>
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-indigo-100 flex items-center justify-center flex-shrink-0">
                <svg className="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 5a2 2 0 012-2h3.28a1 1 0 01.948.684l1.498 4.493a1 1 0 01-.502 1.21l-2.257 1.13a11.042 11.042 0 005.516 5.516l1.13-2.257a1 1 0 011.21-.502l4.493 1.498a1 1 0 01.684.949V19a2 2 0 01-2 2h-1C9.716 21 3 14.284 3 6V5z" /></svg>
              </div>
              <div><div className="font-semibold text-gray-900">Phone</div><div className="text-gray-600">+1 (555) 000-0000</div></div>
            </div>
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 rounded-xl bg-indigo-100 flex items-center justify-center flex-shrink-0">
                <svg className="w-5 h-5 text-indigo-600" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 11a3 3 0 11-6 0 3 3 0 016 0z" /></svg>
              </div>
              <div><div className="font-semibold text-gray-900">Office</div><div className="text-gray-600">123 Innovation Drive, San Francisco, CA 94107</div></div>
            </div>
          </div>
        </div>
        <div className="bg-white rounded-2xl p-8 shadow-sm border border-gray-100">
          <form className="space-y-6">
            <div className="grid sm:grid-cols-2 gap-4">
              <div><label className="block text-sm font-medium text-gray-700 mb-1">First Name</label><input type="text" className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent" placeholder="John" /></div>
              <div><label className="block text-sm font-medium text-gray-700 mb-1">Last Name</label><input type="text" className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent" placeholder="Doe" /></div>
            </div>
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Email</label><input type="email" className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent" placeholder="john@company.com" /></div>
            <div><label className="block text-sm font-medium text-gray-700 mb-1">Message</label><textarea rows={4} className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 focus:border-transparent resize-none" placeholder="Tell us about your project..." /></div>
            <button type="submit" className="w-full py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Send Message</button>
          </form>
        </div>
      </div>
    </section>
  );
}`,
});

// ── BLOG ──

registerComponent({
  id: "blog-grid",
  name: "Blog Grid",
  category: "blog",
  variant: "grid",
  description: "Premium 3-column blog with featured post, author avatars, reading time, category badges, and hover animations",
  tags: ["blog", "articles", "news", "posts", "content", "writing", "magazine", "saas", "startup", "tech"],
  code: `export default function Blog() {
  const posts = [
    { img: "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&h=500&fit=crop", cat: "Engineering", catColor: "indigo", title: "Building Scalable Systems with Modern Architecture", excerpt: "How we redesigned our infrastructure to handle 10x traffic growth while cutting latency by 60%.", date: "Mar 15, 2026", read: "5 min", author: "Sarah Chen", role: "Staff Engineer" },
    { img: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=500&fit=crop", cat: "Product", catColor: "emerald", title: "Introducing Our New AI-Powered Dashboard", excerpt: "A deep dive into the intelligent features that help teams make better decisions, faster.", date: "Mar 12, 2026", read: "4 min", author: "Marcus Rivera", role: "Product Lead" },
    { img: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800&h=500&fit=crop", cat: "Culture", catColor: "amber", title: "How We Built a Remote-First Culture That Actually Works", excerpt: "Practical lessons from scaling a distributed team across 12 time zones without losing connection.", date: "Mar 8, 2026", read: "6 min", author: "Priya Sharma", role: "People Ops" },
  ];
  const colorMap = { indigo: "text-indigo-600 bg-indigo-50", emerald: "text-emerald-600 bg-emerald-50", amber: "text-amber-600 bg-amber-50" };
  return (
    <section className="py-24 px-6 bg-white">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-16">
          <div>
            <p className="text-sm font-semibold text-indigo-600 uppercase tracking-widest mb-3">From the Blog</p>
            <h2 className="text-4xl font-bold text-gray-900">Insights & updates</h2>
          </div>
          <a href="#" className="text-sm font-semibold text-indigo-600 hover:text-indigo-800 transition-colors inline-flex items-center gap-1.5 group">
            View all articles
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" className="group-hover:translate-x-1 transition-transform"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
          </a>
        </div>
        <div className="grid md:grid-cols-3 gap-8">
          {posts.map((p, i) => (
            <article key={i} className="group cursor-pointer">
              <div className="overflow-hidden rounded-2xl mb-5 relative">
                <img src={p.img} alt={p.title} className="w-full h-56 object-cover transition-transform duration-700 group-hover:scale-110" />
                <div className="absolute inset-0 bg-gradient-to-t from-black/20 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />
              </div>
              <div className="flex items-center gap-3 mb-3">
                <span className={\`text-xs font-semibold px-2.5 py-1 rounded-full \${colorMap[p.catColor]}\`}>{p.cat}</span>
                <span className="text-xs text-gray-400">{p.read} read</span>
              </div>
              <h3 className="text-xl font-semibold text-gray-900 group-hover:text-indigo-600 transition-colors mb-2 leading-snug">{p.title}</h3>
              <p className="text-gray-500 leading-relaxed text-sm mb-4">{p.excerpt}</p>
              <div className="flex items-center gap-3 pt-4 border-t border-gray-100">
                <div className="w-9 h-9 rounded-full bg-gradient-to-br from-gray-200 to-gray-300 flex items-center justify-center text-xs font-bold text-gray-600">{p.author.split(" ").map(n => n[0]).join("")}</div>
                <div>
                  <p className="text-sm font-medium text-gray-900">{p.author}</p>
                  <p className="text-xs text-gray-400">{p.role} · {p.date}</p>
                </div>
              </div>
            </article>
          ))}
        </div>
      </div>
    </section>
  );
}`,
});

// ── E-COMMERCE ──

registerComponent({
  id: "ecommerce-product-grid",
  name: "Product Grid",
  category: "ecommerce",
  variant: "product-grid",
  description: "Premium product cards with star ratings, reviews count, wishlist toggle, quick-add, color variants, and sale pricing",
  tags: ["ecommerce", "shop", "store", "products", "buy", "cart", "retail", "fashion", "luxury"],
  code: `export default function Ecommerce() {
  const [wishlist, setWishlist] = React.useState({});
  const products = [
    { img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop", name: "Minimal Watch", brand: "Chronos", price: 249, origPrice: null, badge: "New", rating: 4.9, reviews: 128, colors: ["#0f2148", "#e2e8f0", "#92400e"] },
    { img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&h=600&fit=crop", name: "Pro Headphones", brand: "SoundCraft", price: 149, origPrice: 179, badge: "Best Seller", rating: 4.8, reviews: 342, colors: ["#000", "#fff", "#dc2626"] },
    { img: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&h=600&fit=crop", name: "Sport Sneakers", brand: "Velocity", price: 129, origPrice: null, badge: null, rating: 4.7, reviews: 89, colors: ["#1e3a5f", "#fff", "#059669"] },
    { img: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=600&h=600&fit=crop", name: "Classic Sunglasses", brand: "Optica", price: 69, origPrice: 89, badge: "Sale", rating: 4.6, reviews: 215, colors: ["#000", "#92400e", "#1e3a5f"] },
  ];
  const badgeColors = { "New": "bg-indigo-600", "Best Seller": "bg-emerald-600", "Sale": "bg-rose-600" };
  return (
    <section className="py-24 px-6 bg-gray-50">
      <div className="max-w-7xl mx-auto">
        <div className="flex flex-col md:flex-row md:items-end md:justify-between gap-4 mb-16">
          <div>
            <p className="text-sm font-semibold text-gray-500 uppercase tracking-widest mb-3">Shop</p>
            <h2 className="text-4xl font-bold text-gray-900">Featured Products</h2>
          </div>
          <div className="flex gap-2">
            {["All", "New Arrivals", "Best Sellers", "Sale"].map(f => (
              <button key={f} className={\`px-4 py-2 text-sm font-medium rounded-full transition-colors \${f === "All" ? "bg-gray-900 text-white" : "bg-white text-gray-600 hover:bg-gray-100 border border-gray-200"}\`}>{f}</button>
            ))}
          </div>
        </div>
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {products.map((p, i) => (
            <div key={i} className="group bg-white rounded-2xl overflow-hidden border border-gray-100 hover:border-gray-200 hover:shadow-xl transition-all duration-300">
              <div className="relative overflow-hidden bg-gray-100">
                <img src={p.img} alt={p.name} className="w-full aspect-square object-cover transition-transform duration-700 group-hover:scale-110" />
                {p.badge && <span className={\`absolute top-3 left-3 text-[11px] font-semibold text-white px-2.5 py-1 rounded-full \${badgeColors[p.badge] || "bg-gray-900"}\`}>{p.badge}</span>}
                <button onClick={() => setWishlist(prev => ({...prev, [i]: !prev[i]}))} className="absolute top-3 right-3 w-9 h-9 rounded-full bg-white/90 backdrop-blur-sm flex items-center justify-center shadow-sm hover:bg-white transition-colors">
                  <svg width="16" height="16" viewBox="0 0 24 24" fill={wishlist[i] ? "#ef4444" : "none"} stroke={wishlist[i] ? "#ef4444" : "#6b7280"} strokeWidth="2" strokeLinecap="round"><path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/></svg>
                </button>
                <div className="absolute bottom-0 left-0 right-0 p-3 bg-gradient-to-t from-black/50 to-transparent translate-y-full group-hover:translate-y-0 transition-transform duration-300">
                  <button className="w-full py-2.5 bg-white text-gray-900 text-sm font-semibold rounded-lg hover:bg-gray-100 transition-colors">Quick Add</button>
                </div>
              </div>
              <div className="p-5">
                <p className="text-xs text-gray-400 font-medium uppercase tracking-wider mb-1">{p.brand}</p>
                <h3 className="font-semibold text-gray-900 mb-2">{p.name}</h3>
                <div className="flex items-center gap-1.5 mb-3">
                  <div className="flex">{[...Array(5)].map((_, s) => (<svg key={s} width="14" height="14" viewBox="0 0 24 24" fill={s < Math.floor(p.rating) ? "#f59e0b" : "#e5e7eb"}><path d="M12 2l3.09 6.26L22 9.27l-5 4.87 1.18 6.88L12 17.77l-6.18 3.25L7 14.14 2 9.27l6.91-1.01L12 2z"/></svg>))}</div>
                  <span className="text-xs font-medium text-gray-900">{p.rating}</span>
                  <span className="text-xs text-gray-400">({p.reviews})</span>
                </div>
                <div className="flex items-center gap-3 mb-3">
                  <div className="flex gap-1.5">{p.colors.map(c => (<span key={c} className="w-4 h-4 rounded-full border border-gray-200 cursor-pointer hover:scale-125 transition-transform" style={{ backgroundColor: c }} />))}</div>
                </div>
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="text-lg font-bold text-gray-900">\${p.price}</span>
                    {p.origPrice && <span className="text-sm text-gray-400 line-through">\${p.origPrice}</span>}
                    {p.origPrice && <span className="text-xs font-semibold text-rose-600">-{Math.round((1 - p.price / p.origPrice) * 100)}%</span>}
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}`,
});

// ── MISC: LOGOS ──

registerComponent({
  id: "misc-logos",
  name: "Partner Logos",
  category: "misc",
  variant: "logos",
  description: "Partner/client logo strip with hover effects",
  tags: ["logos", "partners", "clients", "trusted", "companies", "brands", "social proof"],
  code: `export default function Misc() {
  const logos = ["Acme Corp", "TechFlow", "Innovate", "CloudBase", "DataPrime", "NexGen"];
  return (
    <section className="py-16 px-6 bg-white border-y border-gray-100">
      <div className="max-w-7xl mx-auto">
        <p className="text-center text-sm font-medium text-gray-400 mb-8 uppercase tracking-wider">Trusted by innovative companies worldwide</p>
        <div className="flex flex-wrap items-center justify-center gap-12">
          {logos.map((name, i) => (
            <span key={i} className="text-2xl font-bold text-gray-300 hover:text-gray-500 transition-colors cursor-default">{name}</span>
          ))}
        </div>
      </div>
    </section>
  );
}`,
});

// ── GALLERY: Masonry ──
registerComponent({ id: "gallery-masonry", name: "Gallery Masonry", category: "gallery", variant: "masonry", description: "Pinterest-style masonry layout", tags: ["gallery", "masonry", "pinterest", "portfolio", "creative", "photos"], code: `export default function Gallery() { const images=[{src:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=800&fit=crop",h:"h-80"},{src:"https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=400&fit=crop",h:"h-52"},{src:"https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&h=600&fit=crop",h:"h-64"},{src:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=400&fit=crop",h:"h-52"},{src:"https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=800&fit=crop",h:"h-80"},{src:"https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=500&fit=crop",h:"h-56"}]; return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">Gallery</h2><div className="columns-1 md:columns-2 lg:columns-3 gap-4">{images.map((img,i)=>(<div key={i} className="mb-4 break-inside-avoid group overflow-hidden rounded-xl cursor-pointer"><img src={img.src} alt="" className={\`w-full \${img.h} object-cover transition-transform duration-500 group-hover:scale-105\`} /></div>))}</div></div></section>); }` });

// ── GALLERY: Carousel ──
registerComponent({ id: "gallery-carousel", name: "Gallery Carousel", category: "gallery", variant: "carousel", description: "Horizontal scrolling carousel", tags: ["gallery", "carousel", "slider", "scroll", "showcase"], code: `export default function Gallery() { const images=["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=500&fit=crop","https://images.unsplash.com/photo-1519681393784-d120267933ba?w=800&h=500&fit=crop","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=800&h=500&fit=crop","https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&h=500&fit=crop","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=500&fit=crop"]; return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">Our Portfolio</h2><div className="flex gap-4 overflow-x-auto pb-4 snap-x snap-mandatory scrollbar-hide">{images.map((src,i)=>(<div key={i} className="flex-shrink-0 w-80 snap-center"><img src={src} alt="" className="w-full h-56 object-cover rounded-2xl hover:scale-[1.02] transition-transform" /></div>))}</div></div></section>); }` });

// ── CONTACT: Simple ──
registerComponent({ id: "contact-simple", name: "Contact Simple", category: "contact", variant: "simple", description: "Centered form with minimal fields", tags: ["contact", "form", "simple", "minimal", "email"], code: `export default function Contact() { return (<section className="py-24 px-6 bg-white"><div className="max-w-lg mx-auto text-center"><h2 className="text-4xl font-bold text-gray-900 mb-4">Contact Us</h2><p className="text-lg text-gray-600 mb-8">Drop us a line and we'll get back to you within 24 hours.</p><form className="space-y-4 text-left"><input type="text" placeholder="Your name" className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500" /><input type="email" placeholder="Your email" className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500" /><textarea rows={4} placeholder="Your message" className="w-full px-4 py-3 border border-gray-200 rounded-xl focus:ring-2 focus:ring-indigo-500 resize-none" /><button type="submit" className="w-full py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Send Message</button></form></div></section>); }` });

// ── BLOG: Featured ──
registerComponent({ id: "blog-featured", name: "Blog Featured", category: "blog", variant: "featured", description: "One large featured + 3 small articles", tags: ["blog", "featured", "articles", "news", "editorial"], code: `export default function Blog() { return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 mb-16">Latest Articles</h2><div className="grid lg:grid-cols-2 gap-8"><div className="group cursor-pointer"><img src="https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=800&h=500&fit=crop" alt="" className="w-full h-72 object-cover rounded-2xl mb-4 group-hover:scale-[1.02] transition-transform" /><span className="text-sm text-indigo-600 font-semibold">Featured</span><h3 className="text-2xl font-bold text-gray-900 mt-1 group-hover:text-indigo-600 transition-colors">The Future of AI-Powered Development</h3><p className="text-gray-600 mt-2">How artificial intelligence is reshaping the way we build software.</p></div><div className="space-y-6">{[{img:"https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=200&h=150&fit=crop",title:"Understanding Modern Architecture Patterns",cat:"Engineering"},{img:"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=200&h=150&fit=crop",title:"Building Remote Teams That Actually Work",cat:"Culture"},{img:"https://images.unsplash.com/photo-1551434678-e076c223a692?w=200&h=150&fit=crop",title:"From MVP to Scale: A Practical Guide",cat:"Product"}].map((p,i)=>(<div key={i} className="flex gap-4 group cursor-pointer"><img src={p.img} alt="" className="w-24 h-20 object-cover rounded-xl flex-shrink-0" /><div><span className="text-xs text-indigo-600 font-semibold">{p.cat}</span><h4 className="font-semibold text-gray-900 group-hover:text-indigo-600 transition-colors">{p.title}</h4></div></div>))}</div></div></div></section>); }` });

// ── ECOMMERCE: Categories ──
registerComponent({ id: "ecommerce-categories", name: "E-Commerce Categories", category: "ecommerce", variant: "categories", description: "Category cards with images", tags: ["ecommerce", "categories", "shop", "browse", "collections"], code: `export default function Ecommerce() { const cats=[{name:"Electronics",img:"https://images.unsplash.com/photo-1468495244123-6c6c332eeece?w=400&h=300&fit=crop",count:"234 items"},{name:"Fashion",img:"https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop",count:"567 items"},{name:"Home & Living",img:"https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=400&h=300&fit=crop",count:"189 items"},{name:"Sports",img:"https://images.unsplash.com/photo-1461896836934-bd45ba8c3e7e?w=400&h=300&fit=crop",count:"312 items"}]; return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">Shop by Category</h2><div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6">{cats.map((c,i)=>(<div key={i} className="group relative overflow-hidden rounded-2xl cursor-pointer"><img src={c.img} alt={c.name} className="w-full h-64 object-cover transition-transform duration-500 group-hover:scale-110" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent" /><div className="absolute bottom-4 left-4"><h3 className="text-xl font-bold text-white">{c.name}</h3><p className="text-sm text-white/70">{c.count}</p></div></div>))}</div></div></section>); }` });

// ── FORM: Waitlist ──
registerComponent({ id: "form-waitlist", name: "Waitlist Form", category: "forms", variant: "waitlist", description: "Email capture with counter", tags: ["waitlist", "early access", "signup", "launch", "beta"], code: `export default function Forms() { return (<section className="py-24 px-6 bg-gradient-to-br from-indigo-600 to-purple-700"><div className="max-w-xl mx-auto text-center"><span className="inline-block text-sm font-semibold text-indigo-200 bg-white/10 px-4 py-1.5 rounded-full mb-6">Early Access</span><h2 className="text-4xl font-bold text-white mb-4">Join the Waitlist</h2><p className="text-lg text-indigo-200 mb-8">Be among the first to try our revolutionary platform. Limited spots available.</p><div className="flex gap-3 max-w-md mx-auto mb-6"><input type="email" placeholder="Enter your email" className="flex-1 px-5 py-4 rounded-xl text-gray-900" /><button className="px-8 py-4 bg-white text-indigo-600 font-semibold rounded-xl hover:bg-indigo-50 transition-colors">Join</button></div><p className="text-indigo-200 text-sm">🎉 2,847 people already joined</p></div></section>); }` });

// ── MISC: Process Steps ──
registerComponent({ id: "misc-process", name: "Process Steps", category: "misc", variant: "process", description: "Numbered process steps", tags: ["process", "steps", "how it works", "workflow", "methodology"], code: `export default function Misc() { const steps=[{n:"01",title:"Discover",desc:"We learn about your business, goals, and target audience through in-depth research."},{n:"02",title:"Design",desc:"Our team creates wireframes and prototypes that bring your vision to life."},{n:"03",title:"Develop",desc:"We build your solution using modern technology and best practices."},{n:"04",title:"Deploy",desc:"Launch to production with monitoring, analytics, and ongoing support."}]; return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">How It Works</h2><div className="grid md:grid-cols-4 gap-8">{steps.map((s,i)=>(<div key={i} className="text-center group"><div className="text-5xl font-black text-indigo-100 group-hover:text-indigo-200 transition-colors mb-4">{s.n}</div><h3 className="text-xl font-semibold text-gray-900 mb-2">{s.title}</h3><p className="text-gray-600">{s.desc}</p></div>))}</div></div></section>); }` });

// ── MISC: Comparison ──
registerComponent({ id: "misc-comparison", name: "Comparison", category: "misc", variant: "comparison", description: "Without Us vs With Us comparison", tags: ["comparison", "before after", "vs", "benefits", "upgrade"], code: `export default function Misc() { return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-5xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">See the Difference</h2><div className="grid md:grid-cols-2 gap-8"><div className="bg-white rounded-2xl p-8 border border-red-100"><h3 className="text-xl font-semibold text-red-600 mb-6">Without Us ❌</h3><ul className="space-y-3">{["Weeks of development time","Inconsistent design quality","No built-in SEO optimization","Manual deployment process","Limited scalability"].map((t,i)=>(<li key={i} className="flex items-center gap-2 text-gray-600"><span className="text-red-400">✕</span>{t}</li>))}</ul></div><div className="bg-white rounded-2xl p-8 border border-emerald-100 ring-2 ring-emerald-200"><h3 className="text-xl font-semibold text-emerald-600 mb-6">With Us ✓</h3><ul className="space-y-3">{["Ready in under 60 seconds","Agency-quality design every time","SEO optimized by default","One-click deployment","Infinite scalability built-in"].map((t,i)=>(<li key={i} className="flex items-center gap-2 text-gray-600"><span className="text-emerald-500">✓</span>{t}</li>))}</ul></div></div></div></section>); }` });

// ── MISC: Video Embed ──
registerComponent({ id: "misc-video", name: "Video Embed", category: "misc", variant: "video", description: "Video thumbnail with play button", tags: ["video", "demo", "tutorial", "watch", "play", "youtube"], code: `export default function Misc() { return (<section className="py-24 px-6 bg-white"><div className="max-w-4xl mx-auto text-center"><h2 className="text-4xl font-bold text-gray-900 mb-4">See It in Action</h2><p className="text-xl text-gray-600 mb-12">Watch how teams are building 10x faster with our platform.</p><div className="relative group cursor-pointer rounded-2xl overflow-hidden shadow-2xl"><img src="https://images.unsplash.com/photo-1551434678-e076c223a692?w=1200&h=675&fit=crop" alt="Video thumbnail" className="w-full aspect-video object-cover" /><div className="absolute inset-0 bg-black/30 group-hover:bg-black/40 transition-colors flex items-center justify-center"><div className="w-20 h-20 rounded-full bg-white/90 flex items-center justify-center group-hover:scale-110 transition-transform shadow-lg"><svg className="w-8 h-8 text-indigo-600 ml-1" fill="currentColor" viewBox="0 0 24 24"><path d="M8 5v14l11-7z"/></svg></div></div><div className="absolute bottom-4 right-4 bg-black/60 text-white text-sm px-3 py-1 rounded-full">2:34</div></div></div></section>); }` });

// ── MISC: Countdown ──
registerComponent({ id: "misc-countdown", name: "Countdown Timer", category: "misc", variant: "countdown", description: "Launch countdown with email signup", tags: ["countdown", "launch", "timer", "coming soon", "prelaunch"], code: `export default function Misc() { const units=[{val:"12",label:"Days"},{val:"08",label:"Hours"},{val:"45",label:"Minutes"},{val:"23",label:"Seconds"}]; return (<section className="py-24 px-6 bg-gray-900"><div className="max-w-3xl mx-auto text-center"><span className="inline-block text-sm font-semibold text-indigo-300 bg-indigo-500/20 px-4 py-1.5 rounded-full mb-6">Coming Soon</span><h2 className="text-4xl md:text-5xl font-bold text-white mb-8">Something Big Is Coming</h2><div className="flex justify-center gap-4 mb-12">{units.map((u,i)=>(<div key={i} className="bg-gray-800 rounded-2xl p-6 w-24"><div className="text-3xl font-bold text-white">{u.val}</div><div className="text-sm text-gray-400 mt-1">{u.label}</div></div>))}</div><div className="flex gap-3 max-w-md mx-auto"><input type="email" placeholder="Get notified" className="flex-1 px-5 py-3 rounded-xl bg-gray-800 border border-gray-700 text-white placeholder-gray-500" /><button className="px-6 py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Notify Me</button></div></div></section>); }` });

// ── MISC: Integrations ──
registerComponent({ id: "misc-integrations", name: "Integrations Grid", category: "misc", variant: "integrations", description: "Works with tool icons grid", tags: ["integrations", "tools", "connect", "api", "plugins", "ecosystem"], code: `export default function Misc() { const tools=["Slack","GitHub","Figma","Notion","Stripe","Zapier","HubSpot","Jira","Linear","Discord","Vercel","AWS"]; return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-4xl mx-auto text-center"><h2 className="text-4xl font-bold text-gray-900 mb-4">Works With Your Stack</h2><p className="text-xl text-gray-600 mb-16">Seamlessly integrates with the tools you already use.</p><div className="grid grid-cols-3 md:grid-cols-4 lg:grid-cols-6 gap-4">{tools.map((t,i)=>(<div key={i} className="bg-white rounded-xl p-4 border border-gray-100 hover:shadow-md hover:border-indigo-200 transition-all cursor-pointer flex items-center justify-center"><span className="text-sm font-semibold text-gray-700">{t}</span></div>))}</div></div></section>); }` });

// ── FORM: Signup ──
registerComponent({ id: "form-signup", name: "Signup Form", category: "forms", variant: "signup", description: "Email + password signup with social login", tags: ["signup", "register", "create account", "auth", "login"], code: `export default function Forms() { return (<section className="py-24 px-6 bg-white"><div className="max-w-md mx-auto"><h2 className="text-3xl font-bold text-gray-900 text-center mb-2">Create your account</h2><p className="text-gray-600 text-center mb-8">Start building in 60 seconds. No credit card required.</p><div className="space-y-3 mb-6"><button className="w-full py-3 border border-gray-200 rounded-xl font-medium text-gray-700 hover:bg-gray-50 transition-colors flex items-center justify-center gap-2">Continue with Google</button><button className="w-full py-3 border border-gray-200 rounded-xl font-medium text-gray-700 hover:bg-gray-50 transition-colors flex items-center justify-center gap-2">Continue with GitHub</button></div><div className="flex items-center gap-3 mb-6"><div className="flex-1 h-px bg-gray-200" /><span className="text-sm text-gray-400">or</span><div className="flex-1 h-px bg-gray-200" /></div><form className="space-y-4"><input type="text" placeholder="Full name" className="w-full px-4 py-3 border border-gray-200 rounded-xl" /><input type="email" placeholder="Email address" className="w-full px-4 py-3 border border-gray-200 rounded-xl" /><input type="password" placeholder="Password" className="w-full px-4 py-3 border border-gray-200 rounded-xl" /><button type="submit" className="w-full py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Create Account</button></form><p className="text-sm text-gray-400 text-center mt-4">Already have an account? <a href="#" className="text-indigo-600 hover:underline">Sign in</a></p></div></section>); }` });

// ── ECOMMERCE: Featured Product ──
registerComponent({ id: "ecommerce-featured", name: "Featured Product", category: "ecommerce", variant: "featured", description: "Hero product with details", tags: ["ecommerce", "product", "featured", "hero", "detail", "buy"], code: `export default function Ecommerce() { return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-16 items-center"><div><img src="https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&h=600&fit=crop" alt="Product" className="w-full rounded-2xl shadow-lg" /></div><div><span className="text-sm font-semibold text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full">New Release</span><h2 className="text-4xl font-bold text-gray-900 mt-4 mb-4">Minimal Classic Watch</h2><div className="flex items-center gap-2 mb-4"><div className="flex text-amber-400">{"★★★★★".split("").map((s,i)=>(<span key={i}>{s}</span>))}</div><span className="text-sm text-gray-500">(128 reviews)</span></div><p className="text-lg text-gray-600 mb-6">Precision craftsmanship meets minimal design. Swiss movement, sapphire crystal, genuine leather strap. Built to last a lifetime.</p><div className="text-3xl font-bold text-gray-900 mb-6">$249 <span className="text-lg text-gray-400 line-through ml-2">$349</span></div><div className="flex gap-4"><button className="flex-1 py-3 bg-gray-900 text-white font-semibold rounded-xl hover:bg-gray-800 transition-colors">Add to Cart</button><button className="px-6 py-3 border border-gray-200 rounded-xl hover:bg-gray-50 transition-colors">♡</button></div></div></div></section>); }` });

// ── GALLERY: Lightbox ──
registerComponent({ id: "gallery-lightbox", name: "Gallery Lightbox", category: "gallery", variant: "lightbox", description: "Grid with view button overlay", tags: ["gallery", "lightbox", "portfolio", "view", "fullscreen"], code: `export default function Gallery() { const imgs=["https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1519681393784-d120267933ba?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1470071459604-3b5ec3a7fe05?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1472214103451-9374bd1c798e?w=600&h=400&fit=crop","https://images.unsplash.com/photo-1465056836900-8f1e940f2114?w=600&h=400&fit=crop"]; return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">Portfolio</h2><div className="grid grid-cols-2 lg:grid-cols-3 gap-4">{imgs.map((src,i)=>(<div key={i} className="group relative overflow-hidden rounded-xl aspect-[4/3] cursor-pointer"><img src={src} alt="" className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-110" /><div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 transition-all flex items-center justify-center"><button className="opacity-0 group-hover:opacity-100 transition-opacity px-4 py-2 bg-white text-gray-900 text-sm font-medium rounded-lg">View</button></div></div>))}</div></div></section>); }` });

// ── CONTACT: Form + Map ──
registerComponent({ id: "contact-form-map", name: "Contact Form Map", category: "contact", variant: "form-map", description: "Form left, map placeholder right", tags: ["contact", "form", "map", "location", "directions"], code: `export default function Contact() { return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-12"><div><h2 className="text-4xl font-bold text-gray-900 mb-4">Visit Us</h2><p className="text-lg text-gray-600 mb-8">Our doors are always open. Stop by or send us a message.</p><form className="space-y-4"><div className="grid sm:grid-cols-2 gap-4"><input type="text" placeholder="Name" className="px-4 py-3 border border-gray-200 rounded-xl" /><input type="email" placeholder="Email" className="px-4 py-3 border border-gray-200 rounded-xl" /></div><input type="text" placeholder="Subject" className="w-full px-4 py-3 border border-gray-200 rounded-xl" /><textarea rows={4} placeholder="Message" className="w-full px-4 py-3 border border-gray-200 rounded-xl resize-none" /><button className="px-8 py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Send</button></form></div><div className="bg-gray-100 rounded-2xl flex items-center justify-center min-h-[400px]"><div className="text-center text-gray-400"><svg className="w-12 h-12 mx-auto mb-2" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M17.657 16.657L13.414 20.9a1.998 1.998 0 01-2.827 0l-4.244-4.243a8 8 0 1111.314 0z" /></svg><p className="text-sm">Map placeholder</p><p className="text-xs mt-1">123 Innovation Dr, San Francisco</p></div></div></div></section>); }` });

// ── CONTACT: Chat ──
registerComponent({ id: "contact-chat", name: "Contact Chat", category: "contact", variant: "chat", description: "Chat-style interface", tags: ["contact", "chat", "support", "help", "message", "live"], code: `export default function Contact() { return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-lg mx-auto"><div className="bg-white rounded-2xl shadow-lg overflow-hidden border border-gray-100"><div className="bg-indigo-600 px-6 py-4"><h3 className="text-white font-semibold">Chat with us</h3><p className="text-indigo-200 text-sm">We typically reply within minutes</p></div><div className="p-6 space-y-4 min-h-[300px]"><div className="flex gap-3"><div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center text-sm">🤖</div><div className="bg-gray-100 rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[80%]"><p className="text-sm text-gray-700">Hi there! 👋 How can we help you today?</p></div></div><div className="flex gap-3 justify-end"><div className="bg-indigo-600 text-white rounded-2xl rounded-tr-sm px-4 py-2.5 max-w-[80%]"><p className="text-sm">I'd like to learn more about your pricing plans</p></div></div><div className="flex gap-3"><div className="w-8 h-8 rounded-full bg-indigo-100 flex items-center justify-center text-sm">🤖</div><div className="bg-gray-100 rounded-2xl rounded-tl-sm px-4 py-2.5 max-w-[80%]"><p className="text-sm text-gray-700">Great question! We have three plans starting at $0/month. Would you like me to walk you through them?</p></div></div></div><div className="border-t border-gray-100 p-4 flex gap-2"><input type="text" placeholder="Type a message..." className="flex-1 px-4 py-2.5 border border-gray-200 rounded-xl text-sm" /><button className="px-4 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-medium hover:bg-indigo-700">Send</button></div></div></div></section>); }` });

// ── BLOG: Minimal ──
registerComponent({ id: "blog-minimal", name: "Blog Minimal", category: "blog", variant: "minimal", description: "Simple list with dates", tags: ["blog", "minimal", "list", "articles", "simple", "clean"], code: `export default function Blog() { const posts=[{date:"Mar 25",title:"The Future of AI-Powered Development",read:"5 min",tag:"AI"},{date:"Mar 22",title:"Why We Switched to React Server Components",read:"4 min",tag:"Engineering"},{date:"Mar 18",title:"Scaling from 0 to 10,000 Users in 30 Days",read:"7 min",tag:"Growth"},{date:"Mar 14",title:"Design Systems That Actually Scale",read:"3 min",tag:"Design"},{date:"Mar 10",title:"The Case for TypeScript in 2026",read:"6 min",tag:"Development"}]; return (<section className="py-24 px-6 bg-white"><div className="max-w-3xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 mb-12">Blog</h2><div className="divide-y divide-gray-100">{posts.map((p,i)=>(<a key={i} href="#" className="flex items-center justify-between py-5 group"><div className="flex items-center gap-4"><span className="text-sm text-gray-400 w-16 flex-shrink-0">{p.date}</span><h3 className="font-medium text-gray-900 group-hover:text-indigo-600 transition-colors">{p.title}</h3></div><div className="flex items-center gap-3 flex-shrink-0"><span className="text-xs text-indigo-600 bg-indigo-50 px-2 py-1 rounded-full hidden sm:block">{p.tag}</span><span className="text-xs text-gray-400">{p.read}</span></div></a>))}</div></div></section>); }` });

// ── BLOG: Magazine ──
registerComponent({ id: "blog-magazine", name: "Blog Magazine", category: "blog", variant: "magazine", description: "Magazine layout with mixed sizes", tags: ["blog", "magazine", "editorial", "news", "media"], code: `export default function Blog() { return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 mb-16">Latest News</h2><div className="grid lg:grid-cols-3 gap-6"><div className="lg:col-span-2 group cursor-pointer"><img src="https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?w=900&h=500&fit=crop" alt="" className="w-full h-72 object-cover rounded-2xl mb-4" /><span className="text-sm text-indigo-600 font-semibold">Featured</span><h3 className="text-2xl font-bold text-gray-900 mt-1 group-hover:text-indigo-600 transition-colors">The Complete Guide to AI-First Product Development</h3><p className="text-gray-600 mt-2">How the best teams are leveraging AI at every stage of the product lifecycle.</p></div><div className="space-y-6">{[{img:"https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=400&h=250&fit=crop",title:"Q1 2026 Product Roadmap Update",cat:"Product"},{img:"https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=250&fit=crop",title:"Meet Our New Head of Engineering",cat:"Team"},{img:"https://images.unsplash.com/photo-1551434678-e076c223a692?w=400&h=250&fit=crop",title:"How We Achieved 99.99% Uptime",cat:"Engineering"}].map((p,i)=>(<div key={i} className="group cursor-pointer"><img src={p.img} alt="" className="w-full h-36 object-cover rounded-xl mb-2" /><span className="text-xs text-indigo-600 font-semibold">{p.cat}</span><h4 className="font-semibold text-gray-900 group-hover:text-indigo-600 transition-colors mt-1">{p.title}</h4></div>))}</div></div></div></section>); }` });

// ── ECOMMERCE: Deals ──
registerComponent({ id: "ecommerce-deals", name: "E-Commerce Deals", category: "ecommerce", variant: "deals", description: "Sale cards with countdown", tags: ["ecommerce", "deals", "sale", "discount", "offers", "clearance"], code: `export default function Ecommerce() { const deals=[{img:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",name:"Classic Watch",was:349,now:199,off:"43%"},{img:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",name:"Studio Headphones",was:249,now:149,off:"40%"},{img:"https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=400&h=400&fit=crop",name:"Running Shoes",was:189,now:99,off:"48%"}]; return (<section className="py-24 px-6 bg-red-50"><div className="max-w-7xl mx-auto"><div className="text-center mb-12"><span className="inline-block text-sm font-bold text-red-600 bg-red-100 px-4 py-1.5 rounded-full mb-4">🔥 Flash Sale — Ends in 23:45:12</span><h2 className="text-4xl font-bold text-gray-900">Up to 48% Off</h2></div><div className="grid md:grid-cols-3 gap-6">{deals.map((d,i)=>(<div key={i} className="bg-white rounded-2xl overflow-hidden shadow-sm hover:shadow-lg transition-shadow"><div className="relative"><img src={d.img} alt={d.name} className="w-full aspect-square object-cover" /><span className="absolute top-3 right-3 bg-red-600 text-white text-xs font-bold px-2.5 py-1 rounded-full">-{d.off}</span></div><div className="p-5"><h3 className="font-semibold text-gray-900">{d.name}</h3><div className="flex items-center gap-2 mt-2"><span className="text-xl font-bold text-red-600">\${d.now}</span><span className="text-sm text-gray-400 line-through">\${d.was}</span></div><button className="w-full mt-3 py-2.5 bg-red-600 text-white font-semibold rounded-xl hover:bg-red-700 transition-colors">Add to Cart</button></div></div>))}</div></div></section>); }` });

// ── ECOMMERCE: Reviews ──
registerComponent({ id: "ecommerce-reviews", name: "Product Reviews", category: "ecommerce", variant: "reviews", description: "Star ratings and review cards", tags: ["ecommerce", "reviews", "ratings", "feedback", "stars", "customers"], code: `export default function Ecommerce() { const reviews=[{name:"Jessica M.",avatar:"https://randomuser.me/api/portraits/women/32.jpg",stars:5,text:"Absolutely love this product! Quality exceeded my expectations. Fast shipping too.",date:"2 days ago",verified:true},{name:"Thomas R.",avatar:"https://randomuser.me/api/portraits/men/45.jpg",stars:4,text:"Great value for the price. Solid build quality. Only minor issue is the packaging could be better.",date:"1 week ago",verified:true},{name:"Amanda K.",avatar:"https://randomuser.me/api/portraits/women/56.jpg",stars:5,text:"Third time ordering from here. Consistent quality every time. Highly recommend!",date:"2 weeks ago",verified:true}]; return (<section className="py-24 px-6 bg-white"><div className="max-w-4xl mx-auto"><div className="text-center mb-12"><h2 className="text-4xl font-bold text-gray-900 mb-2">Customer Reviews</h2><div className="flex items-center justify-center gap-2"><span className="text-amber-400 text-lg">★★★★★</span><span className="text-gray-600">4.8 out of 5 (2,847 reviews)</span></div></div><div className="space-y-6">{reviews.map((r,i)=>(<div key={i} className="bg-gray-50 rounded-2xl p-6"><div className="flex items-center gap-3 mb-3"><img src={r.avatar} alt={r.name} className="w-10 h-10 rounded-full object-cover" /><div><div className="flex items-center gap-2"><span className="font-semibold text-gray-900">{r.name}</span>{r.verified && <span className="text-xs text-emerald-600 bg-emerald-50 px-2 py-0.5 rounded-full">Verified</span>}</div><div className="flex items-center gap-2"><span className="text-amber-400 text-sm">{"★".repeat(r.stars)}{"☆".repeat(5-r.stars)}</span><span className="text-xs text-gray-400">{r.date}</span></div></div></div><p className="text-gray-700">{r.text}</p></div>))}</div></div></section>); }` });

// ── ECOMMERCE: Cart ──
registerComponent({ id: "ecommerce-cart", name: "Mini Cart", category: "ecommerce", variant: "cart", description: "Cart summary with items", tags: ["ecommerce", "cart", "checkout", "order", "basket"], code: `export default function Ecommerce() { const items=[{name:"Minimal Watch",price:249,qty:1,img:"https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=100&h=100&fit=crop"},{name:"Pro Headphones",price:179,qty:1,img:"https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=100&h=100&fit=crop"},{name:"Sport Sneakers",price:129,qty:2,img:"https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=100&h=100&fit=crop"}]; const total=items.reduce((s,i)=>s+i.price*i.qty,0); return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-lg mx-auto"><div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden"><div className="px-6 py-4 border-b border-gray-100"><h2 className="text-xl font-bold text-gray-900">Your Cart ({items.length})</h2></div><div className="divide-y divide-gray-100">{items.map((item,i)=>(<div key={i} className="px-6 py-4 flex items-center gap-4"><img src={item.img} alt={item.name} className="w-16 h-16 rounded-lg object-cover" /><div className="flex-1"><h3 className="font-medium text-gray-900">{item.name}</h3><p className="text-sm text-gray-500">Qty: {item.qty}</p></div><span className="font-semibold text-gray-900">\${item.price * item.qty}</span></div>))}</div><div className="px-6 py-4 bg-gray-50"><div className="flex items-center justify-between mb-4"><span className="text-gray-600">Subtotal</span><span className="text-xl font-bold text-gray-900">\${total}</span></div><button className="w-full py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Checkout</button><p className="text-xs text-gray-400 text-center mt-3">Free shipping on orders over $100</p></div></div></div></section>); }` });

// ── FORM: Multi-Step ──
registerComponent({ id: "form-multi-step", name: "Multi-Step Form", category: "forms", variant: "multi-step", description: "3-step wizard with progress", tags: ["form", "wizard", "multi-step", "onboarding", "registration"], code: `export default function Forms() { return (<section className="py-24 px-6 bg-white"><div className="max-w-lg mx-auto"><div className="flex items-center justify-between mb-8"><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-indigo-600 text-white flex items-center justify-center text-sm font-bold">1</div><span className="text-sm font-medium text-indigo-600 hidden sm:block">Account</span></div><div className="flex-1 h-px bg-gray-200 mx-2" /><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-gray-200 text-gray-500 flex items-center justify-center text-sm font-bold">2</div><span className="text-sm font-medium text-gray-400 hidden sm:block">Profile</span></div><div className="flex-1 h-px bg-gray-200 mx-2" /><div className="flex items-center gap-2"><div className="w-8 h-8 rounded-full bg-gray-200 text-gray-500 flex items-center justify-center text-sm font-bold">3</div><span className="text-sm font-medium text-gray-400 hidden sm:block">Preferences</span></div></div><div className="bg-gray-50 rounded-2xl p-8"><h2 className="text-2xl font-bold text-gray-900 mb-2">Create Your Account</h2><p className="text-gray-600 mb-6">Step 1 of 3 — Let's start with the basics</p><form className="space-y-4"><input type="text" placeholder="Full name" className="w-full px-4 py-3 border border-gray-200 rounded-xl" /><input type="email" placeholder="Email address" className="w-full px-4 py-3 border border-gray-200 rounded-xl" /><input type="password" placeholder="Create password" className="w-full px-4 py-3 border border-gray-200 rounded-xl" /><div className="flex justify-between pt-2"><button type="button" className="px-6 py-3 text-gray-500 font-medium">Back</button><button type="submit" className="px-8 py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Continue</button></div></form></div></div></section>); }` });

// ── MISC: Dashboard Screenshot ──
registerComponent({ id: "misc-dashboard", name: "Dashboard Preview", category: "misc", variant: "dashboard", description: "App dashboard in browser frame", tags: ["dashboard", "app", "screenshot", "preview", "product", "saas"], code: `export default function Misc() { return (<section className="py-24 px-6 bg-gray-900"><div className="max-w-5xl mx-auto text-center"><h2 className="text-4xl font-bold text-white mb-4">Powerful Dashboard</h2><p className="text-xl text-gray-400 mb-12">Everything you need to manage your business in one place.</p><div className="bg-gray-800 rounded-2xl p-2 shadow-2xl"><div className="bg-gray-700 rounded-t-xl px-4 py-2 flex items-center gap-2"><div className="flex gap-1.5"><div className="w-3 h-3 rounded-full bg-red-400" /><div className="w-3 h-3 rounded-full bg-yellow-400" /><div className="w-3 h-3 rounded-full bg-green-400" /></div><div className="flex-1 text-center"><span className="text-xs text-gray-400">app.yourcompany.com</span></div></div><div className="bg-gray-50 rounded-b-xl p-6"><div className="grid grid-cols-4 gap-4 mb-6">{[{label:"Revenue",val:"$48.2K",change:"+12%"},{label:"Users",val:"2,847",change:"+8%"},{label:"Orders",val:"1,234",change:"+24%"},{label:"Growth",val:"18.5%",change:"+3%"}].map((s,i)=>(<div key={i} className="bg-white rounded-xl p-4 border border-gray-100"><p className="text-xs text-gray-500">{s.label}</p><p className="text-xl font-bold text-gray-900 mt-1">{s.val}</p><p className="text-xs text-emerald-600 mt-1">{s.change}</p></div>))}</div><div className="bg-white rounded-xl p-4 border border-gray-100 h-40 flex items-center justify-center text-gray-300 text-sm">Chart Placeholder</div></div></div></div></section>); }` });

// ── MISC: App Screenshots ──
registerComponent({ id: "misc-screenshots", name: "App Screenshots", category: "misc", variant: "screenshots", description: "Phone frame screenshots", tags: ["screenshots", "mobile", "app", "phone", "ios", "android"], code: `export default function Misc() { return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto text-center"><h2 className="text-4xl font-bold text-gray-900 mb-4">Beautiful on Every Device</h2><p className="text-xl text-gray-600 mb-16">Designed for mobile, optimized for desktop.</p><div className="flex justify-center gap-8 items-end">{[{h:"h-[500px]",img:"https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=300&h=600&fit=crop"},{h:"h-[550px]",img:"https://images.unsplash.com/photo-1551650975-87deedd944c3?w=300&h=600&fit=crop"},{h:"h-[500px]",img:"https://images.unsplash.com/photo-1526498460520-4c246339dccb?w=300&h=600&fit=crop"}].map((s,i)=>(<div key={i} className={\`w-48 \${s.h} bg-gray-900 rounded-[2rem] p-2 shadow-xl\`}><div className="w-full h-full rounded-[1.5rem] overflow-hidden bg-white"><img src={s.img} alt="" className="w-full h-full object-cover" /></div></div>))}</div></div></section>); }` });

// ── FORM: Survey/Feedback ──
registerComponent({ id: "form-survey", name: "Survey Form", category: "forms", variant: "survey", description: "Rating and feedback form", tags: ["survey", "feedback", "rating", "nps", "review"], code: `export default function Forms() { return (<section className="py-24 px-6 bg-white"><div className="max-w-lg mx-auto text-center"><h2 className="text-3xl font-bold text-gray-900 mb-2">How was your experience?</h2><p className="text-gray-600 mb-8">Your feedback helps us improve.</p><div className="flex justify-center gap-3 mb-8">{["😡","😕","😐","🙂","😍"].map((e,i)=>(<button key={i} className="w-14 h-14 text-3xl rounded-xl border-2 border-gray-200 hover:border-indigo-400 hover:scale-110 transition-all">{e}</button>))}</div><textarea rows={4} placeholder="Tell us more (optional)" className="w-full px-4 py-3 border border-gray-200 rounded-xl resize-none mb-4" /><button className="w-full py-3 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-700 transition-colors">Submit Feedback</button></div></section>); }` });

// ── MISC: App Download CTA ──
registerComponent({ id: "cta-app-download", name: "App Download CTA", category: "cta", variant: "app-download", description: "App store buttons with phone mockup", tags: ["app", "download", "ios", "android", "mobile", "install"], code: `export default function CTA() { return (<section className="py-24 px-6 bg-gradient-to-br from-gray-900 to-gray-800"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-16 items-center"><div><span className="text-sm font-semibold text-indigo-400">Now Available on Mobile</span><h2 className="text-4xl font-bold text-white mt-3 mb-4">Take It Everywhere</h2><p className="text-xl text-gray-400 mb-8">All the power of our platform, right in your pocket. Available on iOS and Android.</p><div className="flex gap-4"><button className="px-6 py-3 bg-white text-gray-900 rounded-xl font-semibold hover:bg-gray-100 transition-colors flex items-center gap-2"><span className="text-2xl">🍎</span><div className="text-left"><div className="text-[10px] leading-none">Download on the</div><div className="text-sm font-bold">App Store</div></div></button><button className="px-6 py-3 bg-white text-gray-900 rounded-xl font-semibold hover:bg-gray-100 transition-colors flex items-center gap-2"><span className="text-2xl">▶️</span><div className="text-left"><div className="text-[10px] leading-none">Get it on</div><div className="text-sm font-bold">Google Play</div></div></button></div></div><div className="flex justify-center"><div className="w-64 h-[500px] bg-gray-700 rounded-[2.5rem] p-3 shadow-2xl"><div className="w-full h-full rounded-[2rem] bg-gradient-to-br from-indigo-500 to-purple-600 flex items-center justify-center"><span className="text-6xl">📱</span></div></div></div></div></section>); }` });

// ── MISC: Social Proof Bar ──
registerComponent({ id: "misc-social-proof", name: "Social Proof Bar", category: "misc", variant: "social-proof", description: "Trust badges and stats strip", tags: ["social proof", "trust", "badges", "awards", "featured", "press"], code: `export default function Misc() { return (<section className="py-8 px-6 bg-gray-50 border-y border-gray-100"><div className="max-w-7xl mx-auto flex flex-wrap items-center justify-center gap-8 md:gap-16"><div className="text-center"><div className="text-2xl font-bold text-gray-900">4.9/5</div><div className="text-xs text-gray-500">Product Hunt</div></div><div className="text-center"><div className="text-2xl font-bold text-gray-900">#1</div><div className="text-xs text-gray-500">G2 Leader 2026</div></div><div className="text-center"><div className="text-2xl font-bold text-gray-900">50K+</div><div className="text-xs text-gray-500">Active Users</div></div><div className="text-center"><div className="text-2xl font-bold text-gray-900">99.9%</div><div className="text-xs text-gray-500">Uptime SLA</div></div><div className="text-center"><div className="text-2xl font-bold text-gray-900">SOC 2</div><div className="text-xs text-gray-500">Certified</div></div></div></section>); }` });

// ── HERO: Waitlist/Coming Soon ──
registerComponent({ id: "hero-waitlist", name: "Hero Waitlist", category: "hero", variant: "waitlist", description: "Coming soon hero with email capture", tags: ["hero", "waitlist", "coming soon", "launch", "prelaunch", "beta"], code: `export default function Hero() { return (<section className="min-h-screen flex items-center justify-center px-6 bg-gradient-to-br from-gray-900 via-indigo-950 to-gray-900"><div className="max-w-2xl mx-auto text-center"><span className="inline-block text-sm font-semibold text-indigo-300 bg-indigo-500/20 px-4 py-1.5 rounded-full mb-6">🚀 Launching Q2 2026</span><h1 className="text-5xl md:text-7xl font-bold text-white mb-6">Something<br /><span className="bg-gradient-to-r from-indigo-400 to-purple-400 bg-clip-text text-transparent">Incredible</span><br />Is Coming</h1><p className="text-xl text-gray-400 mb-10">We're building the future of [industry]. Be the first to experience it.</p><div className="flex gap-3 max-w-md mx-auto mb-6"><input type="email" placeholder="Enter your email" className="flex-1 px-5 py-4 rounded-xl bg-white/10 border border-white/20 text-white placeholder-gray-500 focus:ring-2 focus:ring-indigo-500 focus:border-transparent" /><button className="px-8 py-4 bg-indigo-600 text-white font-semibold rounded-xl hover:bg-indigo-500 transition-colors">Join Waitlist</button></div><p className="text-sm text-gray-500">🎉 3,247 people already joined · No spam, ever</p></div></section>); }` });

// ── FEATURES: Icon Cards (Light) ──
registerComponent({ id: "features-icon-cards-light", name: "Features Icon Cards Light", category: "features", variant: "icon-cards-light", description: "Light theme feature cards with colored icons", tags: ["features", "cards", "light", "clean", "minimal", "white"], code: `export default function Features() { const features=[{icon:"🎯",color:"bg-red-50 text-red-600",title:"Precision Targeting",desc:"Reach the right audience with AI-powered segmentation that learns and adapts to your users."},{icon:"⚡",color:"bg-amber-50 text-amber-600",title:"Lightning Performance",desc:"Sub-100ms response times with our globally distributed edge network. Speed is not optional."},{icon:"🔒",color:"bg-emerald-50 text-emerald-600",title:"Enterprise Security",desc:"SOC 2 Type II certified. End-to-end encryption. Your data never leaves our secure infrastructure."},{icon:"📊",color:"bg-blue-50 text-blue-600",title:"Real-time Analytics",desc:"Track every metric that matters. Beautiful dashboards that update in real-time."},{icon:"🔌",color:"bg-purple-50 text-purple-600",title:"200+ Integrations",desc:"Connect with the tools you already use. Slack, Salesforce, HubSpot, and 197 more."},{icon:"🌍",color:"bg-cyan-50 text-cyan-600",title:"Global Scale",desc:"30 regions worldwide. CDN-backed delivery. Every user gets a fast experience."}]; return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto"><div className="text-center mb-16"><h2 className="text-4xl font-bold text-gray-900 mb-4">Built for Modern Teams</h2><p className="text-xl text-gray-600 max-w-2xl mx-auto">Everything you need to build, launch, and scale — without the infrastructure headaches.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">{features.map((f,i)=>(<div key={i} className="p-8 rounded-2xl border border-gray-100 hover:shadow-lg hover:-translate-y-1 transition-all duration-300"><div className={\`w-12 h-12 rounded-xl \${f.color} flex items-center justify-center text-xl mb-5\`}>{f.icon}</div><h3 className="text-xl font-semibold text-gray-900 mb-2">{f.title}</h3><p className="text-gray-600 leading-relaxed">{f.desc}</p></div>))}</div></div></section>); }` });

// ── PRICING: Toggle Monthly/Annual ──
registerComponent({ id: "pricing-toggle-full", name: "Pricing Toggle Full", category: "pricing", variant: "toggle-full", description: "Monthly/annual toggle with 3 tiers", tags: ["pricing", "toggle", "monthly", "annual", "plans", "subscription"], code: `export default function Pricing() { const [annual, setAnnual] = React.useState(false); const plans=[{name:"Starter",monthly:0,annual:0,features:["5 projects","1GB storage","Community support"],cta:"Get Started",featured:false},{name:"Pro",monthly:49,annual:39,features:["Unlimited projects","100GB storage","Priority support","Custom domains","API access"],cta:"Start Free Trial",featured:true},{name:"Enterprise",monthly:199,annual:159,features:["Everything in Pro","Unlimited storage","Dedicated support","SSO & SAML","SLA guarantee","Custom integrations"],cta:"Contact Sales",featured:false}]; return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-7xl mx-auto"><div className="text-center mb-12"><h2 className="text-4xl font-bold text-gray-900 mb-4">Simple Pricing</h2><div className="flex items-center justify-center gap-3 mt-6"><span className={\`text-sm \${!annual?"text-gray-900 font-semibold":"text-gray-500"}\`}>Monthly</span><button onClick={()=>setAnnual(!annual)} className={\`relative w-14 h-7 rounded-full transition-colors \${annual?"bg-indigo-600":"bg-gray-300"}\`}><div className={\`absolute top-0.5 w-6 h-6 bg-white rounded-full shadow transition-transform \${annual?"translate-x-7":"translate-x-0.5"}\`}/></button><span className={\`text-sm \${annual?"text-gray-900 font-semibold":"text-gray-500"}\`}>Annual</span>{annual&&<span className="text-xs font-semibold text-emerald-600 bg-emerald-50 px-2 py-1 rounded-full">Save 20%</span>}</div></div><div className="grid md:grid-cols-3 gap-8 max-w-5xl mx-auto">{plans.map((p,i)=>(<div key={i} className={\`rounded-2xl p-8 \${p.featured?"bg-indigo-600 text-white ring-4 ring-indigo-200 scale-105":"bg-white border border-gray-200"}\`}><h3 className={\`text-xl font-semibold mb-2 \${p.featured?"text-white":"text-gray-900"}\`}>{p.name}</h3><div className="flex items-baseline gap-1 mb-6"><span className={\`text-5xl font-bold \${p.featured?"text-white":"text-gray-900"}\`}>\${annual?p.annual:p.monthly}</span><span className={\`text-sm \${p.featured?"text-indigo-200":"text-gray-500"}\`}>/mo</span></div><ul className="space-y-3 mb-8">{p.features.map((f,j)=>(<li key={j} className={\`flex items-center gap-2 text-sm \${p.featured?"text-indigo-100":"text-gray-600"}\`}><span className={\`\${p.featured?"text-indigo-200":"text-indigo-500"}\`}>✓</span>{f}</li>))}</ul><button className={\`w-full py-3 rounded-xl font-semibold text-sm transition-colors \${p.featured?"bg-white text-indigo-600 hover:bg-indigo-50":"bg-indigo-600 text-white hover:bg-indigo-700"}\`}>{p.cta}</button></div>))}</div></div></section>); }` });

// ── ABOUT: Founder Story ──
registerComponent({ id: "about-founder", name: "About Founder", category: "about", variant: "founder", description: "Founder story with large photo", tags: ["about", "founder", "story", "origin", "ceo", "personal"], code: `export default function About() { return (<section className="py-24 px-6 bg-white"><div className="max-w-7xl mx-auto grid lg:grid-cols-2 gap-16 items-center"><div><img src="https://randomuser.me/api/portraits/men/32.jpg" alt="Founder" className="w-full max-w-md rounded-2xl shadow-lg mx-auto" /></div><div><span className="text-sm font-semibold text-indigo-600 bg-indigo-50 px-3 py-1 rounded-full">Our Story</span><h2 className="text-4xl font-bold text-gray-900 mt-4 mb-6">Built from Frustration, Driven by Purpose</h2><div className="text-lg text-gray-600 leading-relaxed space-y-4"><p>"I spent 15 years watching teams waste months on projects that should take days. The tools were there, but they were fragmented, expensive, and designed for engineers — not for the people who actually had the ideas."</p><p>"So I built this. One platform that takes you from idea to launch in minutes, not months. No coding required. No design degree needed. Just describe what you want, and AI builds it."</p><p>"We're not trying to replace developers. We're trying to give everyone else the same superpower."</p></div><div className="mt-6"><div className="font-semibold text-gray-900 text-lg">Marcus Chen</div><div className="text-gray-500">Founder & CEO</div></div></div></div></section>); }` });

// ── ABOUT: Timeline ──
registerComponent({ id: "about-timeline", name: "About Timeline", category: "about", variant: "timeline", description: "Company history timeline", tags: ["about", "timeline", "history", "milestones", "journey"], code: `export default function About() { const milestones=[{year:"2024",title:"The Idea",desc:"Founded in a garage with nothing but a laptop and a vision."},{year:"2025",title:"First 1,000 Users",desc:"Launched beta. Hit 1,000 users in the first month."},{year:"2025",title:"$2M Seed Round",desc:"Raised from top-tier investors who believed in the mission."},{year:"2026",title:"10,000+ Users",desc:"Scaled to 10K users across 50+ countries. Product-market fit confirmed."}]; return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-3xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">Our Journey</h2><div className="relative"><div className="absolute left-6 top-0 bottom-0 w-px bg-indigo-200" />{milestones.map((m,i)=>(<div key={i} className="relative pl-16 pb-12 last:pb-0"><div className="absolute left-4 w-5 h-5 rounded-full bg-indigo-600 ring-4 ring-indigo-100 -translate-x-1/2" /><div className="text-sm font-semibold text-indigo-600 mb-1">{m.year}</div><h3 className="text-xl font-semibold text-gray-900 mb-2">{m.title}</h3><p className="text-gray-600">{m.desc}</p></div>))}</div></div></section>); }` });

// ── FOOTER: Dark Gradient ──
registerComponent({ id: "footer-dark-gradient", name: "Footer Dark Gradient", category: "footer", variant: "dark-gradient", description: "Gradient dark footer with columns", tags: ["footer", "dark", "gradient", "premium", "modern"], code: `export default function Footer() { return (<footer className="bg-gradient-to-b from-gray-900 to-navy-950 text-gray-400 py-20 px-6"><div className="max-w-7xl mx-auto grid md:grid-cols-2 lg:grid-cols-4 gap-12"><div><span className="text-2xl font-bold text-white">Brand</span><p className="mt-4 text-sm leading-relaxed">The modern platform for building extraordinary products. Fast, reliable, beautiful.</p><div className="flex gap-3 mt-6"><a href="#" className="w-10 h-10 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors text-sm">𝕏</a><a href="#" className="w-10 h-10 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors text-sm">in</a><a href="#" className="w-10 h-10 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors text-sm">gh</a></div></div><div><h4 className="font-semibold text-white mb-4">Product</h4><ul className="space-y-2 text-sm"><li><a href="#" className="hover:text-white transition-colors">Features</a></li><li><a href="#" className="hover:text-white transition-colors">Pricing</a></li><li><a href="#" className="hover:text-white transition-colors">Integrations</a></li><li><a href="#" className="hover:text-white transition-colors">Changelog</a></li></ul></div><div><h4 className="font-semibold text-white mb-4">Resources</h4><ul className="space-y-2 text-sm"><li><a href="#" className="hover:text-white transition-colors">Documentation</a></li><li><a href="#" className="hover:text-white transition-colors">API Reference</a></li><li><a href="#" className="hover:text-white transition-colors">Blog</a></li><li><a href="#" className="hover:text-white transition-colors">Community</a></li></ul></div><div><h4 className="font-semibold text-white mb-4">Company</h4><ul className="space-y-2 text-sm"><li><a href="#" className="hover:text-white transition-colors">About</a></li><li><a href="#" className="hover:text-white transition-colors">Careers</a></li><li><a href="#" className="hover:text-white transition-colors">Privacy</a></li><li><a href="#" className="hover:text-white transition-colors">Terms</a></li></ul></div></div><div className="max-w-7xl mx-auto mt-16 pt-8 border-t border-white/10 text-sm text-center">© {new Date().getFullYear()} Brand. All rights reserved.</div></footer>); }` });

// ── CTA: Floating Bottom Bar ──
registerComponent({ id: "cta-floating", name: "CTA Floating Bar", category: "cta", variant: "floating", description: "Sticky bottom bar CTA", tags: ["cta", "floating", "sticky", "bar", "bottom", "persistent"], code: `export default function CTA() { return (<div className="sticky bottom-0 left-0 right-0 z-40 bg-white/95 backdrop-blur-lg border-t border-gray-200 py-3 px-6"><div className="max-w-7xl mx-auto flex items-center justify-between"><div><h3 className="font-semibold text-gray-900">Ready to get started?</h3><p className="text-sm text-gray-500">Free plan available. No credit card required.</p></div><div className="flex gap-3"><button className="px-6 py-2.5 bg-indigo-600 text-white font-semibold rounded-lg hover:bg-indigo-700 transition-colors text-sm">Start Free</button><button className="px-6 py-2.5 border border-gray-200 text-gray-700 font-medium rounded-lg hover:bg-gray-50 transition-colors text-sm">Learn More</button></div></div></div>); }` });

// ── MISC: Testimonial Wall ──
registerComponent({ id: "misc-testimonial-wall", name: "Testimonial Wall", category: "misc", variant: "testimonial-wall", description: "Twitter-style testimonial grid", tags: ["testimonials", "wall", "twitter", "social", "reviews", "grid"], code: `export default function Misc() { const tweets=[{name:"Alex R.",handle:"@alexr",text:"Just switched to this platform. Built my entire landing page in 45 seconds. Not minutes. SECONDS. 🤯",avatar:"https://randomuser.me/api/portraits/men/22.jpg"},{name:"Sarah K.",handle:"@sarahk",text:"The AI quality is insane. It generated a better design than our agency charged us $15K for.",avatar:"https://randomuser.me/api/portraits/women/33.jpg"},{name:"Mike T.",handle:"@miket",text:"3 months in. Zero regrets. Our dev cycle went from weeks to hours. This is the future.",avatar:"https://randomuser.me/api/portraits/men/44.jpg"},{name:"Emily W.",handle:"@emilyw",text:"Finally an AI builder that actually produces production-ready code. Not toy demos. Real sites.",avatar:"https://randomuser.me/api/portraits/women/55.jpg"},{name:"James L.",handle:"@jamesl",text:"Showed this to my CEO. She immediately asked 'why aren't we using this for everything?'",avatar:"https://randomuser.me/api/portraits/men/66.jpg"},{name:"Priya N.",handle:"@priyan",text:"The component library is 🔥. Every section looks like a $50K agency designed it.",avatar:"https://randomuser.me/api/portraits/women/77.jpg"}]; return (<section className="py-24 px-6 bg-gray-50"><div className="max-w-7xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">What People Are Saying</h2><div className="columns-1 md:columns-2 lg:columns-3 gap-4">{tweets.map((t,i)=>(<div key={i} className="mb-4 break-inside-avoid bg-white rounded-2xl p-6 border border-gray-100 hover:shadow-md transition-shadow"><div className="flex items-center gap-3 mb-3"><img src={t.avatar} alt={t.name} className="w-10 h-10 rounded-full" /><div><div className="font-semibold text-gray-900 text-sm">{t.name}</div><div className="text-xs text-gray-400">{t.handle}</div></div></div><p className="text-gray-700 text-sm leading-relaxed">{t.text}</p></div>))}</div></div></section>); }` });

// ── FEATURES: Bento (Light) ──
registerComponent({ id: "features-bento-light", name: "Features Bento Light", category: "features", variant: "bento-light", description: "Bento grid layout on light background", tags: ["features", "bento", "grid", "apple", "modern", "light"], code: `export default function Features() { const items=[{span:"md:col-span-2",title:"AI-Powered Generation",desc:"Describe what you want. Watch it build itself in real-time.",bg:"bg-gradient-to-br from-indigo-50 to-purple-50"},{span:"",title:"Instant Preview",desc:"See your site in under 1 second.",bg:"bg-gradient-to-br from-cyan-50 to-blue-50"},{span:"",title:"One-Click Deploy",desc:"Publish to your custom domain instantly.",bg:"bg-gradient-to-br from-emerald-50 to-green-50"},{span:"",title:"React Output",desc:"Real React code you can extend.",bg:"bg-gradient-to-br from-amber-50 to-orange-50"},{span:"md:col-span-2",title:"100+ Components",desc:"Hand-crafted sections assembled by AI. Every combination looks professional.",bg:"bg-gradient-to-br from-rose-50 to-pink-50"}]; return (<section className="py-24 px-6 bg-white"><div className="max-w-5xl mx-auto"><h2 className="text-4xl font-bold text-gray-900 text-center mb-16">Built Different</h2><div className="grid md:grid-cols-3 gap-4">{items.map((f,i)=>(<div key={i} className={\`\${f.span} \${f.bg} rounded-2xl p-8 hover:shadow-lg transition-shadow cursor-default\`}><h3 className="text-xl font-semibold text-gray-900 mb-2">{f.title}</h3><p className="text-gray-600">{f.desc}</p></div>))}</div></div></section>); }` });

// ── HERO: Product Launch ──
registerComponent({ id: "hero-product-launch", name: "Hero Product Launch", category: "hero", variant: "product-launch", description: "Product launch hero with countdown", tags: ["hero", "launch", "product", "announcement", "new"], code: `export default function Hero() { return (<section className="min-h-[80vh] flex items-center px-6 bg-gradient-to-br from-violet-600 via-purple-600 to-indigo-700"><div className="max-w-4xl mx-auto text-center"><span className="inline-flex items-center gap-2 text-sm font-semibold text-purple-200 bg-white/10 backdrop-blur-sm px-4 py-2 rounded-full mb-8">🎉 Just Launched — Version 2.0</span><h1 className="text-5xl md:text-7xl font-bold text-white mb-6 leading-tight">The Future of<br /><span className="bg-gradient-to-r from-amber-200 to-yellow-200 bg-clip-text text-transparent">Building</span> Is Here</h1><p className="text-xl text-purple-200 mb-10 max-w-2xl mx-auto">10x faster. 100x more powerful. Completely reimagined from the ground up.</p><div className="flex flex-wrap gap-4 justify-center"><button className="px-8 py-4 bg-white text-purple-700 font-semibold rounded-xl hover:bg-purple-50 transition-colors shadow-lg shadow-purple-900/30">Try It Now — Free</button><button className="px-8 py-4 bg-white/10 backdrop-blur-sm text-white font-semibold rounded-xl hover:bg-white/20 transition-colors border border-white/20">Watch the 2-min Demo</button></div></div></section>); }` });

// ── TESTIMONIALS: Single Featured ──
registerComponent({ id: "testimonials-single", name: "Testimonial Single Featured", category: "testimonials", variant: "single-featured", description: "One large featured testimonial", tags: ["testimonial", "single", "featured", "quote", "review", "customer"], code: `export default function Testimonials() { return (<section className="py-24 px-6 bg-white"><div className="max-w-4xl mx-auto text-center"><div className="text-6xl mb-6">❝</div><blockquote className="text-2xl md:text-3xl font-medium text-gray-900 leading-relaxed mb-8">"We replaced our entire $180K/year tech stack with this single platform. The AI generates better code than our junior developers, and it does it in seconds."</blockquote><div className="flex items-center justify-center gap-4"><img src="https://randomuser.me/api/portraits/women/28.jpg" alt="Lisa Chen" className="w-16 h-16 rounded-full object-cover ring-4 ring-gray-100" /><div className="text-left"><div className="font-semibold text-gray-900 text-lg">Lisa Chen</div><div className="text-gray-500">CTO, DataFlow Inc</div><div className="text-amber-400 text-sm mt-0.5">★★★★★</div></div></div></div></section>); }` });

// ── STATS: Dark with Icons ──
registerComponent({ id: "stats-icons-dark", name: "Stats with Icons Dark", category: "stats", variant: "icons-dark", description: "Stats with icons on dark background", tags: ["stats", "numbers", "metrics", "dark", "icons", "data"], code: `export default function Stats() { const stats=[{icon:"🚀",value:"< 30s",label:"Average Build Time"},{icon:"🎨",value:"100+",label:"Component Library"},{icon:"🌍",value:"50+",label:"Countries Served"},{icon:"⭐",value:"4.9/5",label:"User Rating"}]; return (<section className="py-20 px-6 bg-gray-900"><div className="max-w-7xl mx-auto grid grid-cols-2 md:grid-cols-4 gap-8">{stats.map((s,i)=>(<div key={i} className="text-center group"><div className="text-3xl mb-3 group-hover:scale-125 transition-transform">{s.icon}</div><div className="text-3xl md:text-4xl font-bold text-white mb-1">{s.value}</div><div className="text-sm text-gray-400">{s.label}</div></div>))}</div></section>); }` });

// ── NAVBAR: App Style ──
registerComponent({ id: "navbar-app", name: "Navbar App Style", category: "navbar", variant: "app", description: "App-style nav with user avatar", tags: ["navbar", "app", "dashboard", "user", "avatar", "logged-in"], code: `export default function Navbar() { return (<nav className="sticky top-0 z-50 bg-white border-b border-gray-100"><div className="max-w-7xl mx-auto px-6 h-16 flex items-center justify-between"><div className="flex items-center gap-8"><span className="text-xl font-bold text-gray-900">Brand</span><div className="hidden md:flex items-center gap-1"><a href="#" className="px-3 py-2 text-sm text-indigo-600 bg-indigo-50 rounded-lg font-medium">Dashboard</a><a href="#" className="px-3 py-2 text-sm text-gray-600 hover:bg-gray-50 rounded-lg">Projects</a><a href="#" className="px-3 py-2 text-sm text-gray-600 hover:bg-gray-50 rounded-lg">Analytics</a><a href="#" className="px-3 py-2 text-sm text-gray-600 hover:bg-gray-50 rounded-lg">Settings</a></div></div><div className="flex items-center gap-4"><button className="px-4 py-2 bg-indigo-600 text-white text-sm font-medium rounded-lg hover:bg-indigo-700 transition-colors">New Project</button><div className="w-9 h-9 rounded-full bg-gradient-to-br from-indigo-400 to-purple-500 flex items-center justify-center text-white text-sm font-bold">JD</div></div></div></nav>); }` });
