/**
 * /api/seo/submit-sitemap — push our URLs to Bing + Yandex + IndexNow
 * relay in one call.
 *
 * Pulls the current sitemap from /sitemap.xml (which already includes
 * the programmatic /compare/[competitor] pages because src/app/sitemap.ts
 * was extended to enumerate them) and POSTs the URL list to
 * api.indexnow.org, bing.com/indexnow, and yandex.com/indexnow.
 *
 * Triggers:
 *   - Manual: GET this endpoint from the admin dashboard
 *   - Cron:   GET with ?secret=$CRON_SECRET on a daily schedule via
 *             Crontech (or any external scheduler)
 *   - Webhook: future — fire after every Vercel deploy
 *
 * Returns { ok, submitted, endpoints[] } so the admin can see exactly
 * what was acked by which engine.
 */

import { NextResponse } from "next/server";
import { submitToIndexNow, getIndexNowKey } from "@/lib/seo/indexnow";

export const maxDuration = 60;
export const dynamic = "force-dynamic";

const SITEMAP_URL = "https://zoobicon.com/sitemap.xml";

async function fetchSitemapUrls(): Promise<string[]> {
  const res = await fetch(SITEMAP_URL, {
    signal: AbortSignal.timeout(15000),
    headers: { Accept: "application/xml" },
  });
  if (!res.ok) throw new Error(`Sitemap fetch failed: HTTP ${res.status}`);
  const xml = await res.text();
  // Extract <loc>...</loc> entries. The sitemap is generated by
  // next-sitemap so it's well-formed and predictable.
  const matches = Array.from(xml.matchAll(/<loc>([^<]+)<\/loc>/g));
  return matches.map((m) => m[1].trim()).filter(Boolean);
}

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const secret = searchParams.get("secret");
  if (process.env.CRON_SECRET && secret !== process.env.CRON_SECRET) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Diagnose mode — checks env state without firing a submission. Used
  // by the admin SEO control room to surface configuration problems
  // before the user clicks "Submit."
  if (searchParams.get("diagnose") === "1") {
    const key = getIndexNowKey();
    return NextResponse.json({
      ok: Boolean(key),
      diagnose: true,
      indexNowKeyConfigured: Boolean(key),
      keyFileUrl: key ? `https://zoobicon.com/${key}.txt` : null,
      cronSecretConfigured: Boolean(process.env.CRON_SECRET),
      reason: key
        ? "INDEXNOW_KEY is set. Visit the keyFileUrl above to confirm it returns the key (200 OK)."
        : "INDEXNOW_KEY env not set. Set a UUID as INDEXNOW_KEY in Vercel, then visit /<key>.txt to verify.",
    });
  }

  if (!getIndexNowKey()) {
    return NextResponse.json(
      {
        ok: false,
        reason:
          "INDEXNOW_KEY env not set. Generate a UUID, set it as INDEXNOW_KEY in Vercel, and visit /<that-key>.txt to confirm verification.",
      },
      { status: 400 }
    );
  }

  let urls: string[];
  try {
    urls = await fetchSitemapUrls();
  } catch (err) {
    return NextResponse.json(
      { ok: false, reason: err instanceof Error ? err.message : "sitemap fetch failed" },
      { status: 502 }
    );
  }

  // Allow ?only= to narrow the submission (e.g. only=/compare/ for
  // a fresh programmatic-pages push)
  const only = searchParams.get("only");
  const filtered = only ? urls.filter((u) => u.includes(only)) : urls;

  const result = await submitToIndexNow(filtered);
  return NextResponse.json({
    timestamp: new Date().toISOString(),
    sitemapUrl: SITEMAP_URL,
    totalUrlsInSitemap: urls.length,
    ...result,
  });
}
