import { NextRequest, NextResponse } from "next/server";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { html, reactFiles, reactDeps, name, type = "react" } = body;

    // React project export (new default)
    if (type === "react" && reactFiles && typeof reactFiles === "object") {
      const projectName = sanitizeProjectName(name || "zoobicon-app");
      const files = generateReactProject(reactFiles, reactDeps || {}, projectName);
      return NextResponse.json({ files, projectName, type: "react" });
    }

    // Legacy HTML export (kept for backwards compatibility)
    if (!html || typeof html !== "string") {
      return NextResponse.json({ error: "Code is required (reactFiles or html)" }, { status: 400 });
    }

    const projectName = sanitizeProjectName(name || "zoobicon-site");
    const files = type === "nextjs"
      ? generateNextJsProject(html, projectName)
      : generateStaticProject(html, projectName);

    return NextResponse.json({ files, projectName });
  } catch (error) {
    console.error("GitHub export error:", error);
    return NextResponse.json({ error: "Failed to generate project files" }, { status: 500 });
  }
}

function sanitizeProjectName(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    || "zoobicon-site";
}

// ---------------------------------------------------------------------------
// Static project
// ---------------------------------------------------------------------------

function generateStaticProject(
  html: string,
  projectName: string
): Record<string, string> {
  return {
    "index.html": html,
    "README.md": generateStaticReadme(projectName),
    "package.json": JSON.stringify(
      {
        name: projectName,
        version: "1.0.0",
        description: `${projectName} — generated by Zoobicon`,
        scripts: {
          dev: "npx http-server . -p 3000 -o",
          start: "npx http-server . -p 3000",
        },
        devDependencies: {
          "http-server": "^14.1.1",
        },
      },
      null,
      2
    ),
    ".gitignore": [
      "node_modules",
      ".DS_Store",
      "Thumbs.db",
      ".env",
      ".env.local",
      "",
    ].join("\n"),
    "netlify.toml": [
      "[build]",
      '  publish = "."',
      "",
      "[[redirects]]",
      '  from = "/*"',
      '  to = "/index.html"',
      "  status = 200",
      "",
    ].join("\n"),
    "vercel.json": JSON.stringify(
      {
        rewrites: [{ source: "/(.*)", destination: "/index.html" }],
      },
      null,
      2
    ),
  };
}

function generateStaticReadme(projectName: string): string {
  return `# ${projectName}

Website generated by [Zoobicon](https://zoobicon.com).

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Open [http://localhost:3000](http://localhost:3000) in your browser.

## Deployment

### Netlify

Push this repository to GitHub and import it in [Netlify](https://netlify.com). The included \`netlify.toml\` handles the configuration.

### Vercel

Push this repository to GitHub and import it in [Vercel](https://vercel.com). The included \`vercel.json\` handles the configuration.

## License

MIT
`;
}

// ---------------------------------------------------------------------------
// Next.js project
// ---------------------------------------------------------------------------

function generateNextJsProject(
  html: string,
  projectName: string
): Record<string, string> {
  const { styles, bodyContent } = extractFromHtml(html);

  return {
    "package.json": JSON.stringify(
      {
        name: projectName,
        version: "1.0.0",
        private: true,
        scripts: {
          dev: "next dev",
          build: "next build",
          start: "next start",
          lint: "next lint",
        },
        dependencies: {
          next: "^14.2.0",
          react: "^18.3.0",
          "react-dom": "^18.3.0",
        },
        devDependencies: {
          typescript: "^5.4.0",
          "@types/node": "^20.12.0",
          "@types/react": "^18.3.0",
          "@types/react-dom": "^18.3.0",
          tailwindcss: "^3.4.0",
          postcss: "^8.4.0",
          autoprefixer: "^10.4.0",
        },
      },
      null,
      2
    ),
    "next.config.js": `/** @type {import('next').NextConfig} */
const nextConfig = {};

module.exports = nextConfig;
`,
    "tsconfig.json": JSON.stringify(
      {
        compilerOptions: {
          target: "es5",
          lib: ["dom", "dom.iterable", "esnext"],
          allowJs: true,
          skipLibCheck: true,
          strict: true,
          noEmit: true,
          esModuleInterop: true,
          module: "esnext",
          moduleResolution: "bundler",
          resolveJsonModule: true,
          isolatedModules: true,
          jsx: "preserve",
          incremental: true,
          plugins: [{ name: "next" }],
          paths: { "@/*": ["./src/*"] },
        },
        include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
        exclude: ["node_modules"],
      },
      null,
      2
    ),
    "tailwind.config.ts": `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};

export default config;
`,
    "postcss.config.js": `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`,
    "src/app/layout.tsx": `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Generated by Zoobicon",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
    "src/app/page.tsx": `export default function Home() {
  return (
    <main dangerouslySetInnerHTML={{ __html: \`${escapeTemplateLiteral(bodyContent)}\` }} />
  );
}
`,
    "src/app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;

${styles}
`,
    ".gitignore": [
      "node_modules",
      ".next",
      "out",
      ".DS_Store",
      "Thumbs.db",
      ".env",
      ".env.local",
      ".env.*.local",
      "npm-debug.log*",
      "",
    ].join("\n"),
    "README.md": generateNextJsReadme(projectName),
  };
}

function generateNextJsReadme(projectName: string): string {
  return `# ${projectName}

A [Next.js](https://nextjs.org) project generated by [Zoobicon](https://zoobicon.com).

## Getting Started

1. Install dependencies:
   \`\`\`bash
   npm install
   \`\`\`

2. Start the development server:
   \`\`\`bash
   npm run dev
   \`\`\`

3. Open [http://localhost:3000](http://localhost:3000) in your browser.

## Deployment

The easiest way to deploy is with [Vercel](https://vercel.com):

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new)

## License

MIT
`;
}

// ---------------------------------------------------------------------------
// HTML helpers
// ---------------------------------------------------------------------------

function extractFromHtml(html: string): {
  styles: string;
  bodyContent: string;
} {
  // Extract all <style> tag contents
  const styleRegex = /<style[^>]*>([\s\S]*?)<\/style>/gi;
  const styleBlocks: string[] = [];
  let match;
  while ((match = styleRegex.exec(html)) !== null) {
    styleBlocks.push(match[1].trim());
  }
  const styles = styleBlocks.join("\n\n");

  // Extract <body> content, falling back to the full HTML
  const bodyMatch = html.match(/<body[^>]*>([\s\S]*?)<\/body>/i);
  let bodyContent = bodyMatch ? bodyMatch[1].trim() : html;

  // Strip <script> tags from body for the React component
  bodyContent = bodyContent.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, "");

  return { styles, bodyContent };
}

function escapeTemplateLiteral(str: string): string {
  return str
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$\{/g, "\\${");
}

// ---------------------------------------------------------------------------
// React project (NEW — primary export format)
// ---------------------------------------------------------------------------

function generateReactProject(
  reactFiles: Record<string, string>,
  dependencies: Record<string, string>,
  projectName: string
): Record<string, string> {
  const files: Record<string, string> = {};

  // Package.json with all dependencies
  files["package.json"] = JSON.stringify({
    name: projectName,
    version: "1.0.0",
    private: true,
    scripts: {
      dev: "next dev",
      build: "next build",
      start: "next start",
      lint: "next lint",
    },
    dependencies: {
      next: "^15.0.0",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "lucide-react": "latest",
      ...dependencies,
    },
    devDependencies: {
      typescript: "^5.6.0",
      "@types/node": "^22.0.0",
      "@types/react": "^19.0.0",
      "@types/react-dom": "^19.0.0",
      tailwindcss: "^3.4.0",
      postcss: "^8.4.0",
      autoprefixer: "^10.4.0",
    },
  }, null, 2);

  // Next.js config
  files["next.config.js"] = `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;
`;

  // TypeScript config
  files["tsconfig.json"] = JSON.stringify({
    compilerOptions: {
      target: "es2017",
      lib: ["dom", "dom.iterable", "esnext"],
      allowJs: true,
      skipLibCheck: true,
      strict: true,
      noEmit: true,
      esModuleInterop: true,
      module: "esnext",
      moduleResolution: "bundler",
      resolveJsonModule: true,
      isolatedModules: true,
      jsx: "preserve",
      incremental: true,
      plugins: [{ name: "next" }],
      paths: { "@/*": ["./src/*"] },
    },
    include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
    exclude: ["node_modules"],
  }, null, 2);

  // Tailwind config
  files["tailwind.config.ts"] = `import type { Config } from "tailwindcss";
const config: Config = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  theme: { extend: {} },
  plugins: [],
};
export default config;
`;

  files["postcss.config.js"] = `module.exports = { plugins: { tailwindcss: {}, autoprefixer: {} } };
`;

  // Global CSS
  files["src/app/globals.css"] = `@tailwind base;
@tailwind components;
@tailwind utilities;
`;

  // Layout
  files["src/app/layout.tsx"] = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${projectName}",
  description: "Generated by Zoobicon — zoobicon.com",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

  // Map generated React files into the Next.js src structure
  // App.tsx becomes the main page
  if (reactFiles["App.tsx"]) {
    // Convert App.tsx to a Next.js page
    let appCode = reactFiles["App.tsx"];
    // Replace "export default function App" with page export
    appCode = appCode.replace(
      /export default function App/,
      "export default function Page"
    );
    // Fix component imports to use relative paths
    appCode = appCode.replace(
      /from ["']\.\/components\//g,
      'from "@/components/'
    );
    files["src/app/page.tsx"] = appCode;
  }

  // Copy all other component files
  for (const [path, content] of Object.entries(reactFiles)) {
    if (path === "App.tsx") continue; // Already handled
    if (path.startsWith("components/")) {
      files[`src/${path}`] = content;
    } else if (path.endsWith(".css")) {
      files[`src/app/${path}`] = content;
    } else {
      files[`src/${path}`] = content;
    }
  }

  // Git files
  files[".gitignore"] = "node_modules\n.next\nout\n.DS_Store\n.env\n.env.local\n";

  files["README.md"] = `# ${projectName}

A React/Next.js project generated by [Zoobicon](https://zoobicon.com).

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Open [http://localhost:3000](http://localhost:3000).

## Deploy to Vercel

[![Deploy with Vercel](https://vercel.com/button)](https://vercel.com/new)

## Built With

- [Next.js 15](https://nextjs.org)
- [React 19](https://react.dev)
- [Tailwind CSS](https://tailwindcss.com)
- [TypeScript](https://typescriptlang.org)

Generated by [Zoobicon](https://zoobicon.com) — zoobicon.com · zoobicon.ai · zoobicon.io · zoobicon.sh
`;

  return files;
}
