/**
 * Canonical add-on catalog shared by all marketplace API routes.
 * Prices are in USD cents (e.g. 2900 = $29.00). 0 = free.
 */

export interface Addon {
  id: string;
  name: string;
  description: string;
  price: number; // cents, 0 = free
  priceType: "free" | "one-time" | "monthly";
  priceLabel: string; // human-readable, e.g. "$29" or "$29/mo"
  category: string;
  featured: boolean;
  tag?: string;
  rating: number;
  installs: string;
  gradient: string;
  iconName: string; // lucide-react icon name for client-side mapping
}

export const ADDONS: Addon[] = [
  {
    id: "premium-template-pack",
    name: "Premium Template Pack",
    description: "50 hand-crafted, conversion-optimized website templates for SaaS, e-commerce, portfolios, and more.",
    price: 2900,
    priceType: "one-time",
    priceLabel: "$29",
    category: "Templates",
    featured: true,
    tag: "Best Seller",
    rating: 4.9,
    installs: "12.4K",
    gradient: "from-brand-500 to-brand-700",
    iconName: "Layout",
  },
  {
    id: "seo-campaign-agent",
    name: "SEO Campaign Agent",
    description: "Autonomous SEO agent that researches keywords, writes content, builds backlinks, and tracks rankings 24/7.",
    price: 2900,
    priceType: "monthly",
    priceLabel: "$29/mo",
    category: "AI Agents",
    featured: true,
    tag: "Top Rated",
    rating: 4.8,
    installs: "8.2K",
    gradient: "from-accent-cyan to-emerald-600",
    iconName: "Search",
  },
  {
    id: "ai-video-creator",
    name: "AI Video Creator",
    description: "Generate scroll-stopping videos for TikTok, Instagram, YouTube, and Facebook. No scripts needed.",
    price: 1900,
    priceType: "monthly",
    priceLabel: "$19/mo",
    category: "AI Agents",
    featured: true,
    rating: 4.7,
    installs: "6.8K",
    gradient: "from-accent-purple to-pink-600",
    iconName: "Video",
  },
  {
    id: "ai-email-support",
    name: "AI Email Support",
    description: "World-class AI customer support. Auto-replies, sentiment analysis, smart routing, 24/7 operation.",
    price: 2400,
    priceType: "monthly",
    priceLabel: "$24/mo",
    category: "AI Agents",
    tag: "New",
    featured: false,
    rating: 4.9,
    installs: "4.5K",
    gradient: "from-amber-500 to-orange-600",
    iconName: "Mail",
  },
  {
    id: "stripe-payments",
    name: "Stripe Payments",
    description: "Accept payments instantly. Stripe integration with checkout pages, subscriptions, and invoicing.",
    price: 0,
    priceType: "free",
    priceLabel: "Free",
    category: "E-Commerce",
    featured: false,
    rating: 4.8,
    installs: "15.1K",
    gradient: "from-indigo-500 to-blue-600",
    iconName: "CreditCard",
  },
  {
    id: "google-analytics",
    name: "Google Analytics",
    description: "Full Google Analytics 4 integration. Track visitors, conversions, and user behavior automatically.",
    price: 0,
    priceType: "free",
    priceLabel: "Free",
    category: "Analytics",
    featured: false,
    rating: 4.6,
    installs: "18.3K",
    gradient: "from-emerald-500 to-teal-600",
    iconName: "BarChart3",
  },
  {
    id: "social-media-manager",
    name: "Social Media Manager",
    description: "AI auto-creates, schedules, and publishes social media posts across all platforms. Hashtag optimization.",
    price: 1400,
    priceType: "monthly",
    priceLabel: "$14/mo",
    category: "Marketing",
    featured: false,
    rating: 4.5,
    installs: "5.1K",
    gradient: "from-cyan-500 to-blue-600",
    iconName: "MessageSquare",
  },
  {
    id: "ai-brand-kit",
    name: "AI Brand Kit",
    description: "Complete brand identity: logo, colors, typography, style guide — all AI-generated from your description.",
    price: 1900,
    priceType: "one-time",
    priceLabel: "$19",
    category: "Design",
    featured: false,
    rating: 4.7,
    installs: "7.9K",
    gradient: "from-pink-500 to-rose-600",
    iconName: "Palette",
  },
  {
    id: "ai-chatbot-builder",
    name: "AI Chatbot Builder",
    description: "Deploy custom AI chatbots on any website. Trained on your content, branded to your style. 24/7 support bot.",
    price: 1400,
    priceType: "monthly",
    priceLabel: "$14/mo",
    category: "AI Agents",
    featured: false,
    rating: 4.6,
    installs: "3.8K",
    gradient: "from-blue-500 to-indigo-600",
    iconName: "Bot",
  },
  {
    id: "custom-code-injection",
    name: "Custom Code Injection",
    description: "Add custom HTML, CSS, and JavaScript to any page. Header/footer injection, Google Tag Manager, pixels.",
    price: 0,
    priceType: "free",
    priceLabel: "Free",
    category: "Developer Tools",
    featured: false,
    rating: 4.4,
    installs: "9.2K",
    gradient: "from-slate-500 to-zinc-600",
    iconName: "Code2",
  },
  {
    id: "blog-cms-engine",
    name: "Blog & CMS Engine",
    description: "Full-featured blog with AI writing assistant, categories, tags, RSS feed, and SEO optimization built in.",
    price: 900,
    priceType: "monthly",
    priceLabel: "$9/mo",
    category: "Templates",
    featured: false,
    rating: 4.7,
    installs: "6.3K",
    gradient: "from-amber-600 to-yellow-500",
    iconName: "FileText",
  },
  {
    id: "image-optimizer",
    name: "Image Optimizer",
    description: "Auto-compress, resize, and convert images to WebP/AVIF. Lazy loading and responsive images built in.",
    price: 0,
    priceType: "free",
    priceLabel: "Free",
    category: "Developer Tools",
    featured: false,
    rating: 4.5,
    installs: "11.7K",
    gradient: "from-green-500 to-emerald-600",
    iconName: "Image",
  },
  {
    id: "custom-fonts-pack",
    name: "Custom Fonts Pack",
    description: "1,000+ premium web fonts. Google Fonts integration plus exclusive custom typefaces for your brand.",
    price: 900,
    priceType: "one-time",
    priceLabel: "$9",
    category: "Design",
    featured: false,
    rating: 4.3,
    installs: "8.6K",
    gradient: "from-rose-500 to-pink-600",
    iconName: "Type",
  },
  {
    id: "multi-language-i18n",
    name: "Multi-Language (i18n)",
    description: "Auto-translate your website into 30+ languages. AI-powered translations with locale-specific SEO.",
    price: 1400,
    priceType: "monthly",
    priceLabel: "$14/mo",
    category: "Integrations",
    featured: false,
    rating: 4.6,
    installs: "3.2K",
    gradient: "from-blue-500 to-indigo-600",
    iconName: "Globe",
  },
  {
    id: "lead-gen-forms",
    name: "Lead Gen & Forms",
    description: "Smart forms with conditional logic, file uploads, and CRM integrations. Captures and scores leads with AI.",
    price: 900,
    priceType: "monthly",
    priceLabel: "$9/mo",
    category: "Marketing",
    featured: false,
    rating: 4.7,
    installs: "7.4K",
    gradient: "from-orange-500 to-red-500",
    iconName: "Users",
  },
  {
    id: "uptime-monitor",
    name: "Uptime Monitor",
    description: "24/7 website monitoring with instant alerts via email, Slack, and SMS. 1-minute check intervals.",
    price: 0,
    priceType: "free",
    priceLabel: "Free",
    category: "Analytics",
    featured: false,
    rating: 4.4,
    installs: "5.6K",
    gradient: "from-teal-500 to-cyan-600",
    iconName: "Clock",
  },
  {
    id: "ab-testing-engine",
    name: "A/B Testing Engine",
    description: "Test headlines, layouts, CTAs, and more. AI-powered statistical analysis picks the winner for you.",
    price: 1900,
    priceType: "monthly",
    priceLabel: "$19/mo",
    category: "Analytics",
    tag: "New",
    featured: false,
    rating: 4.8,
    installs: "2.9K",
    gradient: "from-blue-500 to-blue-600",
    iconName: "TrendingUp",
  },
  {
    id: "email-marketing-suite",
    name: "Email Marketing Suite",
    description: "AI writes and designs email campaigns. Auto-segment audiences, drip sequences, analytics, and A/B testing.",
    price: 1400,
    priceType: "monthly",
    priceLabel: "$14/mo",
    category: "Marketing",
    featured: false,
    rating: 4.6,
    installs: "4.8K",
    gradient: "from-red-500 to-orange-500",
    iconName: "Megaphone",
  },
  {
    id: "ssl-security-suite",
    name: "SSL & Security Suite",
    description: "Wildcard SSL, DDoS protection, WAF, malware scanning, and automatic security patching. Enterprise-grade.",
    price: 900,
    priceType: "monthly",
    priceLabel: "$9/mo",
    category: "Integrations",
    featured: false,
    rating: 4.9,
    installs: "10.2K",
    gradient: "from-emerald-600 to-green-500",
    iconName: "Shield",
  },
  {
    id: "component-library",
    name: "Component Library",
    description: "200+ pre-built UI components: navbars, hero sections, pricing tables, footers, testimonials, and more.",
    price: 1900,
    priceType: "one-time",
    priceLabel: "$19",
    category: "Developer Tools",
    featured: false,
    rating: 4.5,
    installs: "6.1K",
    gradient: "from-sky-500 to-blue-600",
    iconName: "Layers",
  },
];
